import type { FacebookInputs, FacebookOutput } from '../types'
import { PROBLEM_DATA, COMPANY } from '../lib/companyProfile'
import { scoreContent } from '../lib/scoring'

const SHORT_POSTS: Record<string, string[]> = {
  'injection-molding-defects': [
    `The average injection molder loses $380,000/year to defect-related scrap.\n\nMost of it comes from process parameter drift that nobody catches until the reject bin is full.\n\nReal-time process monitoring — not end-of-run inspection — is what separates 1% defect rates from 5% defect rates.\n\nWhat does your current defect tracking look like? Comment below.\n\n🔗 plasticmolding.com`,
    `Sink marks. Flash. Short shots.\n\nThree of the most common injection molding defects. Each one has a specific root cause. None of them are random.\n\nThe plants that hold defect rates under 2% have one thing in common: they track process parameters every cycle, not just at startup.\n\nHow are you currently catching parameter drift? Drop it in the comments.\n\n🔗 plasticmolding.com`,
    `Your defect rate tells the story of your process control.\n\nIf it's above 3%, something upstream is drifting — and you're catching it at the end of the line instead of at the source.\n\nWhat's your current defect rate? What's the biggest driver?\n\n🔗 plasticmolding.com — PMT works with injection molders to reduce defect rates through process control, not more inspection.`,
  ],
  'tooling-failures': [
    `Unplanned tooling failures cost injection molders an average of $15,000–$22,000 per event in parts, labor, and lost production.\n\nThe 5 warning signs that always precede failure:\n• Flash appearing on parting lines\n• Cycle time creeping up without process changes\n• Ejector pin drag\n• Surface roughness increasing\n• Cooling imbalance causing part warpage\n\nAre you tracking these? Drop your maintenance approach in the comments.\n\n🔗 plasticmolding.com`,
    `Most tooling failures feel sudden. They almost never are.\n\nThe warning signs build over thousands of cycles. Most teams don't see them until something breaks.\n\nShot-count-based preventive maintenance intervals — not calendar dates — cut unplanned failures by 40–60%.\n\nHow often do you pull molds for planned maintenance? Share below.\n\n🔗 plasticmolding.com`,
    `Emergency mold repairs cost 2–3× more than planned maintenance. And that's before you count the production disruption.\n\nThe ROI on a structured PM program is not complicated. The hard part is building the discipline to follow it.\n\nWhat's your current PM trigger — calendar, shot count, or symptoms?\n\n🔗 plasticmolding.com — PMT supports injection molders with tooling maintenance strategy and process support.`,
  ],
  'production-bottlenecks': [
    `The average injection molding plant loses 23% of production capacity to bottlenecks most teams can't name.\n\nIt's almost never the press itself. It's usually:\n• Changeover time (avg. 4–6 hours vs. 90-min benchmark)\n• Material staging delays\n• Downstream QC and secondary ops backup\n\nWhere does your capacity leak? Comment below.\n\n🔗 plasticmolding.com`,
    `A 30-minute reduction in daily changeover time across 5 presses = $220,000/year in reclaimed capacity.\n\nNo capital investment. No new equipment. Just process discipline and documented setup procedures.\n\nHow long does your average changeover take? What's your biggest time sink?\n\n🔗 plasticmolding.com`,
    `You could be running 10% more parts per shift without adding a single press.\n\nThe capacity is already there — it's locked in changeover waste, idle time, and scheduling inefficiency.\n\nOEE tracking makes hidden capacity visible. It's the first step before any equipment investment decision.\n\nWhat's your current OEE? Comment below.\n\n🔗 plasticmolding.com`,
  ],
  'scrap-rework-cost': [
    `Your scrap bin is a profit statement. What's it saying about your process?\n\nFor a mid-size injection molder at $5M revenue, a 5% scrap rate equals $250,000 walking out the door in rejected material every year.\n\nThe first step to driving that number down: tracking root cause, not just defect type.\n\nHow do you currently categorize and track scrap? Drop your approach below.\n\n🔗 plasticmolding.com`,
    `First-pass yield is the most honest metric in injection molding.\n\nIt tells you exactly how often you make a good part the first time — by press, by tool, by operator.\n\nIf you're not tracking it at that level, you don't know where your scrap is actually coming from.\n\nWhat's your current first-pass yield? What drives the most waste at your plant?\n\n🔗 plasticmolding.com`,
    `Three parts. All defective. Three different root causes. Most plants log all three the same way.\n\nDefect coding that captures type but not cause can't drive improvement. You end up with data that tells you what failed — not why.\n\nCause-based scrap tracking + pareto analysis can cut scrap 20–40% in 90 days.\n\nHow are you currently coding scrap at your facility?\n\n🔗 plasticmolding.com`,
  ],
  'mold-downtime': [
    `Unplanned mold downtime costs injection molders an average of $175,000/year in reactive maintenance environments.\n\nThe difference between that number and $60,000 is a shot-count-based PM program and a list of 5 leading indicators to track.\n\nFlash on parting lines. Rising cycle time. Ejector pin drag. These are your early warning system.\n\nHow often does unplanned downtime hit your shop? Share below.\n\n🔗 plasticmolding.com`,
    `Planned downtime costs time. Unplanned downtime costs time + parts + emergency labor + customer delays.\n\nThe math on preventive maintenance always wins. The discipline is the hard part.\n\nWhat's your current approach to mold maintenance scheduling?\n\n🔗 plasticmolding.com`,
    `The 3 most common causes of unplanned mold downtime:\n\n1. Mechanical failure (parting line wear, ejection system)\n2. Cooling system fouling and flow restriction\n3. Maintenance intervals based on calendar — not shot counts\n\nAll three are trackable. All three are preventable.\n\nWhich one hits your plant most often? Comment below.\n\n🔗 plasticmolding.com`,
  ],
  'poor-part-consistency': [
    `Shot 1 passed inspection. Shot 4,000 didn't. Same tool. Same machine. What changed?\n\nMold temperature variation is the #1 driver of dimensional drift in long production runs. A 5°F swing can shift critical dimensions by 0.002".\n\nIn-process dimensional checks at set intervals — not just at startup — catch drift before it reaches customer-critical features.\n\nWhat's your current in-process inspection frequency? Comment below.\n\n🔗 plasticmolding.com`,
    `If your Cpk is below 1.33, your process can't reliably hold the specified tolerance.\n\nNo amount of inspection changes that. The fix is upstream — in process parameters, mold temperature, and pack pressure consistency.\n\nProcess capability studies reveal which parameters to tighten. Control charts keep them there.\n\nWhat's your tightest tolerance in current production? Drop it below.\n\n🔗 plasticmolding.com`,
    `Inconsistent parts aren't a quality problem. They're a process control problem.\n\nWhen dimensional consistency degrades over a production run, teams add inspection, slow the line, or add rework. All three are symptoms — not solutions.\n\nRoot cause is almost always process variation that nobody's tracking.\n\nHow do you currently maintain part consistency across long runs?\n\n🔗 plasticmolding.com`,
  ],
  'scaling-inefficiencies': [
    `You don't need more presses. You need better OEE.\n\nA 10% OEE improvement in a 5-press shop is equivalent to adding a full press worth of output — without the capital outlay.\n\nOEE (availability × performance × quality) makes hidden capacity visible. It's the metric to track before any equipment investment decision.\n\nWhat's your current OEE? What's your biggest availability or performance loss?\n\n🔗 plasticmolding.com`,
    `The fastest path to more capacity is fewer losses in existing capacity.\n\nChangeover efficiency, scrap reduction, and cycle time optimization together can free 15–20% of existing press capacity without capital investment.\n\nWhat does your capacity utilization look like right now? Where's the biggest gap?\n\n🔗 plasticmolding.com`,
    `Adding a press into a 65% OEE environment just scales inefficiency.\n\nThe plants that scale without chaos fix their process first, then add capacity. In that order.\n\nProcess efficiency audit → targeted improvement → then expansion.\n\nHow do you think about capacity investment decisions at your plant?\n\n🔗 plasticmolding.com`,
  ],
  'material-waste': [
    `How much resin did you throw away last month? Do you actually know?\n\nRunner waste. Purge waste. Defect-driven scrap.\n\nThree separate material cost leaks — most plants track none of them at the part level.\n\nMaterial yield per part vs. theoretical yield is the metric that surfaces waste before it compounds.\n\nHow do you currently track material usage at your facility?\n\n🔗 plasticmolding.com`,
    `In cold runner systems, runner weight can represent 15–30% of total shot weight.\n\nThat's 15–30% of your material cost running in a circle.\n\nHot runner ROI calculation: runner weight × shots/year × resin cost/lb ÷ hot runner system cost = payback period.\n\nFor moderate-volume production, payback is typically 12–24 months.\n\nHave you evaluated hot runner conversion on any of your tools? Share below.\n\n🔗 plasticmolding.com`,
    `A poor purge procedure during material changeovers wastes 50–200 lbs of resin per event.\n\nMultiply that by 100 changeovers/year and you have a six-figure material cost that's entirely avoidable.\n\nStructured purge procedures + weight tracking per changeover = 40–70% reduction in purge waste.\n\nHow do you currently manage material changeovers?\n\n🔗 plasticmolding.com`,
  ],
  'process-cost-leakage': [
    `You quoted $1.85/part. You're running at $2.30/part. Where did $0.45 go?\n\nProcess cost leakage in injection molding is rarely one big problem. It's 8–12 small ones:\n• Cycle time drift\n• Scrap rate above quote assumption\n• Overtime from quality holds\n• Rework labor\n• Changeover overruns\n• Material over-usage\n\nPer-part cost tracking reveals which operations are running above standard.\n\nWhat's your biggest hidden cost right now? Comment below.\n\n🔗 plasticmolding.com`,
    `The most expensive thing in your plant might be the jobs you're quoting wrong.\n\nQuoting based on assumed cycle time and estimated scrap without historical data means every job is a guess.\n\nActual vs. quoted variance tracking shows exactly where margin is going — and how to quote more accurately next time.\n\nHow do you currently validate that your quoted cost reflects actual run performance?\n\n🔗 plasticmolding.com`,
    `Process cost leakage doesn't announce itself. It accumulates silently across hundreds of runs.\n\nCycle time drift: 2 seconds over standard. Scrap rate: 1% above quote. Changeover: 45 minutes over.\n\nEach one is below the threshold for a formal corrective action. Together, they erase margin on every job.\n\nHow do you track actual vs. standard performance at your plant?\n\n🔗 plasticmolding.com`,
  ],
  'tooling-lifecycle-cost': [
    `You spent $80,000 on a mold. How much will you spend before it's retired?\n\nTotal tooling lifecycle cost for a production mold typically runs 2–4× the original build cost over its life.\n\nBuild. Preventive maintenance. Repairs. Modifications. Lost production during downtime.\n\nTracking lifecycle cost from day one — not during the third emergency repair — changes the economics.\n\nHow do you currently account for total tooling cost?\n\n🔗 plasticmolding.com`,
    `Reactive tooling management costs 3× more than preventive. Here's the math:\n\n• Emergency repair: 2–3× part cost vs. planned maintenance cost\n• Production disruption: 4–6 days vs. scheduled hours\n• Customer impact: unpredictable vs. managed\n\nPlants with PM programs spend 35% less on tooling per year.\n\nWhat's your current tooling maintenance approach?\n\n🔗 plasticmolding.com`,
    `Your cheapest mold build might be your most expensive mold.\n\nA $40,000 tool with poor steel selection and inadequate cooling will cost more per part over 500,000 shots than a $65,000 tool built correctly.\n\nTotal cost of ownership modeling at the quote stage — not after the first repair — is the right frame for tooling investment decisions.\n\nHow do you evaluate tooling build cost vs. lifecycle cost when making sourcing decisions?\n\n🔗 plasticmolding.com`,
  ],
}

const EDUCATIONAL_POSTS: Record<string, string> = {
  'injection-molding-defects': `HOW TO REDUCE INJECTION MOLDING DEFECT RATES BELOW 2%\n\nMost injection molding defects are predictable. Here's what drives them — and what to track:\n\n📌 DEFECT #1: Sink Marks\nCause: Insufficient pack pressure or wall thickness variation\nFix: Audit wall section uniformity; increase pack pressure and hold time\n\n📌 DEFECT #2: Flash\nCause: Clamp pressure drift or parting line wear\nFix: Verify clamp tonnage at press start; inspect parting line surface condition\n\n📌 DEFECT #3: Short Shots\nCause: Melt temperature too low, inadequate injection speed, or blocked gate\nFix: Verify barrel temperature profile; increase injection speed in stages\n\n📌 DEFECT #4: Warpage\nCause: Uneven cooling, wall thickness variation, or improper ejection\nFix: Verify cooling line flow and temperature; check ejection timing\n\n📌 DEFECT #5: Burn Marks\nCause: Inadequate venting or excessive injection speed creating heat\nFix: Clean and verify venting; reduce injection speed; check material for moisture\n\nThe common thread: all five have traceable process causes. None are random.\n\nTop-quartile injection molders hold defect rates under 1% by tracking process parameters every cycle — not inspecting at end of run.\n\nWhat's your current defect rate? What drives the most rejects at your plant?\n\n🔗 plasticmolding.com | PMT — Injection Molding Process Support`,
  'tooling-failures': `5 WARNING SIGNS YOUR MOLD WILL FAIL THIS MONTH\n\nTooling failures rarely happen without warning. Here's what to track:\n\n⚠️ WARNING SIGN #1: Flash on Parting Lines\nWhat it means: Parting line surfaces are wearing; clamp pressure may be dropping\nWhat to do: Inspect parting line condition; check clamp tonnage records\n\n⚠️ WARNING SIGN #2: Cycle Time Creeping Up\nWhat it means: Cooling efficiency declining or ejection system drag increasing\nWhat to do: Check cooling line flow rates; inspect ejector pin condition\n\n⚠️ WARNING SIGN #3: Ejector Pin Marks or Drag\nWhat it means: Pin wear or misalignment; lubrication intervals missed\nWhat to do: Pull mold; inspect and replace worn pins; re-lubricate\n\n⚠️ WARNING SIGN #4: Surface Quality Degrading in Cavity\nWhat it means: Steel surface wear or contamination in cavity\nWhat to do: Inspect cavity surface; polishing or texturing may be needed\n\n⚠️ WARNING SIGN #5: Part Warpage Increasing Without Process Changes\nWhat it means: Cooling channel fouling reducing heat extraction uniformity\nWhat to do: Flush cooling channels; inspect for scale buildup\n\nAll five are detectable 2–4 weeks before failure. Tracking them is the difference between planned maintenance and a $15,000 emergency.\n\nWhat's your current PM trigger for mold maintenance?\n\n🔗 plasticmolding.com | PMT — Tooling Lifecycle Support`,
  'production-bottlenecks': `WHERE YOUR INJECTION MOLDING PLANT IS LOSING CAPACITY (AND HOW TO FIND IT)\n\nThe bottleneck is almost never the press. Here's where capacity actually disappears:\n\n📍 BOTTLENECK #1: Changeover Time\nIndustry average: 4–6 hours. Best-in-class: under 90 minutes.\nFix: Standardized setup procedures + staging protocols. No capital required.\n\n📍 BOTTLENECK #2: Material Prep and Staging\nMissed drying times, wrong lot staged at press, resin shortages — all add 30–90 minutes per run.\nFix: Pre-run staging checklists + scheduled drying start times.\n\n📍 BOTTLENECK #3: Downstream QC Backup\nParts waiting for first-article approval or inspection staging delay the next run.\nFix: First-article prep during changeover, not after production starts.\n\n📍 BOTTLENECK #4: Job Sequencing\nRunning the wrong job on the wrong press adds changeover and setup time.\nFix: Press-to-job optimization based on tonnage, material, and mold size.\n\n📍 BOTTLENECK #5: Unplanned Downtime\nEvery unplanned mold or machine event disrupts the schedule downstream.\nFix: PM programs that reduce unplanned events by 40–60%.\n\nThe tool that makes all five visible: OEE tracking at the press level.\n\nWhat's your biggest capacity leak right now?\n\n🔗 plasticmolding.com | PMT — Production Efficiency Support`,
  'scrap-rework-cost': `THE ROOT CAUSE SCRAP ANALYSIS MOST INJECTION MOLDERS SKIP\n\nTracking defect type isn't enough. Here's what to track instead:\n\n🔍 SCRAP CATEGORY #1: Process Parameter Drift\nWhat causes it: Shift-to-shift variation, operator compensation, no parameter logging\nHow to track: Log actual parameters every cycle; flag drift >2% from standard\n\n🔍 SCRAP CATEGORY #2: Tool Wear\nWhat causes it: Parting line degradation, cavity surface wear, ejection issues\nHow to track: Shot count log; correlate scrap spikes to maintenance history\n\n🔍 SCRAP CATEGORY #3: Material Issues\nWhat causes it: Wrong lot, improper drying, contamination, regrind ratio errors\nHow to track: Material traceability by lot number; moisture verification before processing\n\n🔍 SCRAP CATEGORY #4: Measurement Error\nWhat causes it: Gauge variation, operator gauging inconsistency, temperature effects\nHow to track: Gauge R&R studies; controlled inspection conditions\n\n🔍 SCRAP CATEGORY #5: Design-Related\nWhat causes it: Wall thickness variation, gate location, draft angle deficiency\nHow to track: Part design review; DFM audit at tool build stage\n\nMost injection molders know their scrap rate. The top quartile knows which of these five categories drives it — by press, by tool, and by shift.\n\nHow do you currently categorize scrap at your facility?\n\n🔗 plasticmolding.com | PMT — Quality and Process Support`,
  'mold-downtime': `THE ECONOMICS OF PLANNED VS. UNPLANNED MOLD DOWNTIME\n\nThis is a comparison most injection molders haven't run:\n\n📊 PLANNED MAINTENANCE EVENT\nPrep time: 2–4 hours (scheduled during off-peak)\nParts cost: Standard maintenance components at standard pricing\nLabor cost: Standard shop rate\nProduction impact: Scheduled around production; minimal disruption\nAverage total cost: $2,500–$6,000\n\n📊 UNPLANNED FAILURE EVENT\nResponse time: 4–8 hours minimum (emergency mobilization)\nParts cost: Emergency sourcing, 20–50% premium\nLabor cost: Overtime or emergency service rate\nProduction impact: Unscheduled downtime; downstream delays; customer impact\nAverage total cost: $8,000–$25,000+\n\nThe math: Plants with PM programs spend 35% less on tooling per year than reactive environments.\n\nLeading indicators to track (gives you 2–4 weeks of warning):\n• Flash appearing on parting lines\n• Cycle time trending up\n• Ejector pin resistance\n• Cooling temperature differential increasing\n• Cavity surface degradation\n\nWhat's your current approach to mold maintenance scheduling?\n\n🔗 plasticmolding.com | PMT — Tooling Lifecycle Support`,
  'poor-part-consistency': `WHY PARTS DRIFT OUT OF TOLERANCE OVER LONG PRODUCTION RUNS\n\nConsistency between shot 1 and shot 10,000 requires more than a good startup process. Here's what changes:\n\n🔬 DRIVER #1: Mold Temperature Variation\nA 5°F swing in mold surface temperature can shift critical dimensions by 0.002".\nControl: Mold temperature controllers on each circuit; verify temps at regular intervals.\n\n🔬 DRIVER #2: Pack Pressure Drift\nPack pressure consistency controls part weight and dimensional stability.\nControl: Closed-loop pack pressure control; weight verification at startup and mid-run.\n\n🔬 DRIVER #3: Material Variation\nMelt flow index variation between lots affects shrink rate and fill behavior.\nControl: Material lot qualification; incoming MFI verification.\n\n🔬 DRIVER #4: No In-Process Dimensional Checks\nStartup approval doesn't catch drift that builds over 4,000 shots.\nControl: Dimensional checks at 500–1,000 piece intervals on critical features.\n\n🔬 DRIVER #5: Ambient Temperature Effects\nShop temperature swings affect mold heat extraction and part shrinkage.\nControl: Climate-controlled press area or temperature-compensated process parameters.\n\nCpk on your tightest tolerance feature tells you whether your process can actually hold it reliably — or whether you're relying on inspection to catch drift.\n\nWhat tolerance band are you holding on your most critical part features?\n\n🔗 plasticmolding.com | PMT — Process Consistency Support`,
  'scaling-inefficiencies': `HOW TO CALCULATE YOUR INJECTION MOLDING OEE (AND WHAT TO DO WITH IT)\n\nOEE = Availability × Performance × Quality\n\nHere's how to calculate each component:\n\n📐 AVAILABILITY\n= (Planned production time – Downtime) ÷ Planned production time\nIncludes: Changeover time, unplanned downtime, scheduled maintenance, material shortages\nTarget: >90%\n\n📐 PERFORMANCE\n= (Actual cycle time ÷ Standard cycle time) × 100\nIncludes: Cycle time running above standard, reduced speed events, minor stops\nTarget: >95%\n\n📐 QUALITY\n= Good parts ÷ Total parts produced\nIncludes: Defects, rework, startup scrap\nTarget: >99%\n\nWorld-class OEE: 85%+\nIndustry average: 65%\n\nWhat a 10% OEE improvement means at $85/hour machine rate:\n• 1 press, 8 hours/day, 250 days/year: +$170,000 in recovered press revenue annually\n• 5 presses: +$850,000 annually — equivalent to adding a full press without capital outlay\n\nWhat's your current OEE? What's your biggest loss category?\n\n🔗 plasticmolding.com | PMT — Production Efficiency Support`,
  'material-waste': `WHERE RESIN WASTE HIDES IN INJECTION MOLDING (AND HOW TO MEASURE IT)\n\nMaterial yield is one of the most undertargeted metrics in injection molding. Here's where waste occurs:\n\n💧 WASTE SOURCE #1: Runner and Sprue Waste\nIn cold runner systems, runner weight can be 15–30% of total shot weight.\nMeasure: (Runner weight ÷ Total shot weight) × 100\nFix: Hot runner conversion; regrind program; runner weight reduction in tool design\n\n💧 WASTE SOURCE #2: Purge Waste During Changeovers\nA poor purge procedure wastes 50–200 lbs per changeover.\nMeasure: Weigh purge waste per changeover; track by material pair\nFix: Structured purge procedures; mechanical purging compounds; temperature sequencing\n\n💧 WASTE SOURCE #3: Defect-Driven Scrap (Virgin Material)\nScrap parts made from virgin resin that can't be reground cost full material price per reject.\nMeasure: Scrap weight × resin cost/lb\nFix: Process control improvements; regrind qualification where applicable\n\n💧 WASTE SOURCE #4: Over-Packed Parts\nExcessive pack pressure adds part weight beyond nominal — wasting material every cycle.\nMeasure: Actual part weight vs. nominal part weight × shots per year\nFix: Pack pressure optimization; weight verification at startup\n\nThe target metric: Material yield = Good part weight ÷ Total resin consumed\n\nTop quartile injection molders track this at the part level. Most track it at the job level at best.\n\nHow do you currently track material yield?\n\n🔗 plasticmolding.com | PMT — Material Efficiency Support`,
  'process-cost-leakage': `8 PLACES YOUR INJECTION MOLDING PROCESS IS LEAKING MARGIN\n\nNone of these show up as a single line item. All of them are fixable.\n\n💸 LEAK #1: Cycle Time Running Above Standard\nIf actual cycle time is 5% above quote across 500,000 shots/year, that's $42,500 in unrecovered machine time.\n\n💸 LEAK #2: Scrap Rate Above Quote Assumption\nIf quoted scrap rate was 2% and actual is 4%, every point of excess scrap costs you full part margin.\n\n💸 LEAK #3: Overtime from Quality Holds\nQuality holds trigger overtime to recover production. The root cause (process variation) never gets addressed.\n\n💸 LEAK #4: Rework Labor\nRework costs are rarely tracked against the job they came from. They disappear into overhead.\n\n💸 LEAK #5: Changeover Time Over Standard\nIf changeover runs 90 minutes over standard, and you do 200 changeovers/year, that's 300 hours of lost machine time.\n\n💸 LEAK #6: Material Over-Usage\nOver-packed parts, excessive runner weight, and purge waste add material cost above the quote assumption.\n\n💸 LEAK #7: Secondary Ops Scope Creep\nSecondary operations that run longer than quoted absorb labor margin silently.\n\n💸 LEAK #8: Non-Conformance Handling\nCustomer returns, sorting labor, and replacement production aren't tracked against the job that caused them.\n\nThe fix: Per-part cost tracking at the press level — not job-level P&L.\n\nWhat's your biggest hidden cost right now?\n\n🔗 plasticmolding.com | PMT — Process Cost Support`,
  'tooling-lifecycle-cost': `THE FULL COST OF AN INJECTION MOLD (MOST PLANTS ONLY TRACK THE FIRST NUMBER)\n\nBuild cost is just the beginning. Here's what total tooling lifecycle cost actually includes:\n\n🔩 COMPONENT #1: Initial Build Cost\nThe number everyone tracks. Typically $30,000–$150,000+ depending on complexity and cavitation.\n\n🔩 COMPONENT #2: Preventive Maintenance\nShot-count-based PM: $1,500–$4,000 per event × frequency over tool life.\nFor a 1M-shot tool with PM every 50,000 shots: 20 events × $2,500 average = $50,000.\n\n🔩 COMPONENT #3: Unplanned Repairs\nEmergency repairs: $8,000–$25,000 per event. Reactive environments average 2–4/year.\nOver 5 years: $80,000–$250,000 in unplanned repair costs alone.\n\n🔩 COMPONENT #4: Engineering Modifications\nDesign changes, runner modifications, gate relocation: $3,000–$15,000 per modification.\n\n🔩 COMPONENT #5: Lost Production During Downtime\nAt $85/hour machine rate, 40 hours of annual unplanned downtime = $3,400/year. Over 5 years: $17,000.\n\n🔩 COMPONENT #6: End-of-Life Replacement\nReplacement cost equals or exceeds original build cost — often higher due to engineering changes.\n\nTotal lifecycle cost: Often 2–4× the original build cost.\n\nThe plants that know this number by tool — from day one — make better maintenance, modification, and replacement decisions.\n\nHow do you currently track total tooling cost?\n\n🔗 plasticmolding.com | PMT — Tooling Lifecycle Support`,
}

const DISCUSSION_PROMPTS: Record<string, string[]> = {
  'injection-molding-defects': [
    `Question for injection molding operators and managers:\n\nWhat's your single biggest driver of defect-related scrap right now?\n\nA) Process parameter drift between shifts\nB) Tool wear that we haven't stayed ahead of\nC) Material handling or drying issues\nD) Something else (comment below)\n\nAsking because we're seeing a consistent pattern in how defect causes are distributed — curious if it matches what you're experiencing.\n\n🔗 plasticmolding.com`,
    `For those of you running tight-tolerance injection molded parts:\n\nHow do you currently catch process parameter drift before it becomes a defect?\n\n- Ongoing SPC/control charts?\n- Operator-logged parameter checks?\n- End-of-shift first-article inspection?\n- Real-time machine monitoring?\n\nNo right or wrong answer — genuinely curious what's working (and what isn't) in production environments.\n\n🔗 plasticmolding.com`,
  ],
  'tooling-failures': [
    `Question for injection molding plant managers and tooling engineers:\n\nWhat triggers your mold maintenance schedule?\n\nA) Calendar intervals (weekly, monthly)\nB) Shot count thresholds\nC) When something fails or quality drops\nD) No formal trigger — maintenance when time allows\n\nResearch consistently shows shot-count-based triggers outperform all others for preventing unplanned failures. What's your experience?\n\n🔗 plasticmolding.com`,
    `For those managing tooling in injection molding facilities:\n\nWhat's your typical budget for unplanned mold repairs per year?\n\nAsking because most of our conversations with plant managers reveal this number is much higher than they expect when they actually add it up.\n\nThe average in reactive maintenance environments: $60,000–$175,000/year per facility.\n\nDoes that match your experience?\n\n🔗 plasticmolding.com`,
  ],
  'production-bottlenecks': [
    `For injection molding production managers:\n\nWhere does the most time get lost in your operation?\n\nA) Changeover and setup\nB) Material prep and staging\nC) Unplanned downtime\nD) Downstream inspection and secondary ops\nE) All of the above\n\nMost bottleneck analyses show it's rarely the molding cycle itself — it's what happens around it.\n\n🔗 plasticmolding.com`,
    `What's your average changeover time in injection molding?\n\nFor reference:\n• Industry average: 4–6 hours\n• Best-in-class: under 90 minutes\n\nThe gap between those two numbers represents $220,000+ in recoverable capacity on a 5-press operation.\n\nDrop your number in the comments — curious how it compares.\n\n🔗 plasticmolding.com`,
  ],
  'scrap-rework-cost': [
    `For quality and operations managers in injection molding:\n\nWhat percentage of your scrap can you trace to a specific root cause?\n\nA) Over 80% — we have solid root cause tracking\nB) 50–80% — some categories are well-tracked\nC) Under 50% — most scrap is categorized by defect type, not cause\nD) We don't formally track root cause\n\nThe reason this matters: plants in category A or B drive scrap down 3–5× faster than those in C or D.\n\n🔗 plasticmolding.com`,
    `What's the most expensive type of scrap in your injection molding operation?\n\nA) Defects found during in-process inspection\nB) Defects found during final inspection\nC) Customer returns\nD) Rework that fails a second time\n\nThe answer shifts the corrective action significantly — and most plants have a different answer than they expect when they look at the data.\n\n🔗 plasticmolding.com`,
  ],
  'mold-downtime': [
    `For injection molding plant managers and tooling engineers:\n\nHow often does unplanned mold downtime hit your facility?\n\nA) Rarely — under 1 event/month\nB) Monthly — 1–2 events\nC) Weekly — more than that\nD) Multiple times per week\n\nPlants at B or above are typically in reactive maintenance mode. The jump from reactive to preventive takes 90 days and cuts unplanned events 60%.\n\n🔗 plasticmolding.com`,
    `What's your most common cause of unplanned mold downtime?\n\nA) Mechanical failure (broken components, parting line damage)\nB) Cooling system issues (fouling, leaks, flow restriction)\nC) Ejection system failure (pins, plates, lifters)\nD) Gate or runner system problems\nE) Something else — comment below\n\nAsking because the fix is different depending on which category dominates.\n\n🔗 plasticmolding.com`,
  ],
  'poor-part-consistency': [
    `For quality managers and process engineers in injection molding:\n\nWhat's your most consistent driver of part-to-part dimensional variation?\n\nA) Mold temperature variation across the run\nB) Pack pressure inconsistency\nC) Material lot-to-lot variation\nD) No formal root cause — we catch it in inspection\n\nThe answer determines whether the fix is a process parameter change, a material protocol change, or a tooling intervention.\n\n🔗 plasticmolding.com`,
    `What Cpk do you hold on your tightest-tolerance feature in current production?\n\nFor reference:\n• Cpk ≥ 1.67: Capable process with margin\n• Cpk 1.33–1.67: Capable — borderline\n• Cpk < 1.33: Process cannot reliably hold tolerance\n\nIf you're below 1.33, no amount of inspection changes that. The fix is upstream.\n\nDrop your number in the comments.\n\n🔗 plasticmolding.com`,
  ],
  'scaling-inefficiencies': [
    `For injection molding plant managers considering capacity expansion:\n\nWhat's your current OEE?\n\nA) Over 85% — ready to scale\nB) 70–85% — room to improve\nC) 55–70% — significant losses to address\nD) Under 55% — major opportunity\nE) We don't formally track OEE\n\nThe most common mistake in capacity planning: adding presses before fixing OEE. A 10% OEE improvement equals adding a press — without the capital.\n\n🔗 plasticmolding.com`,
    `What's the biggest constraint on your ability to take on more work right now?\n\nA) Press capacity (not enough machines)\nB) Tooling capacity (can't build or source tools fast enough)\nC) Quality system bandwidth (can't scale quality processes)\nD) Labor (can't staff additional shifts)\nE) All of the above\n\nAsking because the right growth strategy is different depending on which constraint is actually binding.\n\n🔗 plasticmolding.com`,
  ],
  'material-waste': [
    `For injection molding operations and materials managers:\n\nHow do you currently track material yield?\n\nA) By part (actual weight vs. theoretical weight)\nB) By job (total resin consumed vs. total good parts)\nC) By resin lot (inventory-level tracking)\nD) We don't formally track it\n\nPart-level tracking reveals waste that job-level tracking hides. The plants that make that shift typically find 15–25% improvement opportunity they didn't know existed.\n\n🔗 plasticmolding.com`,
    `Have you evaluated hot runner conversion on any of your high-volume production tools?\n\nFor context:\n• Cold runner runner waste: 15–30% of shot weight\n• Hot runner investment: $15,000–$50,000 per tool\n• Payback at moderate volume: 12–24 months\n\nCurious whether the economics work at the volumes you're running.\n\n🔗 plasticmolding.com`,
  ],
  'process-cost-leakage': [
    `For injection molding operations managers and estimators:\n\nHow accurately does your quoted cost match your actual cost per part?\n\nA) Within 5% — very accurate\nB) 5–15% gap — room to improve\nC) 15–25% gap — systematic issues\nD) Over 25% — we don't have reliable actuals\nE) We don't track this\n\nThe gap between quoted and actual cost is where margin disappears — quietly, across hundreds of jobs.\n\n🔗 plasticmolding.com`,
    `What's the single biggest process cost you're not currently tracking?\n\nA) Cycle time vs. quoted standard\nB) Actual vs. quoted changeover time\nC) Root cause of scrap (not just rate)\nD) Rework labor cost by job\nE) Material yield per part\n\nAll five are fixable. None of them are being tracked at most injection molding facilities.\n\n🔗 plasticmolding.com`,
  ],
  'tooling-lifecycle-cost': [
    `For injection molding plant and tooling managers:\n\nHow do you track total tooling cost over a mold's life?\n\nA) Full lifecycle tracking (build + maintenance + repairs + modifications)\nB) Maintenance and repair costs only (after build)\nC) Build cost only\nD) We don't formally track tooling cost over time\n\nMost plants discover their actual lifetime tooling cost is 2–4× what they expected — usually during the third emergency repair.\n\n🔗 plasticmolding.com`,
    `What do you consider when deciding whether to repair or replace a mold?\n\nA) Repair cost vs. build cost\nB) Remaining estimated tool life (shot count)\nC) Part complexity and replacement lead time\nD) Customer volume commitment going forward\nE) All of the above — it's usually a combination\n\nThe right answer is E — but most repair vs. replace decisions are made on repair cost alone, which is usually the wrong frame.\n\n🔗 plasticmolding.com`,
  ],
}

const RETARGETING_POSTS: Record<string, string[]> = {
  'injection-molding-defects': [
    `If you've looked at our defect rate resources, here's the follow-up:\n\nThe single most common reason injection molders can't get below 3% defects isn't their equipment. It's the absence of real-time process monitoring.\n\nEnd-of-run inspection tells you what happened. Process monitoring tells you when it started — and lets you catch it before the bin fills.\n\nWe've helped injection molders reduce defect rates by 40–60% using this approach. The timeline is typically 60–90 days.\n\nIf you want to see how we do it: plasticmolding.com`,
    `You've seen the defect rate data. Here's what it means in practice:\n\nA 1% improvement in defect rate on 500,000 parts/year at $2.00/part average:\n→ 5,000 fewer rejected parts\n→ $10,000 in recovered material cost\n→ Plus rework labor, inspection time, and customer return risk\n\nNot all of that is visible in your scrap report. But it's all recoverable.\n\nPMT works with injection molders on process control that drives these numbers. If you're ready to look at yours: plasticmolding.com`,
  ],
  'tooling-failures': [
    `If you've been thinking about tooling maintenance, here's what most plants find when they run the numbers:\n\nThe difference between reactive and preventive maintenance is about 35% in annual tooling cost.\n\nFor a plant with $200,000/year in tooling spend, that's $70,000 in recoverable cost — every year.\n\nPMT helps injection molders build PM programs tied to shot counts, not guesswork. If you want to see the economics for your operation: plasticmolding.com`,
  ],
  'production-bottlenecks': [
    `If you've been thinking about changeover and capacity, here's the part most plants miss:\n\nThe fastest path to more throughput isn't adding a press. It's cutting changeover time in half.\n\nFor a 5-press operation at $85/hour machine rate, a 3-hour reduction in daily changeover time = $383,000/year in recovered press revenue.\n\nPMT works with injection molders to map and reduce production bottlenecks without capital investment. If you want to see what that looks like for your operation: plasticmolding.com`,
  ],
  'scrap-rework-cost': [
    `If you've been tracking scrap but not seeing improvement, here's the most common reason:\n\nDefect-type tracking tells you what failed. Root cause tracking tells you why — and what to fix.\n\nWithout cause-level data, every corrective action is a guess.\n\nPMT works with injection molders to build root cause scrap analysis systems. Most of our customers see 20–40% scrap reduction in the first 90 days.\n\nIf that's a problem you're working on: plasticmolding.com`,
  ],
  'mold-downtime': [
    `If unplanned mold downtime is something you're dealing with, here's the most common pattern we see:\n\nPlants in reactive maintenance mode average 2–4 unplanned events per month. Each one costs $8,000–$25,000 in parts, labor, and lost production.\n\nThe transition to preventive maintenance takes 90 days. The result is typically a 60% reduction in unplanned events — and a 35% reduction in annual tooling spend.\n\nPMT helps injection molders make that transition. If you want to understand the process: plasticmolding.com`,
  ],
  'poor-part-consistency': [
    `If part-to-part consistency is a problem you're working on, here's what we've found:\n\nDimensional drift in long production runs is almost always a process parameter problem — not a tooling problem. Most teams replace tooling when the fix is tighter parameter control.\n\nMold temperature monitoring + in-process dimensional checks at 500-piece intervals catch 80% of consistency issues before they reach critical dimensions.\n\nPMT works with injection molders on process consistency programs. If that's relevant to your operation: plasticmolding.com`,
  ],
  'scaling-inefficiencies': [
    `If you're thinking about adding capacity, here's the question to answer first:\n\nWhat's your current OEE?\n\nIf it's below 75%, the fastest path to more output isn't a new press — it's recovering what you're already losing.\n\nA 10% OEE improvement on a 5-press operation at $85/hour machine rate = $850,000 in recovered annual press revenue.\n\nPMT works with injection molders on OEE improvement before capacity expansion. If you want to see what the opportunity looks like for your operation: plasticmolding.com`,
  ],
  'material-waste': [
    `If material cost is a concern, here's where the recovery usually is:\n\nRunner waste (15–30% of shot weight in cold runner systems) + purge waste (50–200 lbs/changeover) = a material cost problem hiding in plain sight.\n\nHot runner conversion on your highest-volume tools, combined with structured purge procedures, typically reduces material cost 12–20%.\n\nPMT helps injection molders identify and recover material waste. If you want to run the numbers for your operation: plasticmolding.com`,
  ],
  'process-cost-leakage': [
    `If your actual cost per part is consistently above your quoted cost, here's the most common root cause:\n\nYou're quoting with estimated cycle time and assumed scrap rates — not historical actuals.\n\nThe gap compounds across every job. It shows up as margin erosion that's hard to attribute to a single cause.\n\nPMT works with injection molders on per-part cost tracking systems that close the gap between quoted and actual. If this sounds familiar: plasticmolding.com`,
  ],
  'tooling-lifecycle-cost': [
    `If tooling cost is something you're managing closely, here's the perspective that changes most decisions:\n\nBuild cost is typically 40–50% of total lifecycle cost. The rest is maintenance, repairs, modifications, and lost production during downtime.\n\nPlants that track lifecycle cost from day one make better decisions at every stage — maintenance intervals, repair vs. replace, and new tool build specs.\n\nPMT helps injection molders build tooling lifecycle cost models. If you want to see what your current tools actually cost: plasticmolding.com`,
  ],
}

export function generateFacebook(inputs: FacebookInputs, seed: number = 0): FacebookOutput {
  const problem = inputs.problem
  const data = PROBLEM_DATA[problem]
  const idx = seed % 3

  const shortPost = SHORT_POSTS[problem]?.[idx] || SHORT_POSTS['injection-molding-defects'][0]
  const educationalPost = EDUCATIONAL_POSTS[problem] || EDUCATIONAL_POSTS['injection-molding-defects']
  const discussionPrompts = DISCUSSION_PROMPTS[problem] || DISCUSSION_PROMPTS['injection-molding-defects']
  const retargetingPosts = RETARGETING_POSTS[problem] || RETARGETING_POSTS['injection-molding-defects']

  const discussionPrompt = discussionPrompts[idx % discussionPrompts.length]
  const retargetingPost = retargetingPosts[idx % retargetingPosts.length]

  const businessOwnerPost = `${COMPANY.fullName} works with injection molders on the problems that quietly erode margin:\n\nDefect rates that won't drop. Tooling failures that weren't planned. Cycle times that run above quote. Scrap that doesn't trace to a root cause.\n\nNone of these are random. All of them are traceable. Most of them are fixable in 60–90 days with the right process focus.\n\nIf you're an injection molder dealing with any of these, we're worth a conversation.\n\n🔗 ${COMPANY.website}`

  const hasDataPoints = !!(data.stat1 || data.stat2)
  const hasCTA = true
  const hasConsequence = !!data.consequence
  const wordCount = shortPost.split(' ').length

  const qualityScore = scoreContent(inputs, hasDataPoints, hasCTA, hasConsequence, wordCount)

  const repurposingSuggestions = [
    'Pull the educational post bullet points as a LinkedIn carousel slide structure',
    'Use the discussion prompt as a Twitter/X engagement post with the same options',
    'Convert the short post hook into a YouTube Shorts script opener (3-second hook format)',
    'Use the retargeting post body as a LinkedIn InMail follow-up for warm prospects',
    'Turn the educational post into an Instagram carousel (one section per slide)',
  ]

  return {
    platform: 'facebook',
    contentFormat: inputs.contentFormat,
    shortPost,
    educationalPost,
    discussionPrompt,
    businessOwnerPost,
    retargetingPost,
    repurposingSuggestions,
    qualityScore,
    companyName: COMPANY.name,
  }
}
