import type { LinkedInInputs, LinkedInOutput, PostIdea, CalendarEntry } from '../types'
import { PROBLEM_DATA, PROBLEM_LABELS } from '../lib/companyProfile'
import { scoreContent } from '../lib/scoring'

const HOOKS: Record<string, string[]> = {
  'injection-molding-defects': [
    "Most injection molding defects are not a machine problem. They are a process parameter problem — and the parameters were never documented.",
    "Sink marks. Flash. Short shots. Warping. These defects have different names but the same root cause: an unstable process running without controls.",
    "The defect rate in your molding operation is not bad luck. It is the output of a process that was never stabilized.",
  ],
  'tooling-failures': [
    "The mold that cost $40,000 less to build will cost $120,000 more to operate. Most procurement teams make this trade without knowing they made it.",
    "Premature tooling failure is rarely a manufacturing surprise. It is the predictable output of tooling decisions made without lifecycle cost analysis.",
    "Your mold is failing. The question is not whether you saw it coming — it is whether the tooling spec gave you a chance to.",
  ],
  'production-bottlenecks': [
    "Your press is running. Parts are coming out. You are still losing 30% of your available throughput and it is not showing up on any daily report.",
    "Cycle time inefficiency in injection molding is not a machine performance problem. It is a process design problem — and it costs the equivalent of one shift per week.",
    "The production bottleneck in your molding operation is not where your team is looking. It is in the cycle, the cooling, and the parameters nobody has audited in two years.",
  ],
  'scrap-rework-cost': [
    "8–18% scrap in injection molding is not a quality problem. It is a process control problem — and it has a dollar value that compounds on every shift.",
    "Your scrap rate is not a defect metric. It is a process stability metric. And right now, it is telling you something your daily report is not.",
    "The difference between a 2% scrap rate and a 15% scrap rate is not better equipment. It is documented, validated, locked process parameters.",
  ],
  'mold-downtime': [
    "Mold maintenance deferred is not cost avoided. It is downtime scheduled — at a time your production team cannot control.",
    "Every flash buildup, clogged vent, and worn ejector pin your team catches at shift change is a production stop that did not happen yet. The ones they miss are a different story.",
    "The most expensive press downtime in injection molding is unplanned. The second most expensive is planned but reactive. Neither has to be the default.",
  ],
  'poor-part-consistency': [
    "Part-to-part variation in injection molding is not a dimensional problem. It is a process stability problem — and it propagates into every assembly that uses the part.",
    "Your first-pass yield failure is not happening at inspection. It is happening at the press, on every shot where pack pressure, cooling time, or melt temperature drifts.",
    "Assembly lines that stop because of inconsistent molded parts are not stopping because of part quality. They are stopping because of process instability that was never addressed upstream.",
  ],
  'scaling-inefficiencies': [
    "The injection molding program that ran fine at 5,000 parts per month is failing at 50,000. The problem was always there. Scale made it visible.",
    "Scaling injection molding without locking process parameters first does not accelerate production. It accelerates defects.",
    "60–70% of molding programs scaled without DFM review encounter design-driven failures. The review is not overhead — it is the step that keeps $150,000 in engineering changes off the budget.",
  ],
  'material-waste': [
    "Your resin spend is not what your process requires. It is what your process requires plus 8–25% that goes to sprues, runners, and purging that nobody tracks by job.",
    "The material cost in your injection molding operation includes waste that was decided at the tooling design stage — long before the first shot was run.",
    "Sprue and runner waste in injection molding is not a material cost. It is a tooling design cost that shows up on the material line of every invoice.",
  ],
  'process-cost-leakage': [
    "Most injection molding operations do not lose money on resin cost. They lose it through cycle drift, yield variation, and untracked scrap — none of which appears as a single line on any report.",
    "Process cost leakage in injection molding is not one large inefficiency. It is dozens of small ones — each invisible on its own, together consuming 8–15% of annual production value.",
    "The press is running. The parts are shipping. 12% of your annual production value just leaked out through processes nobody was monitoring.",
  ],
  'tooling-lifecycle-cost': [
    "The cheapest mold in the quote comparison is almost never the lowest-cost mold over the life of the program. The math on this is consistent enough to be a rule.",
    "Every dollar cut from tooling upfront costs an average of $3–$7 in downstream repair, downtime, and scrap over the life of the production program. Most buyers never see that math.",
    "The total lifecycle cost of an injection mold averages 2–4x the original build cost over five years. The procurement decision that saved 15% at tooling approval often costs 40% more by year three.",
  ],
}

const BODIES: Record<string, string[]> = {
  'injection-molding-defects': [
    `Injection molding defects do not come from nowhere.\n\nSink marks form when packing pressure is insufficient or cooling time is too short. Flash appears when clamp force is inadequate or mold wear has opened parting line gaps. Short shots trace to fill speed, melt temperature, or gate sizing issues.\n\n${PROBLEM_DATA['injection-molding-defects'].stat1}.\n\nThese are not random events. They are process outputs — and every one of them has a root cause that can be identified, documented, and controlled.\n\n${PROBLEM_DATA['injection-molding-defects'].stat2}.\n\nA defect that escapes to assembly is not a quality failure. It is a control system failure — and it costs orders of magnitude more than the part.\n\n${PROBLEM_DATA['injection-molding-defects'].stat3}.\n\nThe operations running 1–4% defect rates are not running better equipment. They are running documented, validated, and locked process parameters. The difference is discipline — not capital.`,
    `Most injection molding operations treat defects as quality problems to be caught.\n\nThey are process problems to be prevented.\n\n${PROBLEM_DATA['injection-molding-defects'].stat3}.\n\nOperations without documented process parameters are running on tribal knowledge — whatever settings the last technician used, whatever adjustments were made during the last run. Shift to shift, the process drifts.\n\n${PROBLEM_DATA['injection-molding-defects'].stat1}.\n\n5–15% of output going to defects is not an acceptable quality range. It is the predictable output of an undocumented process.\n\n${PROBLEM_DATA['injection-molding-defects'].stat2}.\n\nThe defect that escapes has a multiplier effect. By the time a field recall is triggered, the cost is 10–100x what the production run was worth. The inspection system is not the line of defense. The process is.`,
    `Sink marks, flash, short shots, and warping each have a different mechanism.\n\nThey share the same root cause: a process that was never properly characterized, validated, or documented.\n\n${PROBLEM_DATA['injection-molding-defects'].stat1}.\n\nFor operations running without process controls, that 5–15% figure is the cost of operating without a baseline. Every shift is a new experiment.\n\n${PROBLEM_DATA['injection-molding-defects'].stat3}.\n\nThe 3–5x defect rate differential between controlled and uncontrolled operations is not a technology gap. It is a process engineering gap — and it is closable without new equipment.\n\n${PROBLEM_DATA['injection-molding-defects'].stat2}.\n\nThe downstream cost of an escaped defect makes the case for process control economics straightforward. The question is not whether to invest in process stability. It is when.`,
  ],
  'tooling-failures': [
    `Tooling failures in injection molding are predictable when you know what to look for.\n\nCore damage from inadequate draft angles. Gate erosion from abrasive materials at incorrect fill speeds. Parting line wear from insufficient hardness specifications. Each failure mode has a mechanical cause — and most were visible in the original tooling specification.\n\n${PROBLEM_DATA['tooling-failures'].stat1}.\n\nTwo to six weeks of lost throughput per failure event. In a production program running $200,000 per month in volume, a single mold failure is a six-figure production gap before repair costs are counted.\n\n${PROBLEM_DATA['tooling-failures'].stat2}.\n\nMolds built to the lowest upfront cost fail 3–4x sooner. The initial savings evaporate in the first production year — and the failure always happens at the worst possible time.\n\n${PROBLEM_DATA['tooling-failures'].stat3}.\n\nThe repair is not the total cost. The downtime, the emergency sourcing, the expediting, the downstream assembly disruption — these are the real numbers that compound when a mold fails without warning.`,
    `The tooling decision is made once.\n\nThe consequences are paid on every production run for the life of the program.\n\n${PROBLEM_DATA['tooling-failures'].stat2}.\n\nA mold built with incorrect steel selection, inadequate cooling design, or insufficient venting does not fail catastrophically on day one. It degrades — shot count by shot count — until a production stoppage makes the problem undeniable.\n\n${PROBLEM_DATA['tooling-failures'].stat3}.\n\n$15,000–$120,000 per failure event. On a production program that runs three to five years, that is not a worst-case scenario. It is the expected cost of tooling built without lifecycle engineering.\n\n${PROBLEM_DATA['tooling-failures'].stat1}.\n\nThe 2–6 week production stoppage from an unplanned mold failure is what forces the lifecycle cost conversation. By then, the leverage to make a different tooling decision no longer exists.`,
    `Two mold quotes. Same part. Same production volume. $40,000 price difference.\n\nMost procurement teams select the lower bid.\n\n${PROBLEM_DATA['tooling-failures'].stat2}.\n\nThe cheaper mold uses softer steel. Simpler cooling circuit. Fewer vents. Less precise machining tolerances. Each decision is individually defensible. Together, they create a mold that fails 3–4x faster than the alternative.\n\n${PROBLEM_DATA['tooling-failures'].stat3}.\n\n$15,000–$120,000 per unplanned failure event. At two events per year on a five-year program, that is $150,000–$1.2M in downstream costs on a decision that saved $40,000.\n\n${PROBLEM_DATA['tooling-failures'].stat1}.\n\nThe calculation is not complicated. The problem is that the calculation is almost never done at the time the tooling decision is made.`,
  ],
  'production-bottlenecks': [
    `Injection molding throughput loss is rarely dramatic.\n\nIt accumulates — cycle by cycle — across every press that is running 10–20% longer than its optimized cycle time.\n\n${PROBLEM_DATA['production-bottlenecks'].stat1}.\n\n20–40% effective utilization loss from cycle time inefficiency. The press is occupied. The operator is busy. The throughput is not there.\n\n${PROBLEM_DATA['production-bottlenecks'].stat2}.\n\nA single press running 15% over target cycle time loses the equivalent of 1–2 full production shifts per week. On a 10-press operation, that is a capacity gap running without anyone assigning it a dollar value.\n\n${PROBLEM_DATA['production-bottlenecks'].stat3}.\n\nThe cycle time audit is the tool that makes this visible. Most operations have not run one in years — if ever.`,
    `The production schedule says 12,000 parts per shift.\n\nThe actual output is 9,400.\n\n${PROBLEM_DATA['production-bottlenecks'].stat1}.\n\nThe gap is not equipment failure. It is not unscheduled downtime. It is cycle time running above target — on every press, on every shift — because the process was never fully optimized after the mold was qualified.\n\n${PROBLEM_DATA['production-bottlenecks'].stat2}.\n\nCooling time that runs 2 seconds longer than necessary. Pack time that was set conservatively and never revisited. Injection speed that was dialed back to stop a defect and never re-optimized after the root cause was fixed.\n\n${PROBLEM_DATA['production-bottlenecks'].stat3}.\n\n$80,000–$250,000 in annual throughput loss across multi-mold operations without a cycle audit. The capacity was there all along — it just was not being accessed.`,
    `Cycle time optimization in injection molding is not a one-time event.\n\nIt is an ongoing process — because molds wear, materials vary, and conditions change across the production year.\n\n${PROBLEM_DATA['production-bottlenecks'].stat3}.\n\nOperations managing 10 or more active molds without a formal cycle time review program are almost always running slower than they need to. Not dramatically slower — incrementally slower, in ways that accumulate to significant throughput loss.\n\n${PROBLEM_DATA['production-bottlenecks'].stat1}.\n\n20–40% effective utilization loss is not theory. It is the documented output of operations that have not closed the loop between optimal cycle time and actual running cycle time.\n\n${PROBLEM_DATA['production-bottlenecks'].stat2}.\n\nThe press capacity that was supposed to support the next program launch is already there. It just needs to be recovered.`,
  ],
  'scrap-rework-cost': [
    `Scrap in injection molding is a tax on process instability.\n\nEvery percentage point above baseline scrap rate is resin purchased, melted, shot, cooled, ejected, and discarded — without producing saleable output.\n\n${PROBLEM_DATA['scrap-rework-cost'].stat1}.\n\n8–18% scrap versus 1–4% in controlled operations. That differential is not random. It is the direct output of whether process parameters are documented, validated, and maintained.\n\n${PROBLEM_DATA['scrap-rework-cost'].stat2}.\n\n$0.15–$2.50 per part in rework labor. On a production run of 500,000 parts with 10% requiring rework, that is $75,000–$1.25M in direct labor cost — from a process instability that should have been addressed at qualification.\n\n${PROBLEM_DATA['scrap-rework-cost'].stat3}.\n\n12–22% excess resin consumption in high-scrap operations. That excess is not a material cost anomaly. It is a process control cost that the material line is absorbing.`,
    `The injection molding operation running 12% scrap is not running bad parts.\n\nIt is running an uncontrolled process.\n\n${PROBLEM_DATA['scrap-rework-cost'].stat1}.\n\nThe 14-point gap between an 18% scrap rate and a 4% scrap rate does not require new equipment to close. It requires documented process parameters, routine verification, and a structured response protocol when parameters drift.\n\n${PROBLEM_DATA['scrap-rework-cost'].stat2}.\n\nRework compounds the problem. Parts that come out dimensionally marginal go to a secondary operation — adding labor cost to parts that were already expensive to produce.\n\n${PROBLEM_DATA['scrap-rework-cost'].stat3}.\n\nThe 12–22% excess resin in high-scrap operations means the material budget is funding a process inefficiency that looks like a material cost. It is not. It is a control cost — and it is addressable.`,
    `Two injection molding plants. Same press tonnage. Same resin. Same part geometry.\n\nPlant A: 3% scrap. Plant B: 14% scrap.\n\n${PROBLEM_DATA['scrap-rework-cost'].stat1}.\n\nPlant A documented their process at first article, validated parameters at production launch, and runs a scheduled verification protocol monthly. Plant B relies on experienced operators to run good settings from memory.\n\n${PROBLEM_DATA['scrap-rework-cost'].stat3}.\n\n12–22% more resin consumed annually in the high-scrap operation. On a $500,000 annual resin spend, that is $60,000–$110,000 in resin purchased and discarded — not accounting for the press time, the labor, or the parts that needed rework.\n\n${PROBLEM_DATA['scrap-rework-cost'].stat2}.\n\nRework at $2.50 per part on 60,000 rework events per year is $150,000 in labor cost that would not exist if the process had been controlled from the start.`,
  ],
  'mold-downtime': [
    `Unplanned mold downtime in injection molding is not random.\n\nFlash buildup blocks vents in a predictable number of shots. Ejector pins wear at a calculable rate. Cooling channels accumulate scale on a known timeline. Every failure mode has a schedule — the only question is whether the maintenance program runs on that schedule or waits for production to stop.\n\n${PROBLEM_DATA['mold-downtime'].stat1}.\n\n4–12 unplanned hours per mold per month without a preventive maintenance program. On a 15-mold operation, that is 60–180 hours of press capacity absorbed by avoidable failures every month.\n\n${PROBLEM_DATA['mold-downtime'].stat2}.\n\n$350–$1,800 per hour in lost throughput during unplanned mold-related stops. At 8 hours per event on a high-tonnage press, a single unplanned mold failure costs $2,800–$14,400 before repair labor is counted.\n\n${PROBLEM_DATA['mold-downtime'].stat3}.\n\n60–80% more unplanned events without PM programs. That differential is the cost of reactive maintenance — and it is payable in production output every month.`,
    `The ejector pin that breaks at hour four of a Friday night shift did not fail randomly.\n\nIt wore down across thousands of cycles — tracked by no one, inspected by no one — until the production stop made it visible.\n\n${PROBLEM_DATA['mold-downtime'].stat3}.\n\nOperations without formal mold maintenance schedules experience 60–80% more unplanned events. The events are predictable. The timing is not — which is what makes them expensive.\n\n${PROBLEM_DATA['mold-downtime'].stat1}.\n\n4–12 unplanned hours per mold per month is not an operations failure. It is a maintenance design failure. The schedule was never built.\n\n${PROBLEM_DATA['mold-downtime'].stat2}.\n\n$350–$1,800 per hour in lost throughput. The maintenance program that prevents the stop costs a fraction of the stop it prevents.`,
    `Mold preventive maintenance is not a cost center.\n\nIt is a hedge against a much larger unplanned cost.\n\n${PROBLEM_DATA['mold-downtime'].stat2}.\n\nAt $1,200 per hour of lost throughput on a mid-size press, a 6-hour unplanned mold failure costs $7,200. The preventive inspection that would have caught the failure costs a fraction of that — and it was schedulable.\n\n${PROBLEM_DATA['mold-downtime'].stat3}.\n\n60–80% fewer unplanned downtime events in operations running structured PM programs. That reduction does not come from better molds. It comes from maintaining the molds that exist.\n\n${PROBLEM_DATA['mold-downtime'].stat1}.\n\n60–180 hours of press capacity lost per month across a 15-mold operation without PM. That capacity belongs to a production schedule that could not absorb losing it.`,
  ],
  'poor-part-consistency': [
    `Part-to-part consistency in injection molding is not a quality department problem.\n\nIt is a process stability problem — and it starts at the press, not at the inspection table.\n\n${PROBLEM_DATA['poor-part-consistency'].stat1}.\n\n10–25% first-pass yield failure in operations without closed-loop process control. Every part that fails at inspection was a misused shot — press time, resin, and energy consumed without producing a saleable part.\n\n${PROBLEM_DATA['poor-part-consistency'].stat2}.\n\nPart-to-part weight variation above 0.5% is a reliable early indicator. Before any dimensional failure is confirmed, the weight variation is already there — visible in the data, absent from the daily report.\n\n${PROBLEM_DATA['poor-part-consistency'].stat3}.\n\n30–50% higher assembly line stoppage rates when supplied by inconsistent molding operations. The downstream customer is not stopping because of dimensional variation alone. They are stopping because the variation is unpredictable — and unpredictable variation cannot be managed.`,
    `The assembly line that keeps stopping is not a quality problem.\n\nIt is a supplier process problem — and the process problem lives upstream of every inspection checkpoint.\n\n${PROBLEM_DATA['poor-part-consistency'].stat3}.\n\nAssembly lines dependent on inconsistent injection-molded components experience 30–50% higher stoppage rates. The variation in melt temperature, pack pressure, and cooling time that is invisible at the press becomes a critical dimension failure at the assembly station.\n\n${PROBLEM_DATA['poor-part-consistency'].stat1}.\n\n10–25% first-pass yield failure from dimensional variation. On a supply program shipping 200,000 parts per month, that is 20,000–50,000 failures — absorbing inspection labor, creating expediting pressure, and eroding the customer relationship.\n\n${PROBLEM_DATA['poor-part-consistency'].stat2}.\n\nWeight monitoring at the press is the earliest control available. A 0.5% weight variation threshold catches process drift before it becomes a dimensional failure — at a cost far lower than downstream inspection and rework.`,
    `Melt temperature varies 8 degrees between shots.\n\nPack pressure drifts 200 psi over a two-hour run.\n\nCooling time creeps 1.5 seconds above target by end of shift.\n\nNone of these events appears on a quality report. Together, they produce a first-pass yield failure rate that cannot be explained by any single cause.\n\n${PROBLEM_DATA['poor-part-consistency'].stat1}.\n\nThis is the mechanism behind 10–25% first-pass yield failure in operations without process monitoring. The failure is not one thing going wrong. It is three or four things drifting — simultaneously, invisibly, cumulatively.\n\n${PROBLEM_DATA['poor-part-consistency'].stat2}.\n\nWeight variation above 0.5% surfaces this drift before it becomes a dimensional failure. It is the leading indicator most operations are not using.\n\n${PROBLEM_DATA['poor-part-consistency'].stat3}.\n\n30–50% more assembly stoppages from inconsistent supply. The cost of process monitoring is a fraction of the cost of the stoppages it prevents.`,
  ],
  'scaling-inefficiencies': [
    `Injection molding programs that worked at prototype volumes fail at production scale for a predictable set of reasons.\n\nTooling that was adequate for 5,000 parts per month is not adequate for 50,000. Cycle times optimized for low-volume qualification cannot sustain high-volume production rates. Process parameters locked at prototype conditions do not transfer cleanly to production equipment.\n\n${PROBLEM_DATA['scaling-inefficiencies'].stat1}.\n\n60–70% of programs scaled without DFM review encounter tooling or process failures requiring design changes — averaging $25,000–$150,000 in unplanned engineering cost.\n\n${PROBLEM_DATA['scaling-inefficiencies'].stat2}.\n\nScaling on prototype-intent tooling fails 2–3x faster than scaling on production-intent tooling. The tooling that was "good enough to start" is often the reason the program cannot scale without a mold rebuild.\n\n${PROBLEM_DATA['scaling-inefficiencies'].stat3}.\n\nA 35–55% increase in defect rate at higher production volumes is not a manufacturing failure. It is a qualification failure — the process was never characterized at the volumes the program now requires.`,
    `The prototype worked.\n\nThe pilot ran clean.\n\nThe production launch exposed every assumption that was not validated at lower volume.\n\n${PROBLEM_DATA['scaling-inefficiencies'].stat3}.\n\nDefect rates that increase as volume scales are the signature of a process that was qualified at the wrong conditions. At 5,000 shots, process variation is manageable. At 50,000, it is compounded — and defects that appeared once per thousand shots now appear continuously.\n\n${PROBLEM_DATA['scaling-inefficiencies'].stat1}.\n\n$25,000–$150,000 in unplanned engineering changes on 60–70% of programs scaled without formal DFM review. The review is not a gate — it is the session where scale assumptions are stress-tested before they become production failures.\n\n${PROBLEM_DATA['scaling-inefficiencies'].stat2}.\n\nPrototype tooling scaled to production volumes fails at 2–3x the rate of production-intent tooling. The tooling decision made at program launch determines whether scale is possible — or whether a mold rebuild is the path forward.`,
    `Scaling an injection molding program is not a production planning exercise.\n\nIt is a process engineering exercise — and most programs skip the engineering part.\n\n${PROBLEM_DATA['scaling-inefficiencies'].stat2}.\n\nTooling that was adequate for a pilot run was never designed for 50,000 shots per month. Cooling circuits sized for prototype volumes cannot sustain production cycle times. Gate geometry optimized for low-pressure fills creates flash and burn marks at production fill rates.\n\n${PROBLEM_DATA['scaling-inefficiencies'].stat3}.\n\n35–55% defect rate increase at scale is the engineering cost of skipping the characterization step. The defects were always there — at prototype volume, they were below the detection threshold.\n\n${PROBLEM_DATA['scaling-inefficiencies'].stat1}.\n\n$25,000–$150,000 in unplanned engineering cost per scale-up failure. The DFM review that would have caught this costs a fraction of the correction it prevents.`,
  ],
  'material-waste': [
    `Resin waste in injection molding has three sources — and most operations track none of them by job.\n\nSprue and runner waste: material that is shot, cooled, ejected, and either reground or discarded on every cycle. Purging losses: material consumed clearing barrels between color changes and material transitions. Startup scrap: parts produced while the process stabilizes at run start.\n\n${PROBLEM_DATA['material-waste'].stat1}.\n\n8–25% of total resin input going to these categories is the range for operations without recovery programs or optimized gate design. On a $1M annual resin spend, that is $80,000–$250,000 in material purchased and not converted to saleable product.\n\n${PROBLEM_DATA['material-waste'].stat2}.\n\n$0.50–$3.00 per kilogram in purging costs that are not tracked by job. Color-change purging is treated as a process necessity — but it is a cost center that responds to sequencing optimization.\n\n${PROBLEM_DATA['material-waste'].stat3}.\n\nHot runner tooling eliminates sprue and runner waste entirely. The tooling premium is typically recovered within 6–18 months on programs above 100,000 shots annually.`,
    `The resin spend on a monthly invoice is not the cost of the resin that went into parts.\n\nIt is the cost of the resin that went into parts plus the waste that the process consumed without producing output.\n\n${PROBLEM_DATA['material-waste'].stat1}.\n\n8–25% waste in unoptimized operations. That percentage is built into every purchase order and every cost-per-part calculation — often without a line item identifying it as waste.\n\n${PROBLEM_DATA['material-waste'].stat2}.\n\nPurging costs at $3.00 per kilogram on a program with 10 color changes per month at 5 kg per purge is $150/month in material cost that the production schedule created, not the part geometry. Sequencing changes reduce this — but only if it is tracked.\n\n${PROBLEM_DATA['material-waste'].stat3}.\n\nHot runner conversion pays back in 6–18 months on production programs above 100,000 shots annually. Most programs above that volume are still running cold runners because the tooling investment analysis was never done.`,
    `Two injection molding operations with identical resin pricing and part geometry.\n\nOne is running cold runners with no material recovery. One is running hot runners with optimized gate design.\n\n${PROBLEM_DATA['material-waste'].stat3}.\n\nHot runner tooling reduces material waste by 15–30% compared to cold runner equivalents. On a $600,000 annual resin program, that is $90,000–$180,000 in resin not going to waste. The tooling premium pays back in under two years.\n\n${PROBLEM_DATA['material-waste'].stat1}.\n\nThe operation running 20% material waste is quoting parts from a cost basis that includes $0.20 of waste per $1.00 of resin in the part. The operation running 5% waste is not.\n\n${PROBLEM_DATA['material-waste'].stat2}.\n\nPurging costs that are not tracked by job are invisible in the production cost. They accumulate — color change by color change — across a production schedule that was never optimized for material efficiency.`,
  ],
  'process-cost-leakage': [
    `Process cost leakage in injection molding is not one large problem.\n\nIt is an accumulation of small ones — each individually invisible, together consuming a significant percentage of annual production value.\n\n${PROBLEM_DATA['process-cost-leakage'].stat1}.\n\n8–15% of annual production value lost to individually untracked inefficiencies. Cycle time drift that adds 0.8 seconds per hour. Shot weight variation that means 3% of shots are out-of-spec. Pack pressure inconsistency that creates marginally acceptable parts that pass inspection but fail in assembly.\n\n${PROBLEM_DATA['process-cost-leakage'].stat2}.\n\n200–400 hours of annual productive press time lost per machine to process drift. On a 10-press operation, that is 2,000–4,000 hours of capacity consumed by instability — not by scheduled downtime, not by product changeover, by process drift.\n\n${PROBLEM_DATA['process-cost-leakage'].stat3}.\n\nOperations implementing SPC report 20–40% reductions in total quality-related cost within 12 months. The monitoring investment is a fraction of the leakage it stops.`,
    `The production report shows 96% uptime.\n\nThe efficiency report shows 78% yield.\n\nThe cost report shows material spend 14% above budget.\n\nNone of these reports points to the same problem — but they are all caused by the same thing: an injection molding process running without closed-loop monitoring.\n\n${PROBLEM_DATA['process-cost-leakage'].stat2}.\n\nProcess drift — melt temperature creeping up over a shift, cooling time expanding as the mold heats, pack pressure inconsistency between cavities — does not produce catastrophic failures. It produces marginal outputs that accumulate into significant cost.\n\n${PROBLEM_DATA['process-cost-leakage'].stat1}.\n\n8–15% of production value, spread across scrap, rework, yield loss, and overtime. None of it visible on a single report. All of it traceable to process parameters that were not monitored.\n\n${PROBLEM_DATA['process-cost-leakage'].stat3}.\n\nSPC implementation closes the loop. The leakage stops when the drift is caught.`,
    `If you ask most injection molding operations what process cost leakage costs them annually, they cannot answer.\n\nNot because the cost does not exist — but because it never appears as a single line.\n\n${PROBLEM_DATA['process-cost-leakage'].stat1}.\n\nIt appears as: slightly elevated scrap rates that everyone accepts as normal. Yield percentages that are "good enough." Overtime runs to make up for efficiency losses that were never traced to a root cause. Resin spend that runs 10% above projection every month.\n\n${PROBLEM_DATA['process-cost-leakage'].stat2}.\n\n200–400 hours per machine per year. At $800/hour average press cost, that is $160,000–$320,000 per machine in annual capacity consumed by process drift — not by any planned use of that capacity.\n\n${PROBLEM_DATA['process-cost-leakage'].stat3}.\n\n20–40% reduction in quality-related cost from SPC implementation. The monitoring makes the leakage visible. Visibility makes it fixable.`,
  ],
  'tooling-lifecycle-cost': [
    `The injection mold lifecycle cost conversation almost always happens too late.\n\nIt happens when the mold needs refurbishment at year two on a five-year program. When the repair quote exceeds the original tooling build cost. When the production downtime from the failure has already disrupted the customer delivery schedule.\n\n${PROBLEM_DATA['tooling-lifecycle-cost'].stat1}.\n\n2–4x the original build cost over five years. On a $60,000 mold, that is $120,000–$240,000 in total lifecycle spend. The procurement decision that was made on the $60,000 number was made with incomplete information.\n\n${PROBLEM_DATA['tooling-lifecycle-cost'].stat2}.\n\nMolds built with inadequate steel hardness fail 40–60% earlier. Refurbishment or replacement at $30,000–$200,000 per event eliminates the original cost savings multiple times over.\n\n${PROBLEM_DATA['tooling-lifecycle-cost'].stat3}.\n\nEvery dollar saved at tooling approval costs $3–$7 in downstream spend. The math is consistent enough across programs to treat it as a planning assumption — not an exception.`,
    `Tooling procurement in injection molding is a lifecycle cost decision presented as a build cost decision.\n\nThe $40,000 mold and the $70,000 mold are not the same purchase — even if they produce the same part geometry.\n\n${PROBLEM_DATA['tooling-lifecycle-cost'].stat3}.\n\nThe $30,000 saved at tooling approval generates $90,000–$210,000 in downstream costs over five years. That is not a worst-case projection. It is the documented cost ratio for tooling built without lifecycle engineering.\n\n${PROBLEM_DATA['tooling-lifecycle-cost'].stat2}.\n\nMolds built to inadequate specifications fail 40–60% earlier than properly engineered tooling. On a program designed for 500,000 shots per year, early failure means a refurbishment event at the point of maximum production demand.\n\n${PROBLEM_DATA['tooling-lifecycle-cost'].stat1}.\n\nTotal lifecycle cost of 2–4x the build cost is the expected outcome — not the exception. The programs that beat that ratio chose tooling with that ratio in mind from the start.`,
    `The tooling approval meeting should include a lifecycle cost model.\n\nMost do not.\n\n${PROBLEM_DATA['tooling-lifecycle-cost'].stat1}.\n\n2–4x the build cost over five years is the average. The programs that hit 4x were not unusual programs — they were programs where the tooling decision was made on build cost alone, without modeling repair frequency, refurbishment timing, or production loss from failure events.\n\n${PROBLEM_DATA['tooling-lifecycle-cost'].stat3}.\n\n$3–$7 in downstream cost per $1 saved at tooling approval. On a $30,000 tooling shortcut, that is $90,000–$210,000 in repair, downtime, and scrap costs over the program life.\n\n${PROBLEM_DATA['tooling-lifecycle-cost'].stat2}.\n\nMolds built with inadequate hardness specifications do not fail visibly. They degrade — gradually increasing flash, slowly losing dimensional control, intermittently jamming ejectors — until the repair cost forces the conversation the tooling approval meeting should have had.`,
  ],
}

const BUSINESS_IMPACTS: Record<string, string> = {
  'injection-molding-defects': `Operational exposure: ${PROBLEM_DATA['injection-molding-defects'].cost1}. ${PROBLEM_DATA['injection-molding-defects'].cost2}. For a molding operation producing 300,000 parts per month at 10% defect rate, 30,000 defective parts are produced monthly. At an average part cost of $1.50, that is $45,000 in direct production cost per month yielding no saleable output — before any downstream escape costs are counted.`,
  'tooling-failures': `Financial exposure: ${PROBLEM_DATA['tooling-failures'].cost1}. ${PROBLEM_DATA['tooling-failures'].cost2}. A production program running $180,000 per month in output absorbs $360,000–$1.08M in revenue impact from a single 2–6 week mold failure event. The mold repair itself is the smallest component of the total cost.`,
  'production-bottlenecks': `Throughput exposure: ${PROBLEM_DATA['production-bottlenecks'].cost1}. ${PROBLEM_DATA['production-bottlenecks'].cost2}. A 10-press operation with each press running 20% below optimal cycle efficiency is operating with the equivalent of 2 phantom presses — capacity that exists on paper and is consumed by process inefficiency before any production output is captured.`,
  'scrap-rework-cost': `Cost exposure: ${PROBLEM_DATA['scrap-rework-cost'].cost1}. ${PROBLEM_DATA['scrap-rework-cost'].cost2}. On a $400,000 monthly resin spend, 15% scrap means $60,000 in resin purchased and not converted to saleable output each month. That is $720,000 annually in material cost funding a process instability that responds to process controls — not capital investment.`,
  'mold-downtime': `Production exposure: ${PROBLEM_DATA['mold-downtime'].cost1}. ${PROBLEM_DATA['mold-downtime'].cost2}. A 15-mold operation averaging 8 unplanned hours per mold per month absorbs 120 hours of press capacity per month from mold-related failures alone. At $900/hour average press cost, that is $108,000 per month in production capacity consumed by preventable failures.`,
  'poor-part-consistency': `Yield exposure: ${PROBLEM_DATA['poor-part-consistency'].cost1}. ${PROBLEM_DATA['poor-part-consistency'].cost2}. For an OEM or Tier 1 supplier receiving inconsistent injection-molded components, 30–50% higher assembly stoppages means engineering resources, line labor, and production schedule margin consumed by a supplier process problem — with no direct visibility into the upstream cause.`,
  'scaling-inefficiencies': `Program exposure: ${PROBLEM_DATA['scaling-inefficiencies'].cost1}. ${PROBLEM_DATA['scaling-inefficiencies'].cost2}. A $25,000–$150,000 unplanned engineering cost at production launch is the direct exposure. The indirect cost — delayed customer deliveries, emergency tooling rebuild lead times of 8–16 weeks, and assembly line disruptions downstream — compounds the initial figure significantly.`,
  'material-waste': `Material exposure: ${PROBLEM_DATA['material-waste'].cost1}. ${PROBLEM_DATA['material-waste'].cost2}. An injection molding operation with $800,000 in annual resin spend running 15% material waste is spending $120,000 per year on resin that does not become product. Hot runner conversion on qualifying programs eliminates sprue and runner waste — and pays back within the first 12–18 months of production.`,
  'process-cost-leakage': `Efficiency exposure: ${PROBLEM_DATA['process-cost-leakage'].cost1}. ${PROBLEM_DATA['process-cost-leakage'].cost2}. A 10-press injection molding operation losing 300 productive hours per machine annually to process drift is operating with 3,000 hours of hidden annual capacity loss. At $700/hour average press cost, that is $2.1M in production capacity consumed by unmonitored process instability — not by planned production.`,
  'tooling-lifecycle-cost': `Lifecycle exposure: ${PROBLEM_DATA['tooling-lifecycle-cost'].cost1}. ${PROBLEM_DATA['tooling-lifecycle-cost'].cost2}. A tooling portfolio of 20 active molds with an average build cost of $50,000 — $1M in tooling capital — carries an expected total lifecycle cost of $2M–$4M over five years. Programs that modeled this at tooling approval selected tooling specifications that reduced the lifecycle multiple. Programs that did not are paying the difference in repair and downtime.`,
}

const CTAS: string[] = [
  "If you're managing a molding operation and not tracking these variables, that's worth a 15-minute conversation. Link in comments.",
  "What does your current defect rate or scrap rate tell you about your process control? Most operations haven't done the math.",
  "We've mapped the real cost drivers for molding programs like yours. Comment 'AUDIT' and I'll share the breakdown.",
  "Tag an engineering manager who has absorbed a tooling or process cost that never showed up on the original program budget.",
  "Drop your production volume and part type in the comments. I'll outline where cost leakage typically concentrates in your program.",
]

const IMPROVEMENT_SUGGESTIONS: Record<string, string[]> = {
  'injection-molding-defects': [
    'Add a specific defect type (sink marks, flash, short shots) with the process parameter most likely responsible — it anchors the post to real operator experience.',
    'Include the cost comparison between catching a defect at the press versus at final inspection versus after it reaches the customer assembly line.',
    'Reference the specific process documentation format (process sheets, control plans, PFMEA) that closes the parameter documentation gap.',
  ],
  'tooling-failures': [
    'Name the specific steel grade comparison (P20 vs. H13 vs. S7) and the production volume threshold where the higher-specification steel pays back — it gives procurement teams a concrete framework.',
    'Include the questions to ask a toolmaker that reveal whether they are engineering for lifecycle cost or for build cost minimization.',
    'Add the failure mode comparison: what a steel hardness failure looks like in production versus what inadequate venting looks like — both are common, both are different root causes.',
  ],
  'production-bottlenecks': [
    'Add the specific cycle time audit process — what parameters to measure, where to find the data, and how to calculate the throughput gap against optimal cycle time.',
    'Include the cooling time optimization framework — the most commonly underoptimized cycle time variable in injection molding operations.',
    'Reference the production data source (machine controller logs, MES systems) that makes cycle time variance visible without manual measurement.',
  ],
  'scrap-rework-cost': [
    'Name the statistical process control tools (X-bar R charts, Cpk tracking) that detect the process drift behind high scrap rates before the scrap accumulates.',
    'Include the scrap cost calculation by part geometry — the cost per defective part varies dramatically between a commodity commodity part and a multi-cavity technical part.',
    'Add the first-article inspection process that locks parameters at job startup — the checkpoint that prevents most startup scrap from accumulating.',
  ],
  'mold-downtime': [
    'Name the specific PM interval for the most common failure modes — ejector pin inspection at X shots, vent cleaning at Y shots, parting line inspection at Z shots.',
    'Include the mold log format that tracks shots, maintenance events, and observations — the tool that makes PM scheduling data-driven rather than calendar-based.',
    'Add the cost comparison between scheduled PM labor cost and unplanned downtime cost per event for the same mold type.',
  ],
  'poor-part-consistency': [
    'Add the weight monitoring protocol — what frequency, what tolerance, and what action to take when weight variation exceeds the 0.5% threshold.',
    'Include the process parameter variables most commonly responsible for dimensional variation — melt temperature, pack pressure, and cooling time variation — with the typical drift ranges.',
    'Reference the inline SPC monitoring tools available on modern injection molding machines and what they catch that end-of-run inspection misses.',
  ],
  'scaling-inefficiencies': [
    'Add the DFM review checklist for injection molding programs transitioning from prototype to production — the specific questions that catch scale-up failures before tooling is committed.',
    'Include the tooling specification differences between prototype-intent and production-intent tooling — steel grade, cooling design, ejection design — so engineering teams know what to specify.',
    'Reference the process characterization study required at scale-up — DOE, process window development, control plan validation.',
  ],
  'material-waste': [
    'Add the hot runner payback calculation framework — how to model the tooling premium against the material savings at a given annual shot volume.',
    'Include the purging loss tracking method — how to calculate purging cost by material transition type and build it into job cost analysis.',
    'Name the regrind usage policy considerations — what percentage of regrind is acceptable for various part specifications and how regrind affects process stability.',
  ],
  'process-cost-leakage': [
    'Add the SPC implementation sequence for injection molding — which process parameters to monitor first, what control limits to set, and how to build the monitoring protocol without disrupting production.',
    'Include the process audit framework — the sequence for evaluating a running injection molding operation to quantify current process cost leakage before implementing controls.',
    'Reference the data connection between process monitoring and production reporting — how to build a cost leakage dashboard from data that most molding operations already have.',
  ],
  'tooling-lifecycle-cost': [
    'Add the lifecycle cost model structure — what inputs to include, how to estimate repair frequency, and how to compare two tooling specs on a total cost basis rather than build cost.',
    'Include the tooling specification variables that most influence lifecycle cost: steel grade, hardness, cooling circuit design, venting adequacy, and ejection system robustness.',
    'Reference the tooling audit process for existing molds — how to assess remaining tool life and model the refurbishment decision against continued operation.',
  ],
}

const POST_IDEAS: Record<string, PostIdea[]> = {
  'injection-molding-defects': [
    { title: 'Why Injection Molding Defects Are a Process Control Failure, Not a Quality Failure', angle: 'Assumption Challenge', rank: 1, painClarity: 10, financialImpact: 9, tension: 10 },
    { title: 'The 3–5x Defect Rate Differential Between Controlled and Uncontrolled Operations', angle: 'Industry Benchmark', rank: 2, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'Sink Marks, Flash, Short Shots: Each Has a Different Name and the Same Root Cause', angle: 'Process Breakdown', rank: 3, painClarity: 9, financialImpact: 8, tension: 9 },
    { title: 'The Escaped Defect That Triggered a Field Recall: The 100x Cost Multiplier', angle: 'Financial Impact', rank: 4, painClarity: 10, financialImpact: 10, tension: 10 },
    { title: 'How Undocumented Process Parameters Guarantee a 5–15% Defect Rate', angle: 'Insider Knowledge', rank: 5, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'What Separates a 2% Defect Rate from a 15% Defect Rate: It Is Not the Equipment', angle: 'Contrarian Take', rank: 6, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'The Process Parameter Documentation That Prevents Most Molding Defects', angle: 'Decision Framework', rank: 7, painClarity: 8, financialImpact: 8, tension: 8 },
    { title: 'Tribal Knowledge vs. Documented Parameters: What the Defect Rate Reflects', angle: 'Operational Risk', rank: 8, painClarity: 9, financialImpact: 8, tension: 9 },
    { title: 'First Article Inspection vs. In-Process Control: Where Defect Prevention Actually Happens', angle: 'Case Study Style', rank: 9, painClarity: 8, financialImpact: 9, tension: 8 },
    { title: 'The Monthly Defect Cost Calculation Most Injection Molding Plants Have Never Run', angle: 'Hidden Cost Exposure', rank: 10, painClarity: 9, financialImpact: 10, tension: 9 },
  ],
  'tooling-failures': [
    { title: 'The $40,000 Mold That Cost $200,000 to Operate: The Lifecycle Math', angle: 'Financial Impact', rank: 1, painClarity: 10, financialImpact: 10, tension: 10 },
    { title: 'Why Cheap Tooling Fails 3–4x Faster Than Properly Engineered Molds', angle: 'Industry Benchmark', rank: 2, painClarity: 9, financialImpact: 10, tension: 9 },
    { title: 'The Tooling Failure Nobody Saw Coming (Until the Production Stop Made It Unavoidable)', angle: 'Case Study Style', rank: 3, painClarity: 9, financialImpact: 9, tension: 10 },
    { title: '$120,000 per Tooling Failure Event: The Cost Most Procurement Decisions Ignore', angle: 'Hidden Cost Exposure', rank: 4, painClarity: 10, financialImpact: 10, tension: 9 },
    { title: 'Steel Grade Selection and the Tooling Failure Rate It Determines', angle: 'Process Breakdown', rank: 5, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'Two Tooling Quotes, Same Part, Very Different Five-Year Costs', angle: 'Contrarian Take', rank: 6, painClarity: 10, financialImpact: 10, tension: 10 },
    { title: 'Why Tooling Failures Always Happen at the Worst Possible Time', angle: 'Operational Risk', rank: 7, painClarity: 9, financialImpact: 8, tension: 9 },
    { title: 'The Tooling Specification Questions That Separate Build Cost from Lifecycle Cost', angle: 'Decision Framework', rank: 8, painClarity: 8, financialImpact: 9, tension: 8 },
    { title: 'Core Damage, Gate Erosion, Parting Line Wear: How Each Failure Mode Starts', angle: 'Insider Knowledge', rank: 9, painClarity: 8, financialImpact: 8, tension: 8 },
    { title: 'The Production Program That Could Not Scale Because the Mold Could Not Hold', angle: 'Assumption Challenge', rank: 10, painClarity: 9, financialImpact: 9, tension: 9 },
  ],
  'production-bottlenecks': [
    { title: 'Your Press Is Running 20% Below Optimal Throughput and No Report Shows It', angle: 'Hidden Cost Exposure', rank: 1, painClarity: 10, financialImpact: 10, tension: 10 },
    { title: '$250,000 in Annual Throughput Loss from Avoidable Cycle Time Inefficiency', angle: 'Financial Impact', rank: 2, painClarity: 9, financialImpact: 10, tension: 9 },
    { title: 'The Cycle Time Audit That Recovers the Capacity You Already Paid For', angle: 'Decision Framework', rank: 3, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'Why Cooling Time Is the Most Commonly Underoptimized Cycle Variable', angle: 'Insider Knowledge', rank: 4, painClarity: 9, financialImpact: 8, tension: 9 },
    { title: 'The Phantom Press: Throughput Loss That Shows Up as Capacity Shortage', angle: 'Contrarian Take', rank: 5, painClarity: 9, financialImpact: 9, tension: 10 },
    { title: 'Gate Placement, Fill Speed, and the Cycle Time Cost of Getting Them Wrong', angle: 'Process Breakdown', rank: 6, painClarity: 8, financialImpact: 9, tension: 8 },
    { title: 'When the Production Schedule Says 12,000 and the Output Is 9,400', angle: 'Case Study Style', rank: 7, painClarity: 10, financialImpact: 9, tension: 10 },
    { title: '1–2 Production Shifts Lost Per Press Per Week: The Cycle Time Math', angle: 'Industry Benchmark', rank: 8, painClarity: 9, financialImpact: 9, tension: 8 },
    { title: 'Process Optimization vs. Capital Investment: Where the Throughput Gap Actually Lives', angle: 'Assumption Challenge', rank: 9, painClarity: 9, financialImpact: 10, tension: 9 },
    { title: 'The Multi-Mold Operation That Had No Idea What Its Optimal Cycle Time Was', angle: 'Operational Risk', rank: 10, painClarity: 8, financialImpact: 8, tension: 8 },
  ],
  'scrap-rework-cost': [
    { title: '14 Percentage Points of Scrap Rate Difference Between Controlled and Uncontrolled Operations', angle: 'Industry Benchmark', rank: 1, painClarity: 10, financialImpact: 10, tension: 9 },
    { title: '$720,000 in Annual Resin Wasted to Scrap: The Process Control Cost', angle: 'Financial Impact', rank: 2, painClarity: 10, financialImpact: 10, tension: 9 },
    { title: 'Why Scrap Is a Process Stability Metric, Not a Quality Metric', angle: 'Assumption Challenge', rank: 3, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'The 12–22% Excess Resin Consumption Built Into Every High-Scrap Production Run', angle: 'Hidden Cost Exposure', rank: 4, painClarity: 9, financialImpact: 10, tension: 9 },
    { title: 'Rework at $2.50 Per Part Across 60,000 Annual Events: The Math', angle: 'Process Breakdown', rank: 5, painClarity: 9, financialImpact: 9, tension: 8 },
    { title: 'What the Scrap Rate Tells You Before the Quality Report Does', angle: 'Insider Knowledge', rank: 6, painClarity: 9, financialImpact: 8, tension: 9 },
    { title: 'Two Plants, Same Equipment, 11% Scrap Rate Difference: The Variable That Explains It', angle: 'Case Study Style', rank: 7, painClarity: 10, financialImpact: 9, tension: 10 },
    { title: 'Documented Parameters vs. Operator Memory: The Scrap Rate Outcome', angle: 'Contrarian Take', rank: 8, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'How to Calculate the True Cost of Scrap in an Injection Molding Operation', angle: 'Decision Framework', rank: 9, painClarity: 8, financialImpact: 10, tension: 8 },
    { title: 'The Startup Scrap Accumulation That Nobody Tracks Back to a Root Cause', angle: 'Operational Risk', rank: 10, painClarity: 8, financialImpact: 9, tension: 8 },
  ],
  'mold-downtime': [
    { title: '$1,800/Hour When the Press Stops for a Mold Issue: The Downtime Math', angle: 'Financial Impact', rank: 1, painClarity: 10, financialImpact: 10, tension: 10 },
    { title: '60–80% More Unplanned Downtime Without a Mold PM Program', angle: 'Industry Benchmark', rank: 2, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'The Ejector Pin That Failed at 2 AM Because Nobody Had a Maintenance Schedule', angle: 'Case Study Style', rank: 3, painClarity: 9, financialImpact: 9, tension: 10 },
    { title: '120 Hours of Monthly Press Capacity Lost to Mold-Related Failures in a 15-Mold Operation', angle: 'Hidden Cost Exposure', rank: 4, painClarity: 9, financialImpact: 10, tension: 9 },
    { title: 'Flash Buildup, Vent Clogging, Core Wear: Each Has a Predictable Failure Schedule', angle: 'Process Breakdown', rank: 5, painClarity: 9, financialImpact: 8, tension: 9 },
    { title: 'Reactive vs. Preventive Mold Maintenance: The Cost Comparison Per Event', angle: 'Decision Framework', rank: 6, painClarity: 8, financialImpact: 9, tension: 8 },
    { title: 'Deferred Mold Maintenance Is Not Cost Avoidance. It Is Cost Scheduling.', angle: 'Contrarian Take', rank: 7, painClarity: 10, financialImpact: 9, tension: 10 },
    { title: 'The PM Interval That Prevents the Most Common Mold Failure Modes', angle: 'Insider Knowledge', rank: 8, painClarity: 8, financialImpact: 8, tension: 8 },
    { title: 'Why Mold Failures Always Coincide with Peak Production Demand', angle: 'Operational Risk', rank: 9, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'The Mold Log That Makes PM Scheduling Data-Driven Instead of Calendar-Based', angle: 'Assumption Challenge', rank: 10, painClarity: 8, financialImpact: 8, tension: 8 },
  ],
  'poor-part-consistency': [
    { title: '10–25% First-Pass Yield Failure from Dimensional Variation Nobody Traced to the Press', angle: 'Hidden Cost Exposure', rank: 1, painClarity: 10, financialImpact: 10, tension: 10 },
    { title: 'The Assembly Line That Kept Stopping Because of a Supplier Process Nobody Monitored', angle: 'Case Study Style', rank: 2, painClarity: 9, financialImpact: 9, tension: 10 },
    { title: '30–50% Higher Assembly Stoppages from Inconsistent Molded Components', angle: 'Industry Benchmark', rank: 3, painClarity: 9, financialImpact: 10, tension: 9 },
    { title: 'Weight Variation Above 0.5%: The Process Instability Indicator Most Operations Ignore', angle: 'Insider Knowledge', rank: 4, painClarity: 9, financialImpact: 8, tension: 9 },
    { title: 'Melt Temperature Drift, Pack Pressure Variation, Cooling Time Creep: The Consistency Killers', angle: 'Process Breakdown', rank: 5, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'Part Inconsistency Is Not a Dimensional Problem. It Is a Process Stability Problem.', angle: 'Assumption Challenge', rank: 6, painClarity: 10, financialImpact: 9, tension: 10 },
    { title: 'Why Inspection Cannot Fix the Consistency Problem That Starts at the Press', angle: 'Contrarian Take', rank: 7, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'The Process Monitoring Protocol That Catches Dimensional Drift Before Inspection Does', angle: 'Decision Framework', rank: 8, painClarity: 8, financialImpact: 9, tension: 8 },
    { title: "What Downstream Assembly Stoppages Actually Tell You About Your Supplier's Process", angle: 'Operational Risk', rank: 9, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'Closed-Loop Process Control vs. End-of-Run Inspection: The Yield Difference', angle: 'Financial Impact', rank: 10, painClarity: 8, financialImpact: 9, tension: 8 },
  ],
  'scaling-inefficiencies': [
    { title: '60–70% of Injection Molding Programs Scaled Without DFM Review Fail at Volume', angle: 'Industry Benchmark', rank: 1, painClarity: 10, financialImpact: 10, tension: 9 },
    { title: '$150,000 in Unplanned Engineering Changes: The Scale-Up Cost Nobody Budgeted', angle: 'Financial Impact', rank: 2, painClarity: 10, financialImpact: 10, tension: 9 },
    { title: 'Why Defect Rates Increase When Injection Molding Programs Scale', angle: 'Contrarian Take', rank: 3, painClarity: 9, financialImpact: 9, tension: 10 },
    { title: 'Prototype Tooling vs. Production Tooling: The Failure Rate Difference at Scale', angle: 'Process Breakdown', rank: 4, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'The DFM Review That Prevents the 35–55% Defect Rate Increase at Volume', angle: 'Decision Framework', rank: 5, painClarity: 8, financialImpact: 9, tension: 8 },
    { title: 'Scale Amplifies What Is Already Broken in an Injection Molding Process', angle: 'Insider Knowledge', rank: 6, painClarity: 10, financialImpact: 9, tension: 10 },
    { title: 'Process Characterization at Scale: The Step Most Programs Skip Before Launch', angle: 'Operational Risk', rank: 7, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'The Program That Ran Fine at 5,000 Parts and Failed at 50,000', angle: 'Case Study Style', rank: 8, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'Production-Intent Tooling vs. Prototype Tooling: What the Specification Difference Costs', angle: 'Hidden Cost Exposure', rank: 9, painClarity: 8, financialImpact: 9, tension: 8 },
    { title: 'Why Scaling an Injection Molding Program Is a Process Engineering Exercise, Not a Planning Exercise', angle: 'Assumption Challenge', rank: 10, painClarity: 9, financialImpact: 8, tension: 9 },
  ],
  'material-waste': [
    { title: 'The 8–25% Resin Waste Built Into Every Cold Runner Production Run', angle: 'Hidden Cost Exposure', rank: 1, painClarity: 10, financialImpact: 10, tension: 9 },
    { title: '$250,000 in Annual Resin Waste That Is Not Tracked as Waste', angle: 'Financial Impact', rank: 2, painClarity: 9, financialImpact: 10, tension: 8 },
    { title: 'Hot Runner Payback in 12–18 Months: The Tooling Investment Most Plants Delay', angle: 'Decision Framework', rank: 3, painClarity: 8, financialImpact: 9, tension: 8 },
    { title: 'Purging Costs at $3/kg: The Production Cost Nobody Tracks by Job', angle: 'Insider Knowledge', rank: 4, painClarity: 9, financialImpact: 9, tension: 8 },
    { title: 'Material Cost or Material Waste: The Difference Most Invoices Do Not Show', angle: 'Assumption Challenge', rank: 5, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'Cold Runner vs. Hot Runner: The Resin Efficiency Gap at 100,000 Shots Per Year', angle: 'Industry Benchmark', rank: 6, painClarity: 8, financialImpact: 9, tension: 8 },
    { title: 'Gate Design and the Material Waste Decision That Was Made Before Production Started', angle: 'Process Breakdown', rank: 7, painClarity: 8, financialImpact: 8, tension: 8 },
    { title: 'Why Your Resin Spend Is Running Above Projection Every Month', angle: 'Operational Risk', rank: 8, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'The Material Efficiency Difference Between Two Identical Programs, Different Tooling', angle: 'Contrarian Take', rank: 9, painClarity: 9, financialImpact: 10, tension: 9 },
    { title: 'Regrind Policy, Runner Recovery, Purge Sequencing: The Three Material Cost Levers', angle: 'Case Study Style', rank: 10, painClarity: 8, financialImpact: 8, tension: 8 },
  ],
  'process-cost-leakage': [
    { title: '8–15% of Annual Production Value Lost to Individually Invisible Inefficiencies', angle: 'Hidden Cost Exposure', rank: 1, painClarity: 10, financialImpact: 10, tension: 9 },
    { title: 'The Injection Molding Cost That Spans Scrap, Yield, Overtime, and Resin — and Appears on None of Those Reports', angle: 'Financial Impact', rank: 2, painClarity: 10, financialImpact: 10, tension: 10 },
    { title: '2,000 Hours of Annual Press Capacity Lost to Process Drift in a 10-Press Shop', angle: 'Industry Benchmark', rank: 3, painClarity: 9, financialImpact: 10, tension: 9 },
    { title: 'Why the Production Report Shows 96% Uptime and the Cost Report Shows 14% Over Budget', angle: 'Case Study Style', rank: 4, painClarity: 10, financialImpact: 9, tension: 10 },
    { title: 'Cycle Time Drift, Shot Weight Variation, Pack Pressure Inconsistency: The Three Leakage Sources', angle: 'Process Breakdown', rank: 5, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'SPC in Injection Molding: 20–40% Quality Cost Reduction in 12 Months', angle: 'Decision Framework', rank: 6, painClarity: 8, financialImpact: 9, tension: 8 },
    { title: 'Why Most Injection Molding Operations Cannot Answer "What Does Process Leakage Cost Us?"', angle: 'Assumption Challenge', rank: 7, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'Process Monitoring as a Cost Control Tool, Not a Quality Tool', angle: 'Contrarian Take', rank: 8, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'The Cost That Is Simultaneously Scrap, Overtime, Yield Loss, and Resin Overage', angle: 'Insider Knowledge', rank: 9, painClarity: 10, financialImpact: 10, tension: 9 },
    { title: '$2.1M in Hidden Annual Capacity Loss: The 10-Press Process Leakage Calculation', angle: 'Operational Risk', rank: 10, painClarity: 9, financialImpact: 10, tension: 9 },
  ],
  'tooling-lifecycle-cost': [
    { title: 'Every $1 Saved on Tooling Costs $3–$7 Downstream: The Injection Mold Math', angle: 'Financial Impact', rank: 1, painClarity: 10, financialImpact: 10, tension: 10 },
    { title: 'Total Mold Lifecycle Cost Is 2–4x the Build Cost: What That Means for a $60,000 Tool', angle: 'Industry Benchmark', rank: 2, painClarity: 9, financialImpact: 10, tension: 9 },
    { title: 'The Tooling Approval Meeting That Should Have Included a Lifecycle Cost Model', angle: 'Assumption Challenge', rank: 3, painClarity: 9, financialImpact: 9, tension: 10 },
    { title: '$30,000 Saved at Tooling Approval. $210,000 Paid in Downstream Repair and Downtime.', angle: 'Case Study Style', rank: 4, painClarity: 10, financialImpact: 10, tension: 10 },
    { title: 'Inadequate Steel Hardness and the Tooling Failure Rate It Produces', angle: 'Process Breakdown', rank: 5, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'Build Cost vs. Lifecycle Cost: The Tooling Decision Frame Most Procurement Teams Skip', angle: 'Decision Framework', rank: 6, painClarity: 9, financialImpact: 10, tension: 9 },
    { title: 'Why the Cheapest Injection Mold Is Almost Never the Lowest-Cost Mold', angle: 'Contrarian Take', rank: 7, painClarity: 10, financialImpact: 10, tension: 10 },
    { title: 'The Mold Refurbishment That Was Inevitable from the Tooling Spec It Was Built To', angle: 'Insider Knowledge', rank: 8, painClarity: 9, financialImpact: 9, tension: 9 },
    { title: 'Steel Grade, Cooling Design, Ejection Robustness: The Lifecycle Cost Variables', angle: 'Operational Risk', rank: 9, painClarity: 8, financialImpact: 9, tension: 8 },
    { title: 'How to Build a Tooling Lifecycle Cost Model Before the Mold Is Approved', angle: 'Insider Knowledge', rank: 10, painClarity: 8, financialImpact: 9, tension: 8 },
  ],
}

const CALENDAR_ENTRIES: CalendarEntry[] = [
  { day: 1, topic: 'Injection Molding Defects', hook: 'Your defect rate is not a quality metric. It is a process control metric — and right now it is telling you something your inspection report is not.', angle: 'Assumption Challenge', cta: 'What is your current defect rate, and do you have documented process parameters for the parts that are failing?' },
  { day: 2, topic: 'Tooling Failures', hook: 'The tooling decision made at program approval determines the production cost for the next five years. Most teams make it on build cost alone.', angle: 'Financial Impact', cta: 'When did your last unplanned mold failure occur, and what was the total cost including downtime and expediting?' },
  { day: 3, topic: 'Production Bottlenecks', hook: 'Your press is running 20% below optimal throughput and no daily report shows it. The gap lives in the cycle time nobody has audited.', angle: 'Hidden Cost Exposure', cta: 'What is your current cycle time versus the optimized target for your highest-volume part?' },
  { day: 4, topic: 'Scrap and Rework Cost', hook: 'The difference between 3% scrap and 15% scrap is not equipment. It is documented, validated, and locked process parameters.', angle: 'Industry Benchmark', cta: 'Have you calculated what your current scrap rate costs in resin and press time annually?' },
  { day: 5, topic: 'Downtime from Mold Issues', hook: 'Mold maintenance deferred is not cost avoided. It is downtime scheduled at a time your production team cannot control.', angle: 'Contrarian Take', cta: 'Do you have a formal mold PM schedule tied to shot count, or are you reacting to failures when they occur?' },
  { day: 6, topic: 'Poor Part Consistency', hook: 'Part-to-part weight variation above 0.5% is already predicting the dimensional failures your inspection team will find 48 hours from now.', angle: 'Insider Knowledge', cta: 'Is your operation tracking part weight as a real-time process stability indicator?' },
  { day: 7, topic: 'Scaling Inefficiencies', hook: 'Scale amplifies what is already broken in an injection molding process. The defect that appeared once per thousand shots at prototype volume appears continuously at production volume.', angle: 'Operational Risk', cta: 'Did your most recent program scale-up include a formal process characterization study at production conditions?' },
  { day: 8, topic: 'Material Waste', hook: '8–25% of your resin spend is going to sprues, runners, and purging that most operations do not track by job. That waste is embedded in every cost-per-part calculation.', angle: 'Hidden Cost Exposure', cta: 'Have you calculated your annual resin waste as a percentage of total resin spend?' },
  { day: 9, topic: 'Process Cost Leakage', hook: '8–15% of annual production value lost to individually invisible inefficiencies. None of them appears as a single line on any report. Together they are your most expensive cost center.', angle: 'Financial Impact', cta: 'If you summed your scrap, yield loss, overtime, and resin overage for last year, what percentage of production value would it represent?' },
  { day: 10, topic: 'Tooling Lifecycle Cost', hook: 'Every dollar saved on tooling upfront costs $3–$7 in downstream repair, downtime, and scrap. Most procurement decisions are made without that ratio in the analysis.', angle: 'Decision Framework', cta: 'Does your tooling approval process include a lifecycle cost model, or does the decision stop at build cost comparison?' },
  { day: 11, topic: 'Injection Molding Defects', hook: 'Flash, sink marks, and short shots all have different causes. They share one root: a process that runs on tribal knowledge instead of documented, validated parameters.', angle: 'Process Breakdown', cta: 'Tag an engineering manager whose team is fighting recurring defects without a process parameter documentation system.' },
  { day: 12, topic: 'Tooling Failures', hook: 'A mold built with inadequate steel hardness does not fail on day one. It degrades — shot by shot — until the production stop makes the problem undeniable.', angle: 'Insider Knowledge', cta: 'What is the steel specification on your current highest-volume mold, and what failure rate have you experienced on it?' },
  { day: 13, topic: 'Production Bottlenecks', hook: 'Cooling time is the most commonly underoptimized variable in injection molding cycle time. Most operations set it conservatively at qualification and never revisit it.', angle: 'Insider Knowledge', cta: 'When did you last run a cooling time optimization study on your top three highest-volume molds?' },
  { day: 14, topic: 'Scrap and Rework Cost', hook: 'Scrap in injection molding consumes not just the resin — it consumes the press time, the energy, the operator labor, and the machine capacity that could have produced saleable output.', angle: 'Process Breakdown', cta: 'Is your operation tracking scrap as a cost per shift, or only as a percentage that gets reviewed monthly?' },
  { day: 15, topic: 'Downtime from Mold Issues', hook: '$1,800 per hour of lost throughput during an unplanned mold stop. The PM program that prevents the stop costs a fraction of what the stop costs.', angle: 'Financial Impact', cta: 'What was your last unplanned mold downtime event? What did the total cost look like when you included lost throughput?' },
  { day: 16, topic: 'Poor Part Consistency', hook: 'Assembly lines stop not because the part is bad — but because the part is unpredictably variable. An occasional bad part is manageable. Unpredictable variation is not.', angle: 'Operational Risk', cta: 'What is the downstream cost of part inconsistency on your highest-volume supply program?' },
  { day: 17, topic: 'Scaling Inefficiencies', hook: '60–70% of injection molding programs scaled without DFM review encounter tooling or process failures requiring design changes. The review costs a fraction of what the change costs.', angle: 'Industry Benchmark', cta: 'Did your last program launch include a formal DFM review before tooling was approved?' },
  { day: 18, topic: 'Material Waste', hook: 'Hot runner tooling eliminates sprue and runner waste. The tooling premium pays back in 6–18 months on programs above 100,000 shots annually. Most qualifying programs are still running cold runners.', angle: 'Decision Framework', cta: 'What is the annual shot volume on your highest-volume program? Have you run the hot runner payback calculation?' },
  { day: 19, topic: 'Process Cost Leakage', hook: 'Cycle time drift adds 0.8 seconds per hour. Shot weight variation means 3% of shots are out-of-spec. Pack pressure inconsistency creates marginal parts that pass inspection and fail in assembly. None of these events appears on a single report.', angle: 'Process Breakdown', cta: 'Is your operation running closed-loop process monitoring on active injection molding presses?' },
  { day: 20, topic: 'Tooling Lifecycle Cost', hook: 'The total lifecycle cost of an injection mold averages 2–4x the original build cost over five years. On a $60,000 mold, that is $120,000–$240,000 in total spend. The procurement decision was made on $60,000.', angle: 'Industry Benchmark', cta: 'Have you ever modeled the full 5-year lifecycle cost of your most-used molds? Most operations have not.' },
  { day: 21, topic: 'Injection Molding Defects', hook: 'Operations running without documented process parameters experience defect rates 3–5x higher than controlled operations. The equipment is often identical. The documentation is not.', angle: 'Industry Benchmark', cta: 'Comment with the most common defect type in your molding operation. I will outline the process parameters most likely driving it.' },
  { day: 22, topic: 'Tooling Failures', hook: 'Two mold quotes: $45,000 and $75,000 for the same part. The $45,000 mold will fail 3–4x faster. At $80,000 per failure event, the math resolves quickly.', angle: 'Contrarian Take', cta: 'Have you ever run a total cost comparison between two tooling quotes that included failure rate and repair cost projections?' },
  { day: 23, topic: 'Production Bottlenecks', hook: 'A 10-press operation with each press running 20% below optimal cycle time is leaving the equivalent of two full presses worth of capacity on the table — without any equipment gap.', angle: 'Contrarian Take', cta: 'What is your current OEE on injection molding assets, and how much of the gap is attributable to cycle time versus downtime?' },
  { day: 24, topic: 'Scrap and Rework Cost', hook: 'The operation running 14% scrap is not running bad parts. It is running an uncontrolled process. The fix does not require new equipment — it requires documented parameters and a verification protocol.', angle: 'Assumption Challenge', cta: 'Comment with your current scrap rate. I will outline what process controls typically close that gap in operations like yours.' },
  { day: 25, topic: 'Downtime from Mold Issues', hook: 'Flash buildup blocks vents in a predictable number of shots. Ejector pins wear at a calculable rate. Cooling channels scale on a known timeline. Every failure mode has a schedule.', angle: 'Process Breakdown', cta: 'Is your mold PM schedule based on shot counts, calendar intervals, or reactive inspection? The answer predicts your unplanned downtime rate.' },
  { day: 26, topic: 'Poor Part Consistency', hook: 'The dimensional failure at inspection was not caused at inspection. It was caused at the press — in melt temperature drift, pack pressure variation, or cooling time inconsistency that accumulated over the production run.', angle: 'Assumption Challenge', cta: 'What process parameters does your operation monitor in real time on running injection molding jobs?' },
  { day: 27, topic: 'Scaling Inefficiencies', hook: 'Prototype tooling that was "good enough to start" is often the reason a program cannot scale without a mold rebuild. The decision that enabled the prototype prevented the production launch.', angle: 'Operational Risk', cta: 'What tooling specification criteria does your organization use to distinguish prototype-intent from production-intent tooling?' },
  { day: 28, topic: 'Material Waste', hook: 'Resin waste in injection molding is embedded in every cost-per-part calculation — whether tracked or not. The operations that track it spend 10–20% less on material annually.', angle: 'Financial Impact', cta: 'What percentage of your annual resin spend is going to sprues, runners, purging, and startup scrap? If you do not know, that is the answer.' },
  { day: 29, topic: 'Process Cost Leakage', hook: '200–400 hours of productive press time lost per machine annually to process drift. In a 10-press shop, that is 2,000–4,000 hours of capacity consumed by instability — not scheduled production.', angle: 'Operational Risk', cta: 'If you could recover 20% of the process cost leakage in your operation, what would that represent in annual dollars?' },
  { day: 30, topic: 'Tooling Lifecycle Cost', hook: 'The tooling decision is made once. The consequences are paid on every production run for the life of the program. Most tooling approval meetings model the decision cost, not the program cost.', angle: 'Contrarian Take', cta: 'I can show you how to build a 5-year tooling lifecycle cost model for your active programs. Comment "LIFECYCLE" and I will share the framework.' },
]

const REPURPOSING: string[] = [
  'Break the Business Impact section into a Twitter/X thread — injection molding engineers and plant managers engage heavily with specific process cost numbers.',
  'Turn the 30-day calendar into a downloadable PDF lead magnet titled "30 Days of Injection Molding Cost Control Content for Engineering and Operations Teams."',
  'Pull the hook and first paragraph into a YouTube Shorts script — add B-roll of an injection molding press running and defective parts being sorted.',
  'Convert the Post Ideas table into an Instagram carousel ranking the top content angles for operations directors and engineering managers.',
  'Use the hook as a cold outreach subject line for VPs of Manufacturing and Plant Managers at contract molding and OEM programs.',
]

export function generateLinkedIn(inputs: LinkedInInputs, seed: number = 0): LinkedInOutput {
  const v = seed % 3
  const p = inputs.problem

  const hookOptions = HOOKS[p] ?? HOOKS['injection-molding-defects']
  const bodyOptions = BODIES[p] ?? BODIES['injection-molding-defects']
  const postIdeas = POST_IDEAS[p] ?? POST_IDEAS['injection-molding-defects']

  const hook = hookOptions[v] ?? hookOptions[0]
  const body = bodyOptions[v] ?? bodyOptions[0]
  const businessImpact = BUSINESS_IMPACTS[p] ?? BUSINESS_IMPACTS['injection-molding-defects']
  const cta = CTAS[v % CTAS.length]
  const improvements = IMPROVEMENT_SUGGESTIONS[p] ?? IMPROVEMENT_SUGGESTIONS['injection-molding-defects']

  const problemLabel = PROBLEM_LABELS[p] ?? p

  const fullPostText = `${hook}\n\n${body}\n\n${businessImpact}\n\n${cta}`

  const qualityScore = scoreContent(inputs, true, true, true, fullPostText.split(' ').length)

  const calendar: CalendarEntry[] = CALENDAR_ENTRIES.map(entry => ({
    ...entry,
    topic: entry.topic === problemLabel ? `${entry.topic} (Primary)` : entry.topic,
  }))

  return {
    platform: 'linkedin',
    postIdeas,
    fullPost: { hook, body, businessImpact, cta },
    calendar,
    repurposingSuggestions: REPURPOSING.slice(0, 3),
    qualityScore,
    improvementSuggestions: improvements.slice(0, 3),
  }
}
