import type { YouTubeInputs, YouTubeOutput } from '../types'
import { PROBLEM_DATA } from '../lib/companyProfile'
import { scoreContent } from '../lib/scoring'

const TITLES: Record<string, string[][]> = {
  'injection-molding-defects': [
    ["Why Your Injection Molding Operation Has a 12% Defect Rate (It's Not the Machine)", "Sink Marks, Flash, Short Shots: The Process Behind Every Defect", "Injection Molding Defects Are a Process Control Failure"],
    ["Why Documented Parameters Cut Defect Rates by 5x", "The Root Cause Behind Every Recurring Molding Defect", "How Undocumented Processes Create Predictable Defects"],
    ["Injection Molding Defect Cost: The Number Most Plants Never Calculate", "3–5x Higher Defect Rate Without Process Documentation: Here's Why", "How a Process Control System Eliminates the Defects Your QC Team Keeps Finding"],
  ],
  'tooling-failures': [
    ["The $40,000 Mold That Cost $200,000 to Run: The Lifecycle Math", "Why Cheap Injection Molds Fail 3–4x Faster", "Tooling Failures: The Production Stop Nobody Saw Coming"],
    ["$120,000 Per Tooling Failure: What Unplanned Mold Repairs Actually Cost", "Steel Grade, Cooling Design, and the Mold Failure Rate They Determine", "Why the Lowest Tooling Quote Has the Highest Total Cost"],
    ["How to Build a Tooling Lifecycle Cost Model Before the Mold Is Approved", "Mold Failure Modes: Core Damage, Gate Erosion, Parting Line Wear", "The Tooling Decision That Determines Your Next Five Years of Production Cost"],
  ],
  'production-bottlenecks': [
    ["Your Press Is Running. You Are Still Losing 30% of Throughput.", "Cycle Time Inefficiency: The Production Loss Nobody Tracks", "The $250,000 Annual Throughput Gap in a Multi-Press Injection Molding Shop"],
    ["How Cooling Time Optimization Recovers Lost Press Capacity", "The Cycle Time Audit That Pays for Itself in the First Month", "Why Injection Molding Throughput Loss Hides in Plain Sight"],
    ["Gate Placement, Fill Speed, and the Cycle Time Cost of Getting Them Wrong", "The Phantom Press: Throughput Loss That Shows Up as Capacity Shortage", "How to Calculate the Real Cost of Cycle Time Inefficiency in Your Operation"],
  ],
  'scrap-rework-cost': [
    ["8–18% Scrap in Injection Molding: The Process Control Cost", "Why Your Scrap Rate Is a Process Stability Metric, Not a Quality Metric", "$720,000 in Annual Resin Wasted to Scrap — Here's What's Causing It"],
    ["Two Plants, Same Equipment, 11% Scrap Rate Difference: The Variable That Explains It", "How Documented Process Parameters Reduce Scrap from 15% to 3%", "The Real Cost of Injection Molding Scrap: Resin, Press Time, and Rework"],
    ["Scrap Rate vs. Process Control: The Data Most Injection Molding Plants Are Missing", "Why Rework in Injection Molding Is Always a Process Problem", "The SPC Implementation That Cut Scrap by 70% in 12 Months"],
  ],
  'mold-downtime': [
    ["$1,800/Hour When the Press Stops for a Mold Issue: The Real Downtime Cost", "How Mold Failures Are Predictable — and How to Prevent Them", "60–80% More Downtime Without a Mold PM Program"],
    ["The Ejector Pin Failure That Stopped Production for 8 Hours (And How It Was Preventable)", "Flash Buildup, Vent Clogging, Core Wear: The PM Schedule That Prevents Each", "Why Reactive Mold Maintenance Costs 3x More Than Preventive"],
    ["Building a Mold Maintenance Program from Shot Count Data", "How Unplanned Mold Downtime Shows Up in Production Costs — But Not Maintenance Reports", "The PM Schedule That Eliminated Unplanned Mold Stops in a 15-Mold Operation"],
  ],
  'poor-part-consistency': [
    ["Why Your Injection-Molded Parts Are Inconsistent (It's Not the Mold)", "10–25% First-Pass Yield Failure from Process Variation Nobody Traced to the Press", "Part Consistency Is a Process Stability Problem, Not a Quality Department Problem"],
    ["How Melt Temperature Drift Creates Dimensional Failures Your Inspection Misses", "Weight Monitoring at the Press: The Consistency Control Most Plants Are Not Running", "Why Assembly Lines Stop Because of Inconsistent Injection-Molded Parts"],
    ["Closed-Loop Process Control vs. End-of-Run Inspection: The Yield Difference", "The 0.5% Weight Variation Threshold That Predicts Dimensional Failures", "30–50% Higher Assembly Stoppages: The Supplier Process Problem Nobody Tracks Upstream"],
  ],
  'scaling-inefficiencies': [
    ["Why Injection Molding Programs Fail When They Scale", "60–70% of Programs Scaled Without DFM Review Fail at Volume", "$150,000 in Unplanned Engineering Changes: The Scale-Up Cost Nobody Budgets"],
    ["Prototype Tooling vs. Production Tooling: The Failure Rate Difference", "How Defect Rates Increase as Injection Molding Volume Scales", "The DFM Review That Prevents the Most Expensive Scale-Up Mistakes"],
    ["Scale Amplifies What Is Already Broken in Injection Molding Processes", "Why Process Characterization at Scale Is Not Optional", "The Program That Ran Fine at 5,000 Parts and Failed at 50,000"],
  ],
  'material-waste': [
    ["The 8–25% Resin Waste Built Into Every Cold Runner Production Run", "Why Your Resin Spend Keeps Running Above Budget", "Hot Runner Payback in 12–18 Months: The Case Most Plants Have Not Made"],
    ["Sprue, Runner, and Purging Waste: The Material Cost Nobody Tracks by Job", "Gate Design and the Material Efficiency Decision Made Before Production Starts", "$250,000 in Annual Resin Waste That Shows Up as 'Material Cost'"],
    ["Cold Runner vs. Hot Runner: The Resin Efficiency Math at 100,000 Annual Shots", "How to Calculate and Reduce Material Waste in Injection Molding", "Why Your Resin Invoice Includes 15% Waste You Are Not Measuring"],
  ],
  'process-cost-leakage': [
    ["8–15% of Annual Production Value Lost to Invisible Process Inefficiencies", "The Injection Molding Cost That Spans Every Report and Appears on None of Them", "2,000 Hours of Annual Press Capacity Lost to Process Drift in a 10-Press Shop"],
    ["Why the Production Report Shows 96% Uptime and the Cost Report Shows Over Budget", "Cycle Drift, Yield Variation, Untracked Scrap: The Three Process Leakage Sources", "SPC in Injection Molding: 20–40% Quality Cost Reduction in 12 Months"],
    ["How to Identify and Quantify Process Cost Leakage in Your Molding Operation", "The $2.1M Hidden Annual Cost in a 10-Press Injection Molding Shop", "Why Most Plants Cannot Answer 'What Does Process Leakage Cost Us?'"],
  ],
  'tooling-lifecycle-cost': [
    ["Every $1 Saved on Tooling Costs $3–$7 Downstream: The Injection Mold Math", "Total Mold Lifecycle Cost Is 2–4x the Build Cost — Here's Why", "The Tooling Approval Meeting That Did Not Include a Lifecycle Model"],
    ["Why the Cheapest Injection Mold Is Almost Never the Lowest-Cost Mold", "$30,000 Saved at Tooling Approval. $210,000 Paid Over the Program Life.", "Build Cost vs. Lifecycle Cost: The Tooling Decision Frame Most Teams Skip"],
    ["How to Build a Tooling Lifecycle Cost Model for Injection Molds", "Steel Grade, Cooling Design, Ejection Robustness: The Three Lifecycle Cost Variables", "The Mold That Degraded Slowly Until the Production Stop Made It Undeniable"],
  ],
}

const THUMBNAIL_TEXTS: Record<string, string> = {
  'injection-molding-defects': '12% DEFECT RATE|PROCESS CONTROL FAILURE|3–5X HIGHER WITHOUT DOCS',
  'tooling-failures': '$120K PER FAILURE|CHEAPEST MOLD = HIGHEST COST|LIFECYCLE MATH',
  'production-bottlenecks': '30% THROUGHPUT LOSS|PRESS IS RUNNING|CYCLE TIME GAP',
  'scrap-rework-cost': '15% SCRAP RATE|PROCESS STABILITY PROBLEM|$720K ANNUAL WASTE',
  'mold-downtime': '$1,800/HR DOWNTIME|PM PROGRAM DIFFERENCE|60% MORE FAILURES',
  'poor-part-consistency': '25% YIELD FAILURE|STARTS AT THE PRESS|NOT A QUALITY PROBLEM',
  'scaling-inefficiencies': '70% FAIL AT SCALE|$150K UNPLANNED CHANGES|DFM REVIEW COST',
  'material-waste': '25% RESIN WASTED|COLD RUNNER PROBLEM|HOT RUNNER PAYBACK',
  'process-cost-leakage': '15% VALUE LOST|INVISIBLE INEFFICIENCY|2,000 HRS DRIFT/PRESS',
  'tooling-lifecycle-cost': '$3–$7 DOWNSTREAM|CHEAPEST MOLD COST|LIFECYCLE MODEL MISSING',
}

const THREE_SECOND_HOOKS: Record<string, string[]> = {
  'injection-molding-defects': [
    "Your injection molding defect rate is not a quality problem. It is a process control problem — and it has a dollar value compounding on every shift.",
    "Operations without documented process parameters run 3–5x higher defect rates than controlled operations. The equipment is often identical.",
    "A single escaped defect that triggers a field recall costs 10–100x the production value of the entire run. Your inspection system is not the last line of defense. Your process is.",
  ],
  'tooling-failures': [
    "The $40,000 mold that failed in year one cost $200,000 total. The $70,000 mold that ran five years without refurbishment cost $70,000 total. That math is consistent enough to be a rule.",
    "Molds built to the lowest upfront cost fail at 3–4x the rate of properly engineered tooling. The savings evaporate within the first production year.",
    "$15,000 to $120,000 per unplanned tooling failure. 2 to 6 weeks of lost production. This is not a worst-case scenario. It is the documented cost of tooling built without lifecycle engineering.",
  ],
  'production-bottlenecks': [
    "Your press is occupied. Your operators are busy. You are still leaving 30% of your available throughput on the table — because the cycle time was never optimized after qualification.",
    "One press running 15% over target cycle time loses the equivalent of 1–2 production shifts per week. Most operations have never run the cycle time audit that makes this visible.",
    "$80,000 to $250,000 in annual throughput loss across a multi-mold operation from avoidable cycle time inefficiency. The capacity is there. It is just not being accessed.",
  ],
  'scrap-rework-cost': [
    "8–18% scrap in injection molding versus 1–4% in controlled operations. Same equipment. Different process documentation discipline.",
    "The operation running 15% scrap is spending $720,000 per year on resin that does not become product — from a process instability that responds to documentation, not capital investment.",
    "Every percentage point of scrap above your baseline is resin purchased, shot, cooled, ejected, and discarded — on every shift, whether someone is tracking it or not.",
  ],
  'mold-downtime': [
    "$350 to $1,800 per hour of lost throughput during an unplanned mold stop. Flash buildup, vent clogging, and ejector wear each have a predictable schedule. The PM program determines whether that schedule is yours or the mold's.",
    "Operations without mold PM programs experience 60–80% more unplanned downtime than those with structured schedules. The difference is not the molds — it is the maintenance design.",
    "4 to 12 unplanned hours per mold per month without a PM program. On a 15-mold operation, that is 60–180 hours of press capacity absorbed by avoidable failures every month.",
  ],
  'poor-part-consistency': [
    "Assembly lines stop not because the part failed — but because the part is unpredictably variable. Occasional failure is manageable. Unpredictable variation is not.",
    "Part-to-part weight variation above 0.5% is already predicting the dimensional failures your inspection team will find in 48 hours. Most operations are not using this indicator.",
    "10 to 25 percent first-pass yield failure from dimensional variation that started at the press and was not caught until inspection. The inspection table is not where the problem is fixed.",
  ],
  'scaling-inefficiencies': [
    "60 to 70 percent of injection molding programs scaled without DFM review encounter tooling or process failures at production volume — averaging $25,000 to $150,000 in unplanned engineering cost.",
    "Scale amplifies what is already broken. The process instability that was manageable at 5,000 shots per month becomes a defect crisis at 50,000.",
    "Prototype tooling scaled to production volumes fails 2–3x faster than production-intent tooling. The tooling decision made at program launch determines whether the program can scale.",
  ],
  'material-waste': [
    "8 to 25 percent of your resin spend is going to sprues, runners, and purging — not to parts. Most operations are not tracking this waste by job.",
    "Hot runner tooling eliminates sprue and runner waste. On a program above 100,000 annual shots, the tooling premium pays back within 6–18 months. Most qualifying programs are still running cold runners.",
    "Your resin invoice includes 15% material that never became a part. It is in the material cost line — with no label identifying it as waste.",
  ],
  'process-cost-leakage': [
    "8 to 15 percent of annual production value lost to individually invisible process inefficiencies. None of it appears on a single report. Together, it is your most expensive cost category.",
    "200 to 400 hours of productive press time lost per machine annually to process drift — not to downtime, not to changeover. To drift that nobody was monitoring.",
    "The production report shows 96% uptime. The cost report shows 14% over budget. Both are accurate. The explanation is unmonitored process drift.",
  ],
  'tooling-lifecycle-cost': [
    "Every dollar saved at tooling approval costs $3 to $7 in downstream repair, downtime, and scrap over the life of the program. Most procurement decisions are made without that ratio in the analysis.",
    "The total lifecycle cost of an injection mold averages 2 to 4 times the original build cost over five years. The decision was made on the build cost number — without the lifecycle model.",
    "The $30,000 saved at tooling approval generated $150,000 in downstream costs over three years. That calculation is made after the fact on most programs. It should be made before tooling is approved.",
  ],
}

const OPENING_LINES: Record<string, string[]> = {
  'injection-molding-defects': [
    "Every injection molding defect has a mechanism — and every mechanism has a process parameter behind it.",
    "The defect rate in an injection molding operation is not a measure of quality control effectiveness. It is a measure of process documentation discipline.",
    "Operations running 3% defect rates are not using better machines than operations running 15%. They are using documented, validated, and locked process parameters.",
  ],
  'tooling-failures': [
    "The tooling decision is made once. The production cost consequences last for the life of the program.",
    "Premature mold failure is not a manufacturing surprise. It is the predictable output of tooling decisions made without lifecycle cost analysis.",
    "Every mold failure mode — core damage, gate erosion, parting line wear — has a mechanical origin that was visible in the original tooling specification.",
  ],
  'production-bottlenecks': [
    "Injection molding throughput loss is not dramatic. It accumulates — cycle by cycle — across every press running above its optimized cycle time.",
    "The cycle time audit is one of the highest-return activities in injection molding operations management — and it is almost never done on a scheduled basis.",
    "Cooling time, pack time, and injection speed are each individually optimizable. Together, they determine whether a press is running at its designed throughput or significantly below it.",
  ],
  'poor-part-consistency': [
    "Part consistency in injection molding is not determined at inspection. It is determined at the press — in the stability of melt temperature, pack pressure, and cooling time across every shot.",
    "The assembly line that stops because of an inconsistent molded component is not experiencing a quality problem. It is experiencing the downstream cost of an unmonitored upstream process.",
    "Weight variation at the press is the earliest available signal of dimensional instability. Most operations are not using it as a control parameter.",
  ],
  'scrap-rework-cost': [
    "Scrap in injection molding is not waste. It is a process instability tax — and it is payable on every shift, whether the operation tracks it or not.",
    "The scrap rate differential between a controlled and uncontrolled injection molding operation is not random. It is the direct output of whether process parameters are documented, validated, and verified.",
    "An 8% scrap rate does not require new equipment to reduce to 2%. It requires documented process parameters, a structured verification protocol, and a response procedure for parameter drift.",
  ],
  'mold-downtime': [
    "Unplanned mold downtime in injection molding is not random. Every common failure mode has a predictable occurrence rate — based on shot count, material, and operating conditions.",
    "The most expensive mold maintenance event is the one that was not scheduled — because by the time it forces a press stop, the timing is always wrong.",
    "A formal mold PM program is not a maintenance cost. It is a production cost hedge — against a larger unplanned cost that has a known probability of occurrence.",
  ],
  'scaling-inefficiencies': [
    "Scaling an injection molding program is not a production planning exercise. It is a process engineering exercise — and most programs skip the engineering part.",
    "The prototype that worked at 5,000 shots per month was not validated at the conditions required by 50,000. That validation gap is where scale-up failures originate.",
    "DFM review for injection molding is not a design exercise. It is a production launch risk exercise — and the most expensive design changes are the ones discovered after tooling is committed.",
  ],
  'material-waste': [
    "The resin on a monthly purchase order is not the resin that went into parts. It is the resin that went into parts plus the waste that the process consumed without producing output.",
    "Material waste in injection molding is decided at the tooling design stage — before the first shot is run, before the first purchase order is placed.",
    "Hot runner tooling eliminates sprue and runner waste. Cold runner tooling embeds it in every production cost — as material, not as waste, because nobody is tracking it that way.",
  ],
  'process-cost-leakage': [
    "Process cost leakage in injection molding is not one large problem. It is an accumulation of small ones — each individually invisible, together consuming a significant percentage of annual production value.",
    "The production efficiency report does not show the process cost leakage number — because process cost leakage is not one number. It is the sum of scrap, yield loss, cycle drift, and resin overage, spread across every report in the operation.",
    "Closed-loop process monitoring in injection molding does not find new problems. It makes existing ones visible — and visible problems are fixable.",
  ],
  'tooling-lifecycle-cost': [
    "The tooling approval meeting almost always evaluates build cost. It almost never evaluates lifecycle cost. That omission determines the cost structure of the production program for the next five years.",
    "The mold that was $30,000 less expensive to build is not a $30,000 decision. It is a five-year production cost decision — and the savings are typically eliminated within the first two years.",
    "Every dollar of tooling cost reduction that comes from steel specification, cooling circuit design, or venting adequacy is a cost that will be paid again — in repair, in downtime, and in scrap — with interest.",
  ],
}

const SCRIPT_OUTLINES: Record<string, string[]> = {
  'injection-molding-defects': [
    `PROBLEM (0:00–0:20): Show the scenario — a quality technician pulling parts from the reject bin, a supervisor reviewing a defect report. The defects are recurring. The root cause is unknown.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['injection-molding-defects'].stat1}. For an operation producing 300,000 parts per month at 10% defect rate, that is 30,000 defective parts — representing $45,000 in direct production cost per month with no saleable output.\n\nMISTAKE (0:40–1:00): ${PROBLEM_DATA['injection-molding-defects'].stat3}. The process runs on tribal knowledge — whatever settings the last technician used, whatever adjustments were made during the last run. Without documented parameters, every shift is a new experiment.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['injection-molding-defects'].stat2}. Document, validate, and lock process parameters at first article qualification. Build a structured response protocol for when parameters drift. The operations running 1–4% defect rates are running this discipline — not better equipment.\n\nTAKEAWAY (1:20–1:30): The defect rate is not a quality metric. It is a process control metric. And it responds to process control — not capital investment.`,
    `PROBLEM (0:00–0:25): An injection molding operation with a recurring sink mark problem. Three different operators. Three different approaches to fixing it. The defect rate varies from 4% to 18% depending on who is running the press.\n\nCOST (0:25–0:50): ${PROBLEM_DATA['injection-molding-defects'].stat1}. At 18% defect rate on a 250,000-part monthly run, that is 45,000 rejected parts — and the variation between operators proves the problem is the process, not the machine.\n\nMISTAKE (0:50–1:10): ${PROBLEM_DATA['injection-molding-defects'].stat3}. Three operators produced three defect rates because there were no documented parameters. Each was solving the problem based on their experience — and each arrived at a different answer.\n\nFIX (1:10–1:25): One documented process specification. Validated at first article. Locked before production. Verified at shift start. ${PROBLEM_DATA['injection-molding-defects'].stat2}. The escaped defect risk goes to near-zero when the process is controlled, because the conditions that create defects are no longer present.\n\nTAKEAWAY (1:25–1:30): If defect rate varies by operator, the process is not documented. That is the diagnosis — and the fix is a documentation discipline, not a personnel one.`,
    `PROBLEM (0:00–0:20): A field return. Warped parts in an automotive assembly application. The warping appeared in parts from one specific production run. The press, the mold, and the material are unchanged. What caused it?\n\nCOST (0:20–0:45): ${PROBLEM_DATA['injection-molding-defects'].stat2}. A field return on a safety-critical automotive component triggers inspection of every part in the field, recall notification, and supplier corrective action. The production run was worth $40,000. The recall cost is $400,000.\n\nMISTAKE (0:45–1:05): The cooling time had been shortened by 1.2 seconds during the run — a technician adjustment to speed up output after a slow startup. No documentation. No change record. No process alert. The adjustment caused residual stress. The parts looked good at inspection.\n\nFIX (1:05–1:25): ${PROBLEM_DATA['injection-molding-defects'].stat3}. Locked, documented parameters with change control requirements prevent the undocumented adjustment. If a parameter change is needed, it goes through a review process — and its impact is validated before production continues.\n\nTAKEAWAY (1:25–1:30): The most expensive defect is the one that escapes to the field. The process control that prevents it is cheap by comparison.`,
  ],
  'tooling-failures': [
    `PROBLEM (0:00–0:20): A production program running $180,000 per month in output. The primary mold — built 14 months ago at $48,000 — fails. Core damage. Estimated repair time: 4 weeks. Repair cost: $22,000.\n\nCOST (0:20–0:45): ${PROBLEM_DATA['tooling-failures'].stat3}. The 4-week production gap is $720,000 in missed output. The emergency sourcing to fill partial customer orders adds $35,000. The repair is $22,000. Total event cost: $777,000 — from a tooling shortcut that saved $22,000 at approval.\n\nMISTAKE (0:45–1:05): ${PROBLEM_DATA['tooling-failures'].stat2}. The $48,000 mold was built to P20 pre-hardened steel where H13 hardened steel was required for this material and production volume. The decision was made on build cost. The failure rate consequence was not in the analysis.\n\nFIX (1:05–1:25): ${PROBLEM_DATA['tooling-failures'].stat1}. Lifecycle cost modeling before tooling approval compares two-year total cost — including projected repair frequency, downtime cost, and production loss — not just build cost. The $70,000 properly specified mold had a 5-year total lifecycle cost of $95,000. The $48,000 mold had a 2-year cost of $130,000.\n\nTAKEAWAY (1:25–1:30): Tooling is not a build cost decision. It is a program cost decision. Model it that way before the PO is signed.`,
    `PROBLEM (0:00–0:25): Two tooling quotes for the same injection-molded part. Vendor A: $65,000. Vendor B: $42,000. The project manager selects Vendor B. The mold delivers in 10 weeks.\n\nCOST (0:25–0:50): 18 months into production, Vendor B's mold develops gate erosion and dimensional drift. ${PROBLEM_DATA['tooling-failures'].stat2}. Repair: $28,000. Downtime: 3 weeks. Production gap cost: $540,000 on a $180,000/month program. The $23,000 saved at tooling approval generated a $568,000 downstream cost within 18 months.\n\nMISTAKE (0:50–1:10): ${PROBLEM_DATA['tooling-failures'].stat2}. The Vendor B mold used standard steel without hardening treatment appropriate for the material being run. The gate geometry was designed for minimum machining time, not for longevity at production volumes. Both decisions were invisible in the quote — and neither was asked about during vendor selection.\n\nFIX (1:10–1:25): The tooling specification questions that surface lifecycle engineering: What steel specification and hardness treatment? What cooling circuit design for this cycle time target? What venting design for this material and wall thickness? These questions separate lifecycle-engineered tooling from build-cost-optimized tooling.\n\nTAKEAWAY (1:25–1:30): The tooling quote comparison should be a lifecycle cost comparison — not a build cost comparison. The data required for that comparison is available from the toolmaker before the PO is signed.`,
    `PROBLEM (0:00–0:20): A mold degrading over 24 months of production. Flash increasing at the parting line. Dimensional measurements drifting toward the upper tolerance limit. Ejector pins sticking intermittently.\n\nCOST (0:20–0:40): None of these symptoms triggered a maintenance event. Each was within the tolerance band — until it was not. The sudden full failure: cracked core. ${PROBLEM_DATA['tooling-failures'].stat3}. Full refurbishment: $85,000. Production gap: 5 weeks.\n\nMISTAKE (0:40–1:00): ${PROBLEM_DATA['tooling-failures'].stat1}. The degradation was predictable from the maintenance log — increasing flash measurements at 50,000-shot intervals, dimensional drift trend documented in QC records. The data was collected. It was not connected to a maintenance trigger.\n\nFIX (1:00–1:20): Mold performance monitoring tied to a preventive maintenance decision model — flash at parting line above threshold triggers inspection, dimensional drift above trend threshold triggers preventive repair. Intervention before failure costs a fraction of refurbishment after failure.\n\nTAKEAWAY (1:20–1:30): Mold failure is almost never sudden. It is the end of a degradation curve that was visible in the data. Connect the data to maintenance decisions and the sudden failure stops occurring.`,
  ],
  'production-bottlenecks': [
    `PROBLEM (0:00–0:20): A 10-press injection molding operation scheduled for 120,000 parts per shift. Actual output: 94,000. Production management cannot identify a single root cause — no downtime, no quality holds, no material issues.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['production-bottlenecks'].stat3}. The 22% throughput gap is distributed across all 10 presses — each running 2–3 seconds above optimized cycle time. No single press is the problem. Every press is the problem. The combined annual throughput loss exceeds $180,000 in unmet capacity.\n\nMISTAKE (0:40–1:00): ${PROBLEM_DATA['production-bottlenecks'].stat1}. Cycle times were set at qualification and never revisited. Cooling time was set conservatively to prevent warping during first article — and never optimized after the process stabilized. Pack time was extended to address a short-shot concern that was resolved two production years ago. Each individual decision was reasonable. Together, they created a 20–25% cycle time gap.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['production-bottlenecks'].stat2}. A cycle time audit — comparing actual running cycle time to theoretically optimized cycle time using mold flow data and cooling analysis — identifies the gap on every active mold. Recovery of 20% cycle time efficiency across 10 presses is the equivalent of adding two presses without capital investment.\n\nTAKEAWAY (1:20–1:30): The capacity shortfall that triggers a capital conversation may already exist in the cycle time gap on running production. Audit before you invest.`,
    `PROBLEM (0:00–0:25): A production launch for a new program. The press is running. The mold is qualified. The output is 18% below the target rate needed to meet customer delivery requirements.\n\nCOST (0:25–0:50): ${PROBLEM_DATA['production-bottlenecks'].stat2}. At 18% below target, the operation needs to run additional shifts to meet delivery — adding $38,000 per month in overtime labor and overhead. Over the first production year, that overtime cost exceeds the cycle time optimization investment by 6x.\n\nMISTAKE (0:50–1:10): The mold flow analysis was run during design. The cycle time target was set from that analysis. But the cooling circuit delivered less efficiency than modeled, the gate balance was off by 8%, and the pack pressure required to fill all cavities was higher than predicted — each adding cycle time.\n\nFIX (1:10–1:25): ${PROBLEM_DATA['production-bottlenecks'].stat1}. A post-qualification cycle time optimization study — measuring actual cooling efficiency, gate balance, and fill pressure against design targets — identifies where the cycle time is being lost and what interventions close the gap. In this case: cooling circuit modification recovered 12% of cycle time, gate balance adjustment recovered 6%.\n\nTAKEAWAY (1:25–1:30): The cycle time target set at design is a prediction. The cycle time achievable in production is measured. The gap between them is recoverable — with the right analysis.`,
    `PROBLEM (0:00–0:20): An injection molding manager evaluating a capacity expansion. The plan: purchase two additional presses. The question: is the capacity gap real, or is it a cycle time efficiency gap?\n\nCOST (0:20–0:40): ${PROBLEM_DATA['production-bottlenecks'].stat3}. Before capital authorization, a cycle time audit was run across all active molds. Finding: the existing 8-press operation was running 23% below optimized cycle time across the mold portfolio. The "capacity gap" was a process efficiency gap — recoverable without additional equipment.\n\nMISTAKE (0:40–1:00): The production planning model used actual running cycle times — not optimized cycle times — to calculate available capacity. The result was a capacity projection that understated available throughput by 23%. The capital plan was built on a process inefficiency, not a genuine capacity constraint.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['production-bottlenecks'].stat1}. Cycle time optimization recovered capacity equivalent to 1.8 additional presses from the existing 8 — without capital investment. The expansion was deferred 18 months while the efficiency gains were captured. Capital was eventually authorized — for a single press, not two.\n\nTAKEAWAY (1:20–1:30): Before any capital authorization for capacity expansion, run a cycle time audit. The capacity may already exist in the efficiency gap on running production.`,
  ],
  'scrap-rework-cost': [
    `PROBLEM (0:00–0:20): Two injection molding plants. Same press tonnage. Same resin supplier. Same part design. Plant A: 3.2% scrap rate. Plant B: 16.4% scrap rate. The operations manager at Plant B cannot explain the gap.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['scrap-rework-cost'].stat1}. On a $400,000 monthly resin spend, the 13.2-point scrap gap represents $52,800 per month in resin purchasing no saleable output — $633,600 annually. ${PROBLEM_DATA['scrap-rework-cost'].stat2}. Rework labor on marginal parts adds another $80,000 per year.\n\nMISTAKE (0:40–1:00): Plant A documented process parameters at first article qualification, validated them at production launch, and runs monthly process verification audits. Plant B relies on experienced operators to run "good" settings from memory. Shift to shift, the settings drift — and the scrap rate follows.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['scrap-rework-cost'].stat3}. Process documentation does not require new equipment. It requires a first article process spec, a production verification protocol, and a response procedure for out-of-spec parameters. Plant B implemented this framework. Scrap rate dropped from 16.4% to 4.1% in eight months.\n\nTAKEAWAY (1:20–1:30): The scrap rate gap is a process documentation gap. The documentation costs less than one month of the scrap differential.`,
    `PROBLEM (0:00–0:25): An injection molding program running 22 million parts annually. Scrap rate: 11%. Annual resin spend: $1.8M. The cost of that scrap rate: $198,000 in wasted resin per year — before rework labor, before press time, before overhead allocation.\n\nCOST (0:25–0:50): ${PROBLEM_DATA['scrap-rework-cost'].stat3}. The 11% scrap operation is consuming 12–22% more resin than the process requires. At $1.8M annual spend, that excess is $216,000–$396,000 in material purchased and not converted to product. ${PROBLEM_DATA['scrap-rework-cost'].stat2}. Rework on marginal parts adds additional direct labor cost on top of the material waste.\n\nMISTAKE (0:50–1:10): The scrap was categorized as "normal process variation" — an acceptable cost of doing business at this volume. It was never analyzed by failure mode. When it was, the analysis showed 67% of scrap traced to three root causes, each addressable with process parameter adjustments that required no tooling change.\n\nFIX (1:10–1:25): ${PROBLEM_DATA['scrap-rework-cost'].stat1}. Failure mode analysis of the scrap stream, followed by process parameter optimization for the three primary defect types, reduced scrap from 11% to 3.8% in four months — saving $131,000 in annual resin cost and eliminating 87% of the rework volume.\n\nTAKEAWAY (1:25–1:30): Scrap analysis by failure mode is the diagnostic that points to the process adjustment. Without that analysis, scrap is managed by acceptance — not by elimination.`,
    `PROBLEM (0:00–0:20): A production run of 500,000 parts. Quality hold at the end of the run. 62,000 parts rejected. Root cause: marginal wall thickness on one side of the cavity from a pack pressure setting that drifted during the second production shift.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['scrap-rework-cost'].stat2}. 62,000 parts at $0.85 each: $52,700 in scrapped production cost. Rework on the 18,000 parts that were marginally acceptable but not rejectable: $22,500 in secondary labor. Total event cost: $75,200 from a pack pressure drift that no monitoring system caught.\n\nMISTAKE (0:40–1:00): Pack pressure was set at shift start and not monitored during the run. The drift — 180 psi over 6 hours — was within the range that does not trigger a machine alarm. The parts produced during drift look acceptable to visual inspection. The dimensional failure appears at final gauge check.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['scrap-rework-cost'].stat1}. In-process weight monitoring — at a 0.5% variation threshold — would have flagged the pack pressure drift within the first hour of shift two. The 62,000-part quality hold becomes a 4,000-part process correction event. The cost difference: $75,200 versus $3,400.\n\nTAKEAWAY (1:20–1:30): The monitoring system that catches drift early costs less than one quality hold of the type it prevents.`,
  ],
  'mold-downtime': [
    `PROBLEM (0:00–0:20): A 15-mold injection molding operation. Tuesday, 11:45 PM. Press 7 stops. Ejector pin failure. The mold runs a component for an automotive assembly with Monday delivery. The repair shop opens at 7 AM.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['mold-downtime'].stat2}. 7.5 hours of downtime at $1,400/hour on this press: $10,500 in lost throughput before the repair shop opens. Repair cost: $4,200. Expedited shipping to meet Monday delivery: $2,800. Total event cost: $17,500. The ejector pin failure was not random.\n\nMISTAKE (0:40–1:00): ${PROBLEM_DATA['mold-downtime'].stat3}. The mold had run 285,000 shots since the last ejector system inspection. The PM interval for this mold type at this production rate was 200,000 shots. The inspection was overdue by 42.5% — documented in the shot count log, but not connected to a maintenance trigger.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['mold-downtime'].stat1}. A shot-count-based PM schedule with automated trigger alerts. At 180,000 shots, the mold is flagged for inspection. The ejector pin wear is measured. If within spec, the interval is extended. If approaching tolerance, preventive replacement is scheduled during the next planned changeover — not at 11:45 PM on a Monday-delivery program.\n\nTAKEAWAY (1:20–1:30): The failure was scheduled — by the maintenance system that did not exist. Build the schedule before the mold builds one for you.`,
    `PROBLEM (0:00–0:25): An injection molding manager comparing maintenance costs across two similar facilities. Facility A: $280,000 annual maintenance spend on 18 molds. Facility B: $410,000. Facility B also has 40% more unplanned downtime events.\n\nCOST (0:25–0:50): ${PROBLEM_DATA['mold-downtime'].stat3}. Facility B is spending more on maintenance AND experiencing more unplanned downtime. The maintenance spend is reactive — driven by emergency repairs, expedited parts, and after-hours labor. Facility A's lower spend is structured — driven by preventive inspections, planned replacements, and scheduled maintenance windows.\n\nMISTAKE (0:50–1:10): Facility B never built a shot-count-based PM program. Maintenance was triggered by failures — which always occurred during production, always required emergency response, and always cost more than planned maintenance would have.\n\nFIX (1:10–1:25): ${PROBLEM_DATA['mold-downtime'].stat2}. At $1,400/hour average throughput value and 40 more unplanned downtime events per year at average 6 hours each, Facility B absorbed $336,000 in downtime costs annually — on top of the $130,000 premium in reactive maintenance spend. Facility A's structured PM program cost less and produced less downtime.\n\nTAKEAWAY (1:25–1:30): Reactive maintenance is not cheaper. It is more expensive and less predictable. The PM program pays back before the next unplanned failure it prevents.`,
    `PROBLEM (0:00–0:20): Flash buildup on a high-cycle mold. It starts as an occasional quality flag. Within 200,000 shots, it is a consistent dimensional failure. Within 400,000 shots, it has caused vent damage requiring a $35,000 repair.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['mold-downtime'].stat1}. Each unplanned stop to address flash accumulation costs 3–5 hours of production. At 8 events over the degradation cycle: 24–40 hours of press downtime. At $900/hour: $21,600–$36,000 in throughput loss before the repair cost is added.\n\nMISTAKE (0:40–1:00): Flash buildup is predictable from material type, cavity pressure, and cycle rate. For this mold and material combination, vent cleaning was required every 80,000 shots. The PM schedule had the mold flagged every 150,000 shots. The interval was wrong — not because nobody knew the right interval, but because no one had calculated it from the process parameters.\n\nFIX (1:00–1:20): PM interval calculation from process parameters: material viscosity, cavity pressure, vent depth, and cycle rate. For this mold: 75,000-shot cleaning interval based on the calculation. Cost of one cleaning event: $380. Annual cleaning cost at correct interval: $1,900. Annual unplanned downtime cost before the PM program: $28,800.\n\nTAKEAWAY (1:20–1:30): The PM interval is not a guess. It is a calculation. Run the calculation from the process parameters and the downtime becomes a maintenance cost — not a production crisis.`,
  ],
  'poor-part-consistency': [
    `PROBLEM (0:00–0:20): An OEM assembly line. 30–50% higher stoppage rate than planned. Root cause traced to injection-molded sub-components from a supplier running without process monitoring. The parts pass first-article inspection. They fail at the assembly station — inconsistently.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['poor-part-consistency'].stat3}. At a line rate of $12,000/hour and a 30% higher stoppage rate, the assembly line is absorbing $3,600/hour in additional downtime cost — from a supplier process instability that never appears on a quality rejection report because the parts pass inspection.\n\nMISTAKE (0:40–1:00): ${PROBLEM_DATA['poor-part-consistency'].stat2}. Part-to-part weight variation at the supplier was running at 0.8%. Above the 0.5% stability threshold. The weight data existed in the supplier's process logs — but no alert threshold was set, no customer visibility into the data existed, and no corrective action was triggered.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['poor-part-consistency'].stat1}. A real-time weight monitoring protocol at the press — with a 0.4% variation trigger for operator review and a 0.6% trigger for process adjustment — catches the drift before it becomes a dimensional failure that reaches the assembly line. The supplier implemented this. Assembly stoppages dropped 62% within 30 days.\n\nTAKEAWAY (1:20–1:30): The assembly line problem was a molding process problem. The data to see it was at the press. The monitoring system that connected the data to an action was missing.`,
    `PROBLEM (0:00–0:25): A 16-cavity injection mold. Cavity-to-cavity weight variation: 1.2%. Some cavities producing parts within nominal. Others consistently at the high side of the tolerance band. The mold passes capability studies. The assembly operation keeps failing.\n\nCOST (0:25–0:50): ${PROBLEM_DATA['poor-part-consistency'].stat1}. The parts that fail at assembly are not the parts that fail at the supplier's inspection. They are the parts that are dimensionally acceptable individually — but inconsistent relative to each other in assembly clearances that require matched component tolerances. The yield failure is at the assembly level, not the part level.\n\nMISTAKE (0:50–1:10): The cavity imbalance — causing higher shear and different fill dynamics between inside and outside cavities — was addressable with a gate balance adjustment and runner modification. The problem was known. The correction was deferred because the parts were "passing inspection."\n\nFIX (1:10–1:25): ${PROBLEM_DATA['poor-part-consistency'].stat2}. Cavity-level weight monitoring catches imbalance at the press — in real time, before any assembly failure occurs. Gate balance correction, validated with cavity-level weight data, reduced weight variation from 1.2% to 0.2%. Assembly yield failure rate: from 18% to 2%.\n\nTAKEAWAY (1:25–1:30): Parts that pass inspection can still fail assembly. Consistency is the standard that matters — and it is measured at the process level, not the part level.`,
    `PROBLEM (0:00–0:20): Melt temperature varies 8°C between shots. Pack pressure drifts 180 psi over a 4-hour run. Cooling time creeps 1.5 seconds by end of shift. None of these trigger a machine alarm. Together, they produce a first-pass yield failure rate of 22%.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['poor-part-consistency'].stat1}. 22% yield failure on a 400,000-part monthly run: 88,000 parts produced with no saleable output. At $0.65 per part: $57,200 in monthly production cost with zero return. Plus rework labor on the parts recoverable through secondary operations.\n\nMISTAKE (0:40–1:00): No closed-loop process monitoring. The process parameters were set at shift start and assumed to be stable for the duration of the run. The 8°C melt variation, 180 psi pack drift, and 1.5-second cooling creep were each within individual machine alarm tolerances — but collectively producing an unstable process.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['poor-part-consistency'].stat2}. Part weight monitoring at 15-minute intervals — as a surrogate for process stability — flags the cumulative drift before it becomes a dimensional failure event. When weight variation exceeds 0.4%, the process is audited. In this operation, weight monitoring reduced the 22% yield failure rate to 3.8% in six months.\n\nTAKEAWAY (1:20–1:30): Individual parameters within alarm tolerance can collectively produce an unstable process. Weight monitoring integrates all process variation into a single trackable signal.`,
  ],
  'scaling-inefficiencies': [
    `PROBLEM (0:00–0:20): A product development team ready to launch production. Prototype tooling has run 50,000 shots successfully. Customer purchase order: 600,000 units in year one. The scale-up begins.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['scaling-inefficiencies'].stat1}. Six weeks into full-rate production, defect rate spikes from 3% to 19%. The prototype tool cannot maintain dimensional control at the production cycle time required to hit the volume target. Emergency DFM review identifies three design changes required for production viability. Engineering changes: $85,000. 8-week tooling rebuild lead time.\n\nMISTAKE (0:40–1:00): ${PROBLEM_DATA['scaling-inefficiencies'].stat2}. The prototype tool was designed for low-volume validation — not for the cycle time, fill pressure, and cooling requirements of production volume. At 50,000 shots per year, the tool performed. At 600,000 shots per year, it could not sustain the process conditions required.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['scaling-inefficiencies'].stat3}. A pre-production DFM review — evaluating tool specification against production volume requirements, cycle time targets, and process window adequacy — catches these failures before tooling is committed. On this program, the DFM review would have cost $8,000 and identified all three design issues before the $85,000 engineering change and 8-week delay.\n\nTAKEAWAY (1:20–1:30): The DFM review is not overhead. It is the diagnostic that prevents the most expensive design changes — the ones discovered after tooling is committed and production has already launched.`,
    `PROBLEM (0:00–0:25): A program scaling from 8,000 parts per month to 80,000. Process parameters validated at low volume. Production launch at target volume: defect rate 3.8x higher than qualification data.\n\nCOST (0:25–0:50): ${PROBLEM_DATA['scaling-inefficiencies'].stat3}. The 3.8x defect rate increase at scale is the documented output of a process validated at conditions that do not transfer to production volume. At 80,000 monthly parts and 22% defect rate: 17,600 defective parts per month. Customer delivery requirements not met for 3 consecutive months while the process is re-characterized.\n\nMISTAKE (0:50–1:10): ${PROBLEM_DATA['scaling-inefficiencies'].stat1}. No process characterization study was run at production conditions before the scale-up launch. The qualification data came from low-volume runs where thermal equilibrium was different, fill pressure was lower, and cycle time variation was negligible. None of those conditions transferred to 80,000 shots per month.\n\nFIX (1:10–1:25): Process window development at production conditions — characterizing the acceptable ranges of melt temperature, fill speed, pack pressure, and cooling time at full production rate — before the launch. A design of experiments at target volume conditions identifies the process window that maintains quality at scale.\n\nTAKEAWAY (1:25–1:30): The process that works at 10% of production volume has not been validated. It has been run successfully at low risk. Validation requires characterization at the conditions that production will actually impose.`,
    `PROBLEM (0:00–0:20): Three programs failed their first production quarter after scaling from prototype. All three had successful prototype runs. All three had approved first-article inspection reports. All three hit defect rates above 15% within the first 60 days of production launch.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['scaling-inefficiencies'].stat1}. Across the three programs: $180,000 in unplanned engineering costs, 14 weeks of combined delay to first customer delivery, and three emergency tooling modifications. Total scale-up failure cost: $290,000. DFM review for all three programs combined would have cost $18,000.\n\nMISTAKE (0:40–1:00): Each program was qualified using prototype tooling and validated at low volume. The scale-up assumption: if it works at prototype, it works at production. That assumption fails when the tooling, the process window, and the production conditions were not designed for production requirements.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['scaling-inefficiencies'].stat2}. Production-intent tooling — specified for the steel, cooling, venting, and ejection requirements of production volume — eliminates the tooling failure mode at scale. Process window development at production conditions eliminates the process failure mode. These are two separate engineering steps, each required before production launch.\n\nTAKEAWAY (1:20–1:30): Scale-up is not a production planning event. It is a process engineering event. The programs that fail at scale skipped the engineering.`,
  ],
  'material-waste': [
    `PROBLEM (0:00–0:20): An injection molding operation with $1.2M in annual resin spend. Material cost running 18% above the process-theoretic requirement. The gap is not in part geometry, not in material pricing, not in resin quality — it is in process design decisions made two years ago.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['material-waste'].stat1}. At 18% material waste on $1.2M annual spend: $216,000 in resin purchased annually without converting to product. ${PROBLEM_DATA['material-waste'].stat2}. Purging costs add another $28,000 per year — tracked nowhere in the production cost accounting.\n\nMISTAKE (0:40–1:00): All primary molds in the operation run cold runner systems. Hot runner technology was considered at tooling approval and rejected as "too expensive." At current production volume — 140,000 shots annually on the highest-volume program — hot runner tooling would pay back within 11 months.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['material-waste'].stat3}. Hot runner conversion on the three highest-volume programs eliminates sprue and runner waste on those programs — reducing annual material waste from 18% to 6%. The investment pays back in 14 months. Annual savings after payback: $144,000 in resin cost reduction.\n\nTAKEAWAY (1:20–1:30): The hot runner vs. cold runner decision is a material cost decision embedded in a tooling cost conversation. Run the material cost calculation at the tooling approval meeting — not two years later when the waste has already accumulated.`,
    `PROBLEM (0:00–0:25): Two identical injection molding programs. Same part, same material, same annual volume. Program A: cold runner tooling, 14% material waste. Program B: hot runner tooling, 3% material waste.\n\nCOST (0:25–0:50): ${PROBLEM_DATA['material-waste'].stat1}. On $400,000 annual resin spend, the 11-point waste gap is $44,000 in material per year. ${PROBLEM_DATA['material-waste'].stat3}. The hot runner premium on Program B tooling: $22,000 over the cold runner equivalent. Payback period: 6 months. Year-3 cumulative savings advantage of Program B over Program A: $110,000.\n\nMISTAKE (0:50–1:10): Program A was tooled with cold runners because the upfront cost analysis stopped at tooling build cost. The material efficiency difference — and its annual cost impact — was not part of the tooling decision framework. The $22,000 tooling premium that would have paid back in 6 months was rejected to save 5.5% on tooling cost.\n\nFIX (1:10–1:25): ${PROBLEM_DATA['material-waste'].stat2}. Material efficiency analysis at tooling approval: calculate annual resin waste in dollars for each tooling option, model the payback period for the hot runner premium, include the result in the tooling cost comparison. The decision changes when the 5-year cost is in the comparison rather than the build cost alone.\n\nTAKEAWAY (1:25–1:30): Material waste is a tooling cost decision — made once, paid annually. Include the material cost in the tooling decision.`,
    `PROBLEM (0:00–0:20): A plant manager reviewing monthly resin variances. The resin spend is consistently 12–16% above the process-theoretic cost. No single job shows an obvious waste driver. The variance is distributed — across purging, startup scrap, and runner waste — with no job-level tracking.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['material-waste'].stat1}. $800,000 annual resin spend at 14% waste: $112,000 per year in purchased material not converted to product. The waste is real. The reporting system does not show it — because purging is recorded as a process cost, startup scrap is in the scrap bin, and runner waste is in the regrind bin.\n\nMISTAKE (0:40–1:00): No job-level material tracking. Resin is purchased in bulk, issued to the floor, and reconciled at the end of the month against finished goods inventory. The waste between issue and inventory is the reconciling item — with no breakdown by type or source.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['material-waste'].stat2}. Job-level material tracking: resin issued to each job, product yield at end of job, waste categorized by type (runner, purge, startup scrap). Tracking makes the waste visible. Visible waste has a root cause. Root causes are addressable.\n\nTAKEAWAY (1:20–1:30): Material waste does not become controllable until it becomes measurable. The first step is not process improvement — it is tracking.`,
  ],
  'process-cost-leakage': [
    `PROBLEM (0:00–0:20): An injection molding operation with $6M in annual revenue. Uptime: 94%. Quality rejection rate: 4.2%. Resin budget: 11% over. Overtime: 18% above plan. None of these variances are large enough individually to trigger a corrective action — but together, they represent $780,000 in annual cost above the efficient baseline.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['process-cost-leakage'].stat1}. 11% of annual revenue in individually invisible inefficiencies. Cycle time drift. Shot weight variation. Pack pressure inconsistency. Each within acceptable ranges individually — together, producing a process that costs 13% more than it should.\n\nMISTAKE (0:40–1:00): ${PROBLEM_DATA['process-cost-leakage'].stat2}. 280 hours of productive press time lost per machine annually to process drift — without triggering a single alarm, a single downtime record, or a single quality hold. The loss is distributed across thousands of slightly-off shots, running continuously.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['process-cost-leakage'].stat3}. SPC implementation on critical process parameters — melt temperature, pack pressure, cooling time, shot weight — makes the drift visible before it accumulates to cost. The 20–40% reduction in quality-related cost from SPC is documented across injection molding implementations. The monitoring investment is a fraction of the leakage it eliminates.\n\nTAKEAWAY (1:20–1:30): The most expensive cost in this operation is the one nobody is tracking. SPC makes it trackable — and trackable costs are reducible.`,
    `PROBLEM (0:00–0:25): A production efficiency review. Press utilization: 91%. OEE: 74%. The 17-point gap between utilization and OEE is the process cost leakage — and it is not showing up anywhere as a recoverable cost.\n\nCOST (0:25–0:50): ${PROBLEM_DATA['process-cost-leakage'].stat2}. In a 10-press operation with an average of 310 hours of annual press time lost to process drift per machine: 3,100 hours of production capacity consumed annually. At $700/hour average press cost: $2.17M in capacity absorbed by unmonitored process instability — not by downtime, not by changeover, by drift.\n\nMISTAKE (0:50–1:10): The OEE measurement captures the output. The management system has no mechanism for attributing the OEE gap to a specific cause. Without cause attribution, there is no root cause — and without root cause, there is no corrective action. The 74% OEE is accepted as a performance characteristic rather than investigated as a recoverable cost.\n\nFIX (1:10–1:25): ${PROBLEM_DATA['process-cost-leakage'].stat3}. SPC with cause attribution: when a process parameter drifts, the monitoring system records the drift event, its duration, the affected output, and the quality consequence. The data builds a root cause profile that directs corrective action — and eliminates the drift events that account for most of the OEE gap.\n\nTAKEAWAY (1:25–1:30): OEE without cause attribution is a performance report. OEE with cause attribution is a corrective action roadmap.`,
    `PROBLEM (0:00–0:20): Three injection molding operations, similar size and product mix, different process monitoring approaches. Operation A: no real-time monitoring. Operation B: alarm-based monitoring on critical parameters. Operation C: SPC with trend tracking and drift alerts.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['process-cost-leakage'].stat1}. Operation A: 14% of annual production value in process cost leakage. Operation B: 9%. Operation C: 4%. The process monitoring approach is the primary differentiator — not equipment age, not operator skill, not part complexity.\n\nMISTAKE (0:40–1:00): Operation A's management team measures quality by end-of-run inspection and monitors cost by monthly variance report. Neither catches process drift in real time. By the time the variance report flags the resin overage, the overtime variance, and the yield shortfall — the drift has already run for weeks.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['process-cost-leakage'].stat3}. The 10-point cost leakage difference between Operation A and Operation C is a monitoring system difference. Operation C does not have better molds, better material, or better operators. It has a system that catches and corrects drift before it accumulates to cost.\n\nTAKEAWAY (1:20–1:30): Process cost leakage is not a cost problem. It is an information problem. The operation with better process information has a lower cost structure — automatically.`,
  ],
  'tooling-lifecycle-cost': [
    `PROBLEM (0:00–0:20): A procurement team approves a mold at $52,000 — $18,000 less than a competing quote from a different toolmaker. 16 months into production, the mold requires refurbishment. Cost: $38,000. 4-week lead time for the refurbishment.\n\nCOST (0:20–0:40): ${PROBLEM_DATA['tooling-lifecycle-cost'].stat1}. The 16-month refurbishment on a mold expected to run 5 years represents a total year-one cost of $90,000 ($52,000 build + $38,000 repair). The competing $70,000 quote, with proper steel specification, was projected to run without refurbishment for 36 months. Year-one cost comparison: $90,000 vs. $70,000. The "cheaper" mold cost more before its second birthday.\n\nMISTAKE (0:40–1:00): ${PROBLEM_DATA['tooling-lifecycle-cost'].stat3}. The tooling approval meeting evaluated build cost. The $18,000 savings was real. The refurbishment frequency projection — based on steel specification, hardness, and volume requirements — was never modeled. It was not in the decision framework.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['tooling-lifecycle-cost'].stat2}. A 5-year lifecycle cost model: build cost + projected repair events × average repair cost + projected production loss from failure events. For this mold, the model would have shown the $52,000 quote generating a 5-year total cost of $210,000 and the $70,000 quote generating $112,000. The model takes 2 hours to build. It would have saved $98,000.\n\nTAKEAWAY (1:20–1:30): The tooling approval decision should be a 5-year cost decision. The data required is available from the toolmaker. The question is whether the procurement process asks for it.`,
    `PROBLEM (0:00–0:25): A tooling portfolio of 22 active molds. Average age: 3.2 years. Average remaining design life: projected 4 years. Actual performance: 6 of the 22 molds have already required full refurbishment. The refurbishments were not budgeted.\n\nCOST (0:25–0:50): ${PROBLEM_DATA['tooling-lifecycle-cost'].stat1}. 6 unplanned refurbishments at an average of $65,000 each: $390,000 in unbudgeted tooling cost over 3 years. ${PROBLEM_DATA['tooling-lifecycle-cost'].stat2}. All 6 molds that required early refurbishment were built to P20 pre-hardened steel at production volumes that required H13 hardened tool steel. The steel specification drove the failure rate.\n\nMISTAKE (0:50–1:10): The tooling approval process evaluated build cost and delivery lead time. Steel specification was accepted from the toolmaker without validation against the production volume, material, and cycle rate requirements of each program. For 6 of the 22 programs, the accepted specification was inadequate.\n\nFIX (1:10–1:25): ${PROBLEM_DATA['tooling-lifecycle-cost'].stat3}. A tooling specification validation checklist: for each program, verify steel specification against material, tonnage, cycle rate, and expected shot count. Flag programs where the accepted specification does not meet lifecycle requirements. Require the toolmaker to justify the specification — or upgrade it. Prevention cost: $0. Correction cost: $390,000 over 3 years.\n\nTAKEAWAY (1:25–1:30): Steel specification is a lifecycle cost decision made at tooling approval. Validate it before the PO is signed — not after the third refurbishment proves it was wrong.`,
    `PROBLEM (0:00–0:20): A production operations review. The tooling maintenance line on the P&L: $840,000 for the year on a 30-mold portfolio. The budget was $480,000. The variance is 75% above plan — attributed to "unplanned repairs."\n\nCOST (0:20–0:40): ${PROBLEM_DATA['tooling-lifecycle-cost'].stat1}. The $360,000 unplanned repair variance represents tooling lifecycle cost that was never modeled at program approval. ${PROBLEM_DATA['tooling-lifecycle-cost'].stat3}. For every dollar of tooling cost cut at approval across the 30-mold portfolio, an average of $4.20 was paid in the first 3 years of operation.\n\nMISTAKE (0:40–1:00): Tooling approvals across the portfolio were made on build cost — with the target of minimizing tooling capital spend. The lifecycle cost consequence of those decisions accumulated over 3 years into the $360,000 unplanned variance. The decisions that caused the variance were individually reasonable — each saved real money at approval. Together, they created a maintenance cost structure that was neither predictable nor budgetable.\n\nFIX (1:00–1:20): ${PROBLEM_DATA['tooling-lifecycle-cost'].stat2}. A lifecycle cost model for every tooling approval going forward: projected repair events, projected timing, estimated refurbishment cost, and production loss per failure event. The model turns tooling maintenance from an unbudgeted variance into a planned cost — and the tooling specification decisions change when lifecycle cost is in the comparison.\n\nTAKEAWAY (1:20–1:30): An $840,000 tooling maintenance variance was the result of 30 individual tooling approval decisions that optimized for build cost. Model the lifecycle cost instead — and the $840,000 becomes a budgeted, planned, and reducible number.`,
  ],
}

const RETENTION_BEATS: Record<string, string[]> = {
  'injection-molding-defects': ['Open with the defect type and cost stat to give viewers a concrete scenario immediately', 'Name the specific process parameter behind the defect at the midpoint — it establishes operator-level credibility', 'Close with the documentation discipline as the fix — specific and achievable without capital investment'],
  'tooling-failures': ['Lead with the cost comparison — build cost vs. lifecycle cost — to create immediate financial tension', 'Name the specific steel specification failure at the midpoint to give technical viewers an anchor', 'Close with the lifecycle cost model as the preventive action — a concrete tool viewers can apply'],
  'production-bottlenecks': ['Open with the throughput gap stat to surface the scale of the problem immediately', 'Introduce the cycle time audit as the diagnostic tool at the midpoint — gives viewers a specific action', 'Close with the capital vs. optimization comparison — the most impactful frame for plant managers and VPs'],
  'scrap-rework-cost': ['Lead with the scrap rate differential to establish the benchmark immediately', 'Name the process documentation failure as the root cause at the midpoint — reframes scrap as a process issue', 'Close with the implementation result — a documented outcome that validates the approach'],
  'mold-downtime': ['Open with the failure scenario at worst-case timing to maximize tension', 'Introduce the shot-count-based PM interval as the specific fix — actionable and calculable', 'Close with the cost comparison: PM cost vs. unplanned downtime cost — the ROI is explicit'],
  'poor-part-consistency': ['Lead with the assembly stoppage consequence — the downstream cost that makes the upstream problem urgent', 'Name the weight variation threshold at the midpoint — the specific metric most operations are not using', 'Close with the process monitoring result — documented yield improvement that validates the approach'],
  'scaling-inefficiencies': ['Open with the scale failure scenario to establish immediate relevance for product launch teams', 'Name the tooling specification failure at the midpoint — the specific variable that determines scale success', 'Close with the DFM review cost vs. engineering change cost — the ROI is calculated and compelling'],
  'material-waste': ['Lead with the waste percentage and dollar impact — makes an abstract material cost concrete immediately', 'Use the hot runner payback calculation at the midpoint — gives viewers a specific investment framework', 'Close with the tooling approval process change — a specific action that prevents future waste accumulation'],
  'process-cost-leakage': ['Open with the split metrics — uptime vs. OEE vs. cost variance — to establish that multiple reports can all be accurate while hiding the real problem', 'Name the SPC cost leakage reduction percentage at the midpoint — establishes a clear ROI for the monitoring investment', 'Close with the information system framing — positions process monitoring as a cost control tool, not a quality tool'],
  'tooling-lifecycle-cost': ['Lead with the refurbishment event and its true total cost — creates immediate financial tension', 'Name the steel specification failure as the specific variable at the midpoint — gives technical viewers a concrete anchor', 'Close with the lifecycle cost model as the preventive tool — something the viewer can build and apply at the next tooling approval'],
}

const BUSINESS_INSIGHTS: Record<string, string> = {
  'injection-molding-defects': `The financial exposure from injection molding defects compounds with volume. ${PROBLEM_DATA['injection-molding-defects'].cost1}. ${PROBLEM_DATA['injection-molding-defects'].cost2}. For a high-volume program producing 500,000 parts monthly at 10% defect rate, the monthly production cost of defects — resin, press time, labor, overhead — exceeds $75,000. The downstream escape cost, if defects reach assembly or the field, is an order of magnitude higher.`,
  'tooling-failures': `Tooling failure is a production cost problem presented as a maintenance event. ${PROBLEM_DATA['tooling-failures'].cost1}. ${PROBLEM_DATA['tooling-failures'].cost2}. A production program generating $180,000 per month in output and experiencing one unplanned mold failure annually absorbs $360,000–$1.08M in production revenue impact — from a tooling specification shortcut that saved $20,000–$30,000 at program approval.`,
  'production-bottlenecks': `Throughput loss in injection molding is recoverable without capital investment. ${PROBLEM_DATA['production-bottlenecks'].cost1}. ${PROBLEM_DATA['production-bottlenecks'].cost2}. A 10-press operation recovering 20% cycle efficiency has effectively added 2 presses of capacity to its existing asset base — without equipment purchase, facility expansion, or headcount addition. The cycle time audit is the diagnostic that quantifies the opportunity before the capital meeting is scheduled.`,
  'scrap-rework-cost': `Scrap cost in injection molding is a process investment decision. ${PROBLEM_DATA['scrap-rework-cost'].cost1}. ${PROBLEM_DATA['scrap-rework-cost'].cost2}. Moving from 15% to 3% scrap on a $400,000 monthly resin program recovers $48,000 per month in production cost — $576,000 annually — from process documentation and SPC implementation that costs a fraction of one year's savings. The ROI is explicit and fast.`,
  'mold-downtime': `Mold downtime is a budgetable, predictable cost — when the PM program exists. ${PROBLEM_DATA['mold-downtime'].cost1}. ${PROBLEM_DATA['mold-downtime'].cost2}. A 15-mold operation implementing shot-count-based PM reduces unplanned downtime by 60–80% — converting $108,000 in monthly throughput loss from reactive failures into a fraction of that cost in planned, scheduled maintenance events.`,
  'poor-part-consistency': `Part consistency is a supply chain cost when the supplier's process is unstable. ${PROBLEM_DATA['poor-part-consistency'].cost1}. ${PROBLEM_DATA['poor-part-consistency'].cost2}. For a Tier 1 supplier absorbing a 30% assembly stoppage rate premium from an inconsistent injection-molded component, the labor and overhead cost per additional stoppage event accumulates faster than any incoming inspection program can address it. The fix is upstream — at the molding press, not at the receiving dock.`,
  'scaling-inefficiencies': `Scale-up failure in injection molding has a predictable cost profile. ${PROBLEM_DATA['scaling-inefficiencies'].cost1}. ${PROBLEM_DATA['scaling-inefficiencies'].cost2}. The 8-week tooling rebuild lead time triggered by a scale-up failure creates customer delivery gaps that carry their own cost — expediting, premium freight, contractual penalties, and customer relationship exposure that exceeds the direct engineering change cost by a multiple.`,
  'material-waste': `Material efficiency is a tooling cost decision with a multi-year financial tail. ${PROBLEM_DATA['material-waste'].cost1}. ${PROBLEM_DATA['material-waste'].cost2}. On a $1.2M annual resin program, moving from 18% to 5% material waste through hot runner tooling and purge optimization saves $156,000 annually. The tooling investment required to achieve this recovers in year one — and runs a positive return for every subsequent year of the program.`,
  'process-cost-leakage': `Process cost leakage is the most consistently underreported cost category in injection molding operations. ${PROBLEM_DATA['process-cost-leakage'].cost1}. ${PROBLEM_DATA['process-cost-leakage'].cost2}. A 10-press injection molding operation implementing SPC and recovering 60% of its process leakage captures $1.26M in annual cost improvement — from a monitoring system that costs less than 2% of that figure to implement and operate.`,
  'tooling-lifecycle-cost': `Tooling lifecycle cost is a program cost multiplier that most procurement decisions underweight. ${PROBLEM_DATA['tooling-lifecycle-cost'].cost1}. ${PROBLEM_DATA['tooling-lifecycle-cost'].cost2}. A tooling portfolio of 20 active molds with an average build cost of $55,000 carries an expected 5-year lifecycle cost of $220,000–$440,000 per mold — $4.4M–$8.8M across the portfolio. Programs that modeled this at tooling approval selected specifications that reduced the lifecycle multiple. Programs that did not are paying the difference in repair, downtime, and scrap.`,
}

const VIDEO_CTAS: Record<string, string[]> = {
  'injection-molding-defects': [
    'If you are managing a molding operation and your defect rate varies by operator, your process is undocumented. That is worth a 15-minute audit conversation. Link in description.',
    'Comment with your current defect rate. I will outline the process parameters most likely driving it for your part type.',
    'Subscribe for weekly content on injection molding process control and cost reduction.',
  ],
  'tooling-failures': [
    'If your tooling approval process evaluates build cost only, the lifecycle cost model in the description is worth building before your next mold approval.',
    'Comment with your last unplanned tooling failure event — what the failure mode was and what it cost. Most viewers have one.',
    'Subscribe for weekly content on injection molding tooling and process engineering.',
  ],
  'production-bottlenecks': [
    'Before your next capital authorization for press capacity, run a cycle time audit on your active molds. The framework is in the description.',
    'Comment with your current OEE and the percentage attributable to cycle time versus downtime. Most operations have never broken it down.',
    'Subscribe for weekly content on injection molding throughput and process optimization.',
  ],
  'scrap-rework-cost': [
    'Comment with your current scrap rate. I will outline the process documentation approach that typically closes the gap for operations at your volume.',
    'The first-article process specification template is in the description — the starting point for moving from 15% scrap to 3%.',
    'Subscribe for weekly injection molding cost control content.',
  ],
  'mold-downtime': [
    'Ask your team for the shot count on your three highest-volume molds and when each was last inspected. The gap tells you your PM program status.',
    'Comment with your most expensive unplanned mold failure in the last 12 months. The number is usually larger than anyone formally calculated.',
    'Subscribe for weekly content on mold maintenance and production reliability.',
  ],
  'poor-part-consistency': [
    'If you are supplying injection-molded components to an assembly operation, ask for their stoppage rate data. It tells you more about your process stability than your own inspection does.',
    'Comment with your current part weight variation data. If you do not have it, that is the answer — and the first step.',
    'Subscribe for weekly content on injection molding quality and process stability.',
  ],
  'scaling-inefficiencies': [
    'Before your next production scale-up, download the DFM review checklist in the description. It covers the specific questions that catch scale-up failures before tooling is committed.',
    'Comment with the volume at which your last program was qualified versus the volume it was launched at. Most scale-up failures happen in that gap.',
    'Subscribe for weekly content on injection molding program launch and scale-up engineering.',
  ],
  'material-waste': [
    'Calculate your annual resin waste percentage before your next tooling approval meeting. If the number is above 8%, a hot runner analysis is worth running.',
    'Comment with your annual resin spend and current runner type. I will outline the payback calculation for hot runner conversion on your program.',
    'Subscribe for weekly content on material efficiency in injection molding operations.',
  ],
  'process-cost-leakage': [
    'If you can sum your scrap, overtime, yield shortfall, and resin overage from last year, the total as a percentage of revenue is your process cost leakage number. Post it in the comments.',
    'The SPC implementation sequence for injection molding is in the description — where to start, what to monitor first, and how to build the control system without disrupting production.',
    'Subscribe for weekly content on injection molding process cost control.',
  ],
  'tooling-lifecycle-cost': [
    'The 5-year tooling lifecycle cost model template is in the description. Build it for your next mold approval before the PO is signed.',
    'Comment with the steel specification on your highest-volume mold and what your actual repair frequency has been. The data tells the story.',
    'Subscribe for weekly content on injection molding tooling engineering and lifecycle cost management.',
  ],
}

const REPURPOSING_SUGGESTIONS: Record<string, string[]> = {
  'injection-molding-defects': ['Break the process parameter documentation framework into a LinkedIn carousel: "5 parameters to document before your next production launch"', 'Convert the defect cost calculation into a Twitter/X thread for injection molding engineers and plant managers', 'Use the escaped defect cost multiplier as an Instagram Reel hook with B-roll of a quality inspection station'],
  'tooling-failures': ['Turn the lifecycle cost model into a LinkedIn post: "Why the cheapest mold quote is almost never the lowest-cost mold"', 'Convert the failure mode explanation into a Facebook educational post for engineering managers', 'Use the two-quote comparison scenario as an Instagram carousel: "Two tooling quotes. Same part. Very different 5-year costs."'],
  'production-bottlenecks': ['Pull the cycle time audit finding into a LinkedIn post for plant managers and VPs of Manufacturing', 'Convert the capital vs. optimization comparison into a Twitter/X contrarian take', 'Use the phantom press concept as an Instagram Reel hook: "You are leaving 2 presses worth of throughput on the floor"'],
  'scrap-rework-cost': ['Turn the two-plant comparison into a LinkedIn post: "Same equipment, 11-point scrap rate difference. Here is what explains it."', 'Convert the process documentation framework into a Facebook educational post for operations managers', 'Use the scrap cost calculation as a Twitter/X thread for injection molding professionals'],
  'mold-downtime': ['Turn the PM interval calculation into a LinkedIn post for mold maintenance engineers', 'Convert the reactive vs. preventive maintenance cost comparison into a Facebook educational post', 'Use the 2 AM failure scenario as an Instagram Reel hook for plant managers'],
  'poor-part-consistency': ['Pull the assembly stoppage stat into a LinkedIn post for supply chain directors and OEM procurement teams', 'Convert the weight variation monitoring protocol into a Facebook educational post for quality engineers', 'Use the process monitoring vs. inspection framing as a Twitter/X contrarian take'],
  'scaling-inefficiencies': ['Turn the DFM review ROI into a LinkedIn post for product development engineers', 'Convert the three failed programs scenario into a Facebook case study post for engineering managers', 'Use the "scale amplifies what is already broken" angle as a Twitter/X contrarian take'],
  'material-waste': ['Pull the hot runner payback calculation into a LinkedIn post for plant managers', 'Convert the material waste tracking method into a Facebook educational post for operations teams', 'Use the two-program material efficiency comparison as an Instagram carousel: "Same part. Same material. 11% material cost difference."'],
  'process-cost-leakage': ['Turn the OEE gap attribution finding into a LinkedIn post for VPs of Manufacturing', 'Convert the SPC reduction stat into a Facebook educational post: "20–40% quality cost reduction from process monitoring"', 'Use the three-operation comparison as a Twitter/X thread showing the monitoring system impact on cost structure'],
  'tooling-lifecycle-cost': ['Pull the $3–$7 downstream cost ratio into a LinkedIn contrarian post: "The cheapest mold quote is not a cost decision. It is a program cost decision."', 'Convert the refurbishment calculation into a Facebook educational post for procurement and engineering teams', 'Use the tooling approval meeting angle as a Twitter/X thread for program managers and tooling engineers'],
}

export function generateYouTube(inputs: YouTubeInputs, seed: number = 0): YouTubeOutput {
  const v = seed % 3
  const p = inputs.problem
  const fmt = inputs.videoFormat

  const titleSet = TITLES[p] ?? TITLES['injection-molding-defects']
  const titleIdx = fmt === 'shorts' ? 0 : fmt === '60-90s' ? 1 : 2
  const titles = titleSet[titleIdx] ?? titleSet[0]
  const title = titles[v % titles.length] ?? titles[0]

  const thumbnailRaw = THUMBNAIL_TEXTS[p] ?? THUMBNAIL_TEXTS['injection-molding-defects']
  const thumbnailParts = thumbnailRaw.split('|')
  const thumbnailText = thumbnailParts[v % thumbnailParts.length] ?? thumbnailParts[0]

  const hooksArr = THREE_SECOND_HOOKS[p] ?? THREE_SECOND_HOOKS['injection-molding-defects']
  const threeSecondHook = hooksArr[v] ?? hooksArr[0]

  const openingArr = OPENING_LINES[p] ?? OPENING_LINES['injection-molding-defects']
  const openingLine = openingArr[v] ?? openingArr[0]

  const scriptArr = SCRIPT_OUTLINES[p] ?? SCRIPT_OUTLINES['injection-molding-defects']
  const scriptOrOutline = scriptArr[v] ?? scriptArr[0]

  const beatsArr = RETENTION_BEATS[p] ?? RETENTION_BEATS['injection-molding-defects']
  const retentionBeats = beatsArr

  const businessInsight = BUSINESS_INSIGHTS[p] ?? BUSINESS_INSIGHTS['injection-molding-defects']

  const ctasArr = VIDEO_CTAS[p] ?? VIDEO_CTAS['injection-molding-defects']
  const cta = ctasArr[v % ctasArr.length] ?? ctasArr[0]

  const repArr = REPURPOSING_SUGGESTIONS[p] ?? REPURPOSING_SUGGESTIONS['injection-molding-defects']

  const qualityScore = scoreContent(inputs, true, true, true, scriptOrOutline.split(' ').length)

  const improvementSuggestions = [
    'Add a specific part geometry or end market (automotive, medical, consumer) to anchor the scenario to a recognizable context for the target viewer.',
    'Include a specific resin type (PP, ABS, nylon) in the cost scenario — it grounds the material cost numbers in real production conditions.',
    'Reference the injection molding machine specification (tonnage, shot size) to give manufacturing engineers a concrete mental model for the scale of the cost scenario.',
  ]

  return {
    platform: 'youtube',
    title,
    thumbnailText,
    threeSecondHook,
    openingLine,
    scriptOrOutline,
    retentionBeats,
    businessInsight,
    cta,
    repurposingSuggestions: repArr.slice(0, 3),
    qualityScore,
    improvementSuggestions,
  }
}
