import type { FacebookInputs, FacebookOutput } from '../types'
import { PROBLEM_DATA } from '../lib/companyProfile'
import { scoreContent } from '../lib/scoring'

const SHORT_POSTS: Record<string, string[]> = {
  'fabrication-bottlenecks': [
    `When fabrication programs run late, the first question is usually "which vendor fell behind?"\n\nThe better question: "How many vendor handoffs did we build into this program?"\n\n${PROBLEM_DATA['fabrication-bottlenecks'].stat2}.\n\nThe delay is usually a structure problem — not a vendor problem. And structure is a decision made before production starts.`,
    `A fabrication bottleneck that starts in the forming stage can delay a construction project by four weeks.\n\nMost project managers don't find out until week three or four.\n\n${PROBLEM_DATA['fabrication-bottlenecks'].stat1}.\n\nThe cost isn't just in the fab shop. It's in every idle trade downstream.`,
    `Vendor count in a fabrication program is a risk variable.\n\nEvery vendor you add is another handoff.\n\nEvery handoff is a potential bottleneck.\n\n${PROBLEM_DATA['fabrication-bottlenecks'].stat2}.\n\nMost programs don't track this. The variance report explains why.`,
  ],
  'production-delays': [
    `If fabrication is late, everyone downstream pays for it.\n\n${PROBLEM_DATA['production-delays'].stat2}.\n\nThat's the daily cost before any change order is written.\n\nOn a project with four active trades and a three-week delay, the downstream idle cost can reach $200,000 before the first invoice arrives from the fab shop.`,
    `68% of construction project overruns trace back to fabrication and material delays.\n\nNot site conditions. Not labor availability.\n\nFabrication timing.\n\n${PROBLEM_DATA['production-delays'].stat3}.\n\nIf you're building contingency around on-site risk, you're covering the 32%.`,
    `The fabrication vendor said four weeks.\n\nAt week five: "We need one more."\n\n${PROBLEM_DATA['production-delays'].stat2}.\n\nEach day of delay on a commercial project with multiple mobilized trades is a four-to-five figure cost to the project.\n\nProduction visibility between order and delivery is the control that prevents this from being a surprise.`,
  ],
  'rework-scrap-cost': [
    `Rework in fabrication costs more than the fix.\n\n${PROBLEM_DATA['rework-scrap-cost'].stat2}.\n\nBut the 8 hours of remediation is the visible part. The invisible part is the delivery date that moves — and every downstream crew that adjusts around it.\n\nThe schedule cost is always larger than the remediation cost.`,
    `${PROBLEM_DATA['rework-scrap-cost'].stat1}.\n\nOn a $500,000 fabrication program, 10% rework is $50,000. Most of it from a process gap that a first-article inspection would have caught.\n\nThe inspection takes four hours. The rework takes weeks.`,
    `Shops running 15% scrap rates aren't using bad steel.\n\nThey're using poor nesting and programming practices.\n\n${PROBLEM_DATA['rework-scrap-cost'].stat3}.\n\nA 12% gap in scrap rate between shops is a measurable cost difference on any structural program — visible in the quote if you know to look for it.`,
  ],
  'labor-inefficiency': [
    `Labor is 35–50% of fabrication cost. It's also the variable most shops don't measure until a job closes.\n\n${PROBLEM_DATA['labor-inefficiency'].stat1}.\n\nA 25% productivity gap from poor sequencing doesn't show up on a daily report — it shows up in the variance when the job is done.`,
    `${PROBLEM_DATA['labor-inefficiency'].stat2}.\n\nSix to ten wasted supervisor hours per week on status chasing is a full workday of management capacity lost.\n\nThat capacity belongs on the shop floor — managing quality, sequencing, and throughput. Instead it's managing information gaps.`,
    `The shop that looks busiest is not always the shop that delivers on time.\n\n${PROBLEM_DATA['labor-inefficiency'].stat1}.\n\nActivity and efficiency are different things. The variance report shows you which one your fab vendor is running.`,
  ],
  'poor-project-coordination': [
    `The specification error discovered at delivery was not a vendor quality failure.\n\nIt was a coordination failure.\n\n${PROBLEM_DATA['poor-project-coordination'].stat2}.\n\nSame drawing. Two vendors. Two interpretations. The gap wasn't in the steel — it was in the communication.`,
    `${PROBLEM_DATA['poor-project-coordination'].stat1}.\n\n2.3x more coordination failures at three or more vendors.\n\nEvery additional vendor adds a communication surface. Coordination failures live on those surfaces — not in the individual vendor's work.`,
    `40% of late project completions trace to gaps between fabrication, finishing, and delivery coordination.\n\nNot to any single vendor's performance.\n\nTo the spaces between vendors — where nobody was responsible for alignment.\n\nThat's a program design problem, not a vendor problem.`,
  ],
  'missed-deadlines': [
    `${PROBLEM_DATA['missed-deadlines'].stat2}.\n\nMost project managers sign the contract, accept the lead time, and find out about the capacity problem when the delay happens.\n\nCapacity confirmation before order placement prevents most of these conversations.`,
    `The fabrication deadline miss cascades in ways that don't show up on the fab vendor's invoice.\n\n${PROBLEM_DATA['missed-deadlines'].stat1}.\n\n3–6 weeks of installation delay. Mobilized trades waiting. Extended general conditions. Penalty clause exposure.\n\nThe total project cost impact from one missed fab deadline routinely reaches six figures.`,
    `72% of project managers can't accurately forecast fabrication timing.\n\nNot because they're poor planners.\n\nBecause most fabrication vendors quote lead times without confirming production capacity — and most project managers accept them without asking.\n\nThe question "what is your current production backlog?" changes the conversation.`,
  ],
  'cost-overruns': [
    `The lowest fabrication bid rarely produces the lowest final cost.\n\n${PROBLEM_DATA['cost-overruns'].stat2}.\n\n$12,000–$85,000 in change orders from scope gaps. Each one identified during production — when leverage is minimum and cost is maximum.`,
    `${PROBLEM_DATA['cost-overruns'].stat3}.\n\nProjects that run a pre-production engineering review experience 3x fewer cost overruns.\n\nThe review is a four-hour meeting. The change orders it prevents average $40,000–$85,000 on commercial structural programs.`,
    `18–28% average cost overrun on complex structural fabrication programs.\n\nThat's not a sample size problem. It's a pattern.\n\nThe pattern is driven by procurement processes that optimize for bid price and skip the scope alignment review that controls final cost.`,
  ],
  'quality-inconsistency': [
    `Quality inconsistency in a multi-vendor fabrication program is not a vendor quality problem.\n\nIt's a standard alignment problem.\n\n${PROBLEM_DATA['quality-inconsistency'].stat3}.\n\nFour sources. Four interpretations of the same drawing. The result is consistent — and consistently more expensive than a single-source program.`,
    `${PROBLEM_DATA['quality-inconsistency'].stat1}.\n\n8–20% rejection at first inspection — not because any vendor was negligent, but because no unified QC standard was issued before production.\n\nThe rejection cost is $150–$400 per event. The schedule cost of discovering it at delivery is significantly larger.`,
    `The most expensive version of a quality failure in fabrication:\n\nDiscovered after installation has begun.\n\n${PROBLEM_DATA['quality-inconsistency'].stat2}.\n\n$150–$400 per weld correction in the shop. $1,500–$4,000+ in the field. The timing of discovery determines the cost.`,
  ],
  'equipment-downtime': [
    `One machine failure in a fabrication shop doesn't stop one process.\n\nIt stops the sequence.\n\n${PROBLEM_DATA['equipment-downtime'].stat1}.\n\n$1,200–$4,500/hour in throughput loss — before accounting for the downstream project impact of the delivery date moving.`,
    `${PROBLEM_DATA['equipment-downtime'].stat2}.\n\nShops with preventive maintenance programs experience 40–60% less unplanned downtime.\n\nThat difference is in your delivery dates. Whether the vendor discloses it or not.`,
    `CNC and plasma equipment averages 6–12 unplanned downtime hours per month in shops running above 80% utilization without a maintenance program.\n\n${PROBLEM_DATA['equipment-downtime'].stat1}.\n\nAt $3,000/hour average, that's $18,000–$36,000/month in throughput loss.\n\nAnd every hour of that loss is in the lead time your vendor quoted.`,
  ],
  'material-waste': [
    `The material waste in a fabrication quote is invisible — labeled as "material cost" with no percentage breakdown.\n\n${PROBLEM_DATA['material-waste'].stat1}.\n\nOn a $200,000 plate program at 20% waste: $40,000 of purchased steel became scrap.\n\nYou paid for it. It's not visible on the invoice.`,
    `${PROBLEM_DATA['material-waste'].stat3}.\n\nManual nesting generates 2–3x the waste of programmed nesting.\n\nSame steel. Same drawings. Two very different cost bases — and a difference of $30,000–$40,000 on a mid-size structural program.`,
    `Plate yield rate is the variable most customers never ask about when comparing fabrication quotes.\n\n${PROBLEM_DATA['material-waste'].stat2}.\n\n$8–$30 per square foot of wasted plate — in the quote as material cost.\n\nThe vendor who wastes 4% of steel is pricing differently than the vendor who wastes 20%. The quote doesn't show you that. The yield rate does.`,
  ],
}

const EDUCATIONAL_POSTS: Record<string, string[]> = {
  'fabrication-bottlenecks': [
    `If your fabrication programs consistently run behind schedule, the answer is usually not in the fab shop.\n\nIt's in the structure of how the program was set up.\n\nHere's what project managers and OEMs need to understand about fabrication bottlenecks:\n\n**Why Multi-Vendor Programs Create Bottlenecks**\n\nMost commercial and industrial fabrication programs distribute work across multiple vendors — one for cutting, one for forming, one for welding, sometimes more.\n\nEach vendor manages their own timeline. When everyone hits their individual milestone, the program looks on track.\n\nBut inter-vendor handoffs — the transitions between vendors — are coordination surfaces that nobody manages. When any one of them slips, every downstream vendor stops.\n\n${PROBLEM_DATA['fabrication-bottlenecks'].stat2}.\n\n**The Cascade Effect**\n\n${PROBLEM_DATA['fabrication-bottlenecks'].stat3}.\n\nA bottleneck at one stage affects every stage that follows. When cutting is complete but forming is backed up, welding can't start. When welding can't start, assembly is on hold. When assembly is on hold, delivery moves.\n\nThe project manager sees idle trades on-site. The bottleneck is in the shop — and was visible weeks earlier.\n\n**The Cost**\n\n${PROBLEM_DATA['fabrication-bottlenecks'].stat1}.\n\nDownstream idle labor at $800–$2,500/day per trade. On a project with three active trades, a two-week fabrication bottleneck generates $33,600–$105,000 in idle labor cost before the first change order.\n\n**The Structural Fix**\n\nSingle-source fabrication — one shop managing cutting, forming, welding, finishing, and delivery coordination — eliminates the inter-vendor handoff as a failure point.\n\nOne timeline. One escalation path. One point of accountability for the entire sequence.\n\n**Questions to Ask Before Structuring Your Next Program**\n\n→ How many vendor handoffs does this program require?\n→ Who is accountable for each handoff?\n→ What is the escalation protocol when a vendor runs behind?\n→ Have we confirmed each vendor's capacity for their phase before committing the sequence?\n\nThe answers determine whether the bottleneck is prevented or managed after it appears. Prevention is always cheaper.`,
  ],
  'production-delays': [
    `Fabrication delays are the leading cause of construction project overruns — responsible for 68% of timeline and cost variances in commercial and industrial projects.\n\nDespite this, fabrication timing is the planning variable that receives the least scrutiny.\n\nHere's what every project manager and OEM should understand:\n\n**The Downstream Cost of a Fabrication Delay**\n\nWhen fabrication falls behind, the cost is not contained in the fab shop. It travels downstream — and compounds daily.\n\n${PROBLEM_DATA['production-delays'].stat2}.\n\nOn a project with four mobilized trades, a three-week fabrication delay generates $67,200–$210,000 in downstream idle labor cost alone. That number does not include penalty clause exposure, extended general conditions, or out-of-sequence work rework.\n\n**Why Fabrication Timing Is Difficult to Forecast**\n\n${PROBLEM_DATA['production-delays'].stat3}.\n\nMost fabrication vendors quote lead times based on estimated capacity — not confirmed production scheduling. When vendors take on additional work after your order is placed, your lead time extends without notice.\n\n**The Financial Impact**\n\n${PROBLEM_DATA['production-delays'].stat1}.\n\nA 20% timeline extension on a six-month project is five weeks. Most project contingencies don't cover five weeks of downstream costs across multiple trades.\n\n**What Reliable Fabrication Partners Do Differently**\n\nVendors with consistent on-time delivery records share a few practices:\n\n→ Production milestone schedules issued at order placement — not just a delivery date\n→ Weekly production status updates with confirmed milestone completion\n→ Early escalation when a milestone is at risk — not notification after the delivery has slipped\n→ Capacity confirmation before accepting an order — not after\n\n**How to Protect Your Project Timeline**\n\nBefore placing a fabrication order:\n→ Confirm current production backlog\n→ Ask for the production milestone schedule\n→ Confirm which equipment is running your job and its current utilization\n→ Agree on an escalation protocol\n\nThese questions cost nothing to ask. The cost of not asking is in the stats above.`,
  ],
  'rework-scrap-cost': [
    `Rework in metal fabrication is one of the most significant — and consistently underestimated — cost drivers in commercial and industrial projects.\n\nHere's a complete breakdown of where rework costs come from, what they look like in real dollar terms, and how well-run fabrication programs prevent them:\n\n**The Three Costs of Rework**\n\nMost project budgets track the first cost. The second and third are where the real exposure lives.\n\n*Cost 1: Material*\nThe steel that was cut, formed, or welded incorrectly and must be replaced. Visible. Measurable. Often the smallest of the three.\n\n*Cost 2: Labor*\n${PROBLEM_DATA['rework-scrap-cost'].stat2}.\n\nFour to eight hours per structural rework event. Before accounting for lift rental, crew coordination, or production scheduling disruption.\n\n*Cost 3: Schedule*\nThe delivery date that moves. The installation window that shifts. The downstream trades that adjust. The extended general conditions.\n\nThis cost never appears on a rework invoice. It is almost always the largest of the three.\n\n**The Financial Scale**\n\n${PROBLEM_DATA['rework-scrap-cost'].stat1}.\n\nOn a $500,000 fabrication program, that's $25,000–$60,000 in direct rework cost. Schedule impact adds a multiple of that number.\n\n${PROBLEM_DATA['rework-scrap-cost'].stat3}.\n\nThe gap between 3% and 15% scrap on a $200,000 material program: $24,000 in wasted material.\n\n**What Creates the Rework**\n\nThe root causes are consistent:\n→ Incomplete or unclear drawings issued to the vendor\n→ No first-article inspection before full production run\n→ No inter-stage dimensional check between cutting, forming, and welding\n→ Assumptions made about tolerance requirements that weren't explicit in the drawing\n\n**How Well-Run Shops Prevent It**\n\n→ First-article inspection: the first piece off each new setup is inspected and approved before full run begins\n→ In-process dimensional checks at forming and pre-weld stages\n→ Final inspection with documented acceptance criteria before shipping\n\nNone of these steps are expensive. All of them are far cheaper than discovering a problem at delivery.\n\n**What to Ask Your Fabrication Vendor**\n\n→ What is your scrap rate on comparable programs?\n→ Do you run first-article inspection? At which stages?\n→ What are your documented QC checkpoints?\n→ What is your rework frequency on programs like this?\n\nThese answers separate shops that prevent rework from shops that remediate it.`,
  ],
  'cost-overruns': [
    `Fabrication cost overruns average 18–28% on complex structural programs.\n\nThis is a documented pattern — not random variance. It's produced by the same set of planning decisions, project after project.\n\nHere's what drives it and how to prevent it:\n\n**The Change Order Pattern**\n\nCost overruns in fabrication almost always follow the same sequence:\n\n1. Program is bid from drawings that contain scope ambiguities\n2. Vendor wins on low bid based on optimistic scope assumptions\n3. Production begins — scope ambiguities surface as production decisions\n4. Vendor issues change orders to cover scope gaps\n5. Project manager has no leverage — steel is already cut\n\n${PROBLEM_DATA['cost-overruns'].stat2}.\n\nOn a $400,000 structural program, the average change order exposure lands between $48,000 and $112,000. The fabrication vendor did not cause these costs. The planning process that allowed scope gaps to reach production did.\n\n**Why the Lowest Bid Produces the Highest Cost**\n\nA bid is an estimate of what the vendor thinks they can do with the information provided. When the information is incomplete — and it usually is — the vendor's estimate is based on best-case scope assumptions.\n\nFinal cost reflects actual scope — including everything the drawings didn't specify.\n\n${PROBLEM_DATA['cost-overruns'].stat1}.\n\n**The Front-End Engineering Review**\n\n${PROBLEM_DATA['cost-overruns'].stat3}.\n\nThe single most effective mechanism for controlling fabrication cost overruns is a pre-production engineering review that covers:\n\n→ Drawing completeness — are all dimensions, tolerances, and material callouts specified?\n→ Weld standard alignment — which standard applies, and is it consistently called out?\n→ Surface treatment specification — coating, primer, galvanizing requirements fully defined?\n→ Tolerance confirmation — are dimensional requirements explicit and achievable with the specified process?\n→ Material grade verification — are all material specifications confirmed and available?\n\nThis review costs a few hours. It prevents the change orders listed above.\n\n**Practical Steps for Your Next Program**\n\n→ Require the review before issuing orders — not as an option, as a process step\n→ Document sign-off from the fabrication vendor on scope completeness\n→ Build change order authority into the contract with explicit approved scope as the basis\n→ Track bid-to-final-cost variance across programs — the pattern will identify your highest-risk vendor relationships`,
  ],
  'quality-inconsistency': [
    `Quality inconsistency across fabrication vendors is one of the most predictable — and preventable — problems in multi-source manufacturing programs.\n\nUnderstanding why it happens and how to prevent it is essential for any OEM or project manager running complex fabrication programs.\n\n**Why Multi-Vendor Programs Produce Quality Inconsistency**\n\nQuality consistency requires a consistent standard.\n\nWhen multiple vendors are executing against the same drawing, each interprets that drawing through their own process standards, tolerance norms, and inspection criteria.\n\n${PROBLEM_DATA['quality-inconsistency'].stat3}.\n\nThis is not a vendor quality problem. It is a standard ambiguity problem — and it's structural.\n\n**The Financial Impact**\n\n${PROBLEM_DATA['quality-inconsistency'].stat1}.\n\nAn 8–20% rejection rate at first inspection in a 200-component program is 16–40 components requiring remediation.\n\n${PROBLEM_DATA['quality-inconsistency'].stat2}.\n\nAt $300 average per weld remediation event: $4,800–$12,000 in direct remediation cost. The schedule impact of discovering this at delivery adds a multiple of that number.\n\n**When Quality Failures Are Discovered**\n\nQuality failures in multi-vendor programs are almost never caught during production — they're caught at receiving, at inspection, or after installation begins.\n\nEach stage of late discovery multiplies the cost:\n→ Caught in production: fix before value is added, minimal schedule impact\n→ Caught at receiving: full material and labor cost sunk, schedule disrupted\n→ Caught after installation: full remediation in the field at 3–5x shop cost plus schedule compression\n\n**How to Create Consistency Across Multiple Vendors**\n\nOption 1: Project-Specific QC Documentation\n\nIssue project-specific quality requirements — not just drawings — to all vendors before production begins. This includes:\n→ Explicit tolerance requirements with allowable variance\n→ Weld inspection criteria and acceptance standards\n→ Surface preparation and coating requirements\n→ Dimensional verification protocol and documentation format\n→ First-article inspection requirement with results submitted before full run\n\nOption 2: Single-Source Fabrication\n\nConsolidating to a single fabrication source eliminates the standard ambiguity problem entirely. One shop applies one standard consistently. The result: ${PROBLEM_DATA['quality-inconsistency'].stat3.split(',')[0].toLowerCase()} — the opposite direction.\n\n**Practical Steps**\n\n→ Require first-article inspection results from all vendors before full run\n→ Define acceptance criteria explicitly — not by reference to general standards, but in project-specific documentation\n→ Track rejection rates by vendor across programs — the pattern is predictable once measured`,
  ],
  'labor-inefficiency': [
    `Labor is the largest cost variable in metal fabrication — representing 35–50% of total production cost.\n\nIt's also the variable that most fabrication shops manage least rigorously, and that most customers never evaluate when selecting a vendor.\n\nHere's what labor inefficiency looks like, what it costs, and how it shows up in the projects you manage:\n\n**How Labor Inefficiency Manifests**\n\n${PROBLEM_DATA['labor-inefficiency'].stat1}.\n\nPoor shop floor sequencing creates invisible productivity loss. The shop appears busy — every station has work, every welder is occupied. But the sequence is wrong. Jobs are waiting at bottleneck stations. In-process material is building up at transitions. Supervisors are resolving sequencing conflicts instead of managing production.\n\nThe output: 20–35% less productive labor on the same headcount.\n\n**The Management Time Cost**\n\n${PROBLEM_DATA['labor-inefficiency'].stat2}.\n\nSix to ten hours per supervisor per week on status chasing is a full workday of management capacity lost. That capacity should be on the shop floor — managing quality, throughput, and process discipline. Instead, it's managing information gaps.\n\n**The Financial Impact on Your Programs**\n\n${PROBLEM_DATA['labor-inefficiency'].stat3}.\n\nAt 40% of fabrication cost, a 25% labor productivity gap means:\n→ 10% cost overrun on every job — embedded in actual labor hours\n→ Extended production timelines — the same scope takes longer to complete\n→ Compressed delivery windows — catch-up production produces quality risk\n\nThis cost is invisible in the estimate. It surfaces in the variance report when the job closes.\n\n**What Efficient Shops Do Differently**\n\nShops with consistently low labor variance have specific management practices:\n\n→ Sequenced job routing — every job moves through the floor in a documented sequence, not on-the-fly decisions\n→ Visual production management — job status is visible without asking\n→ Clear handoff protocols — what the next station needs before it can start is defined and confirmed\n→ Supervisor time on production management — status is communicated through systems, not through conversations\n→ Labor hours per unit tracked against estimate on every closed job\n\n**What to Ask a Fabrication Vendor**\n\nBefore placing a significant order:\n→ What is your shop floor management system?\n→ How do supervisors track job status without asking?\n→ What is your average actual-versus-estimated labor variance on comparable programs?\n\nThe vendor who can answer these questions clearly runs a different shop floor than the one who can't.`,
  ],
  'missed-deadlines': [
    `Missed fabrication deadlines are the most common — and most expensive — cause of commercial project timeline failures.\n\nUnderstanding why they happen and how to prevent them is one of the highest-value things a project manager or OEM can do for their programs.\n\n**Why Fabrication Deadlines Are Missed**\n\n${PROBLEM_DATA['missed-deadlines'].stat3}.\n\nMost missed deadlines trace to the same root cause: the lead time was accepted without confirming production capacity.\n\nVendors quote lead times based on estimated capacity at the time of quotation. Between quote and production start, they accept additional orders. By the time your job enters the queue, the original timeline is no longer achievable.\n\nWithout a confirmation process, the project manager discovers this when the delivery date passes.\n\n**The Cost of a Missed Deadline**\n\nMissed fabrication deadlines carry multiple cost layers:\n\n${PROBLEM_DATA['missed-deadlines'].stat2}.\n\nAt $25,000/week and a two-week delay: $50,000 in penalties before any downstream costs are counted.\n\n${PROBLEM_DATA['missed-deadlines'].stat1}.\n\nA 3–6 week installation window push means:\n→ Three mobilized trades idling at $800–$2,500/day each\n→ Extended general conditions\n→ Penalty clause exposure\n→ Possible out-of-sequence work creating downstream rework\n\nTotal project cost impact from a single two-week fabrication delay: frequently exceeds $100,000 on commercial builds.\n\n**Confirming Vendor Capacity Before Order Placement**\n\nAsk every fabrication vendor before placing an order:\n→ What is your current production backlog?\n→ What is your material procurement lead time for this program?\n→ Which specific equipment will run this job, and what is its current utilization rate?\n→ What are the production milestones — not just the delivery date — for this order?\n\n**Building Production Visibility Into the Program**\n\nRequire from your vendor:\n→ A production milestone schedule at order placement\n→ Weekly milestone completion confirmation during production\n→ An agreed escalation protocol if any milestone is at risk — surfaced immediately, not at delivery\n\nThe vendors who will commit to this process are the vendors whose lead times are worth trusting.`,
  ],
  'equipment-downtime': [
    `Equipment downtime in a metal fabrication shop doesn't just stop one machine.\n\nIt stops the sequence — and every process that depends on that machine's output idles until capacity is restored.\n\nHere's what that costs, why it's predictable, and what separates fabrication shops with reliable delivery from those without:\n\n**The Cascade Effect of Equipment Downtime**\n\nMetal fabrication is a sequential process. Cutting precedes forming. Forming precedes welding. Welding precedes finishing.\n\nWhen a CNC plasma or laser cutter goes down:\n→ Cutting stops immediately\n→ In-process material for forming runs out\n→ Welding has no new components to process\n→ The entire production sequence pauses until the machine is restored\n\n${PROBLEM_DATA['equipment-downtime'].stat1}.\n\n$1,200–$4,500/hour in throughput loss. In an 8-hour unplanned downtime event: $9,600–$36,000 in production value that didn't happen. And every job queued behind the failed machine moves on the delivery calendar.\n\n**Why It Happens Predictably**\n\n${PROBLEM_DATA['equipment-downtime'].stat2}.\n\nShops without preventive maintenance programs experience 40–60% more unplanned downtime. Not because their equipment is worse — because scheduled maintenance windows don't exist.\n\n${PROBLEM_DATA['equipment-downtime'].stat3}.\n\nHigh utilization without maintenance planning is a failure accumulation strategy. The question is when it occurs — not whether.\n\n**How to Evaluate a Vendor's Equipment Reliability**\n\nBefore placing a significant order with a fabrication vendor:\n\n→ Ask for the preventive maintenance schedule for the specific equipment running your job\n→ Ask for their average unplanned downtime frequency per machine per month\n→ Ask what their process is when a machine failure occurs mid-program\n\nThe vendor who can answer these questions clearly has a maintenance program. The vendor who can't is managing equipment reactively — and your delivery date is exposed to their maintenance posture.\n\n**Practical Implication for Program Timing**\n\nThe lead time your fabrication vendor quotes assumes their equipment runs. In a reactive maintenance shop at high utilization, that assumption has a meaningful probability of failure.\n\nFactor equipment reliability into your vendor selection criteria the same way you factor quality and price. The connection to delivery reliability is direct and measurable.`,
  ],
  'material-waste': [
    `Material waste is the fabrication cost variable that's invisible in quotes and consistent across invoices.\n\nIt's built into every line that says "material cost" — without a percentage breakdown, without an explanation, and without the customer ever seeing what fraction of their spend became scrap.\n\nHere's what the numbers look like and what to do about it:\n\n**The Waste Rate Reality**\n\n${PROBLEM_DATA['material-waste'].stat1}.\n\nShops using manual cut layout and freehand marking regularly waste 12–22% of plate steel input. On a $200,000 plate program, that's $24,000–$44,000 in steel purchased and scrapped.\n\n${PROBLEM_DATA['material-waste'].stat3}.\n\nThe gap between manual and programmed nesting is 2–3x in waste rate. The same drawing, the same steel, cut by a shop with nesting software versus a shop without: measurably different material costs.\n\n**How It Shows Up in Quotes**\n\nMaterial waste does not appear as a line item in a fabrication quote. It appears as part of "material cost."\n\nWhen a vendor quotes $85,000 for a structural steel package, that number includes:\n→ The steel in the finished product (accountable)\n→ The steel that was wasted in production (embedded, unlabeled)\n\n${PROBLEM_DATA['material-waste'].stat2}.\n\nAt 20% waste on a $150,000 material program: $30,000 of your material spend is waste. At 4% waste: $6,000. The $24,000 difference is in the quote — you just can't see it without the yield rate.\n\n**The Business Impact**\n\nOn repeat programs — the kind that run quarterly or annually — material waste rates compound:\n→ A $150,000/quarter plate program with a 15% waste vendor vs. a 3% waste vendor: $18,000/quarter difference\n→ Over a year: $72,000 in preventable material cost\n\nNot visible in the quote. Entirely visible in the yield rate.\n\n**What to Ask Every Fabrication Vendor**\n\n→ What is your plate yield rate on comparable programs?\n→ Do you use programmed nesting software or manual layout?\n→ What is your typical scrap weight per unit on this part type?\n\nThe vendor who uses programmed nesting and tracks yield rate is pricing from an efficient cost basis. The vendor who doesn't is building waste into their quote — and the customer pays it without a line item.\n\n**Practical Takeaway**\n\nAdd plate yield rate to your vendor qualification criteria. It's one of the most impactful and least-used evaluation metrics in fabrication procurement.`,
  ],
}

const DISCUSSION_PROMPTS: Record<string, string> = {
  'fabrication-bottlenecks': "For project managers and OEMs in the group: what's the most impactful fabrication bottleneck you've dealt with, and where did it actually originate? The cost, the cause, and what you'd do differently.",
  'production-delays': "This one is for project managers: what's your best example of a fabrication delay that cascaded into a significant project cost? What was the downstream impact, and did you ever trace the full cost back to the original delay?",
  'rework-scrap-cost': "For anyone managing fabrication programs: what's your current process for catching rework before it compounds? First-article inspection, in-process checks, end-of-line only? And what's the most expensive rework event you've seen — what caused it?",
  'labor-inefficiency': "For fabrication shop managers and OEMs in the group: how are you currently tracking labor efficiency in your production operations? Hours per unit, variance by job type, or something else? What's worked and what hasn't?",
  'poor-project-coordination': "For project managers: what's your coordination structure on multi-vendor fabrication programs? Who owns the inter-vendor handoffs? And what's the most costly coordination failure you've seen — what caused it and what would have prevented it?",
  'missed-deadlines': "For project managers and OEMs: what's your current process for confirming fabrication vendor capacity before committing to a project timeline? And what's the most expensive deadline miss you've managed — what was the total project cost impact?",
  'cost-overruns': "For project managers and procurement officers: what's your average bid-to-final-cost variance on fabrication programs? Are you tracking it? And what's the most significant change order event you've managed — what caused it and what would have prevented it?",
  'quality-inconsistency': "For OEMs and project managers running multi-vendor fabrication programs: what's your current rejection rate at first inspection? Are you tracking it by vendor? What's been the most impactful quality improvement process change you've made?",
  'equipment-downtime': "For fabrication shop managers and procurement officers: how are you evaluating vendor equipment reliability when selecting fabrication partners? And what's the most disruptive equipment failure you've dealt with — what was the timeline and cost impact?",
  'material-waste': "For procurement officers and project managers: have you ever asked a fabrication vendor for their plate yield rate before selecting them? What did you find? And for shop managers in the group — what's your current nesting efficiency, and how do you measure it?",
}

const BUSINESS_OWNER_POSTS: Record<string, string[]> = {
  'fabrication-bottlenecks': [
    `After managing 200+ fabrication programs, the single most consistent predictor of on-time delivery is not vendor quality, not equipment capability, and not workforce size.\n\nIt's vendor count.\n\nPrograms structured around one fabrication source deliver on time at 90%+.\n\nPrograms structured around three or more vendors deliver on time at 60–65% — with 30–50% more production stoppages.\n\n${PROBLEM_DATA['fabrication-bottlenecks'].stat2}.\n\nThe data is consistent. Coordination surface area is the variable that predicts outcomes.\n\nFor OEMs and project managers managing complex programs: your vendor structure is a delivery performance variable. Treat it like one.`,
    `The most expensive fabrication programs I've seen were not the most complex.\n\nThey were the most fragmented — spread across multiple vendors with no coordination owner, no inter-vendor milestone tracking, and no escalation protocol.\n\n${PROBLEM_DATA['fabrication-bottlenecks'].stat1}.\n\nEach vendor did their individual work well. The program still ran behind.\n\nThe failures were all in the handoffs — the spaces between vendors where nobody was responsible.\n\nConsolidation to single-source fabrication on these programs consistently reduced timeline variance by 30–40%. Not because the work was done better. Because the coordination surface was eliminated.`,
  ],
  'production-delays': [
    `The most impactful thing I've seen project managers do for their project outcomes is add fabrication timeline confirmation to their vendor selection process.\n\nNot just accepting the quoted lead time — confirming it against current production backlog, material lead time, and equipment availability.\n\n${PROBLEM_DATA['production-delays'].stat3}.\n\nThe lead time confirmation process takes one 30-minute conversation before order placement. The downstream cost of skipping it is documented in 68% of project overruns.\n\nFor OEMs and project managers: this is the highest ROI process addition available in fabrication program management.`,
  ],
  'cost-overruns': [
    `We started requiring a pre-production engineering review on every fabrication program three years ago.\n\nBefore that requirement, our average bid-to-final-cost variance was 22%.\n\nAfter: 7%.\n\n${PROBLEM_DATA['cost-overruns'].stat3}.\n\nThe review is a four-hour meeting. It covers drawings, specifications, tolerances, surface treatment, and weld standards — with explicit vendor sign-off before production authorization.\n\nEvery change order it has prevented was visible in that review as an unanswered question.\n\nFor OEMs and project managers: if you're not running this meeting, the unanswered questions are still there. You'll just be answering them with change orders.`,
  ],
  'quality-inconsistency': [
    `We ran a quality analysis across our multi-vendor programs three years ago.\n\nRejection rate at first inspection with four vendors: 17%.\n\nRejection rate with a single-source vendor using our project-specific QC documentation: 3%.\n\n${PROBLEM_DATA['quality-inconsistency'].stat3}.\n\nThe vendors in the multi-vendor program were not low-quality. They were running their standard process — which didn't match our project requirements because we never issued project-specific requirements.\n\nThe fix was not replacing vendors. It was issuing explicit QC documentation before production.\n\nFor OEMs: if your rejection rate is consistently above 5%, the problem is in your pre-production documentation process — not in your vendors.`,
  ],
  'material-waste': [
    `We added plate yield rate to our vendor qualification criteria two years ago.\n\nBefore that, we compared quote prices.\n\nAfter the first evaluation round: our lowest-price vendor had a 19% plate waste rate. Our highest-price vendor had a 4% waste rate.\n\n${PROBLEM_DATA['material-waste'].stat1}.\n\nOn our largest structural program, the cost difference between those two waste rates was $34,000.\n\nThe "more expensive" vendor was cheaper.\n\nFor procurement officers: add yield rate to your vendor qualification criteria. The quote price is what the vendor thinks the job costs. The yield rate tells you how efficiently they'll execute it.`,
  ],
}

const RETARGETING_POSTS: Record<string, string[]> = {
  'fabrication-bottlenecks': [
    `If you've been following our content on fabrication program structure, here's the practical application:\n\nBefore your next multi-vendor program starts, map the handoffs.\n\nFor each inter-vendor transition, answer:\n→ Who triggers the handoff?\n→ Who confirms readiness on the receiving end?\n→ What's the escalation path if the handoff fails?\n\nIf those questions don't have clear answers, the coordination failure is already designed into the program.\n\nFabcon manages the full fabrication sequence — cutting, forming, welding, finishing, delivery — under one contract. One timeline. One accountability point.\n\nIf you're evaluating your current vendor structure, we'd be glad to walk through the coordination risk map for your specific program type.`,
  ],
  'production-delays': [
    `If you've experienced fabrication delays that cascaded into significant project cost, this is the practical step:\n\nBefore your next fabrication order, require:\n→ A production milestone schedule — not just a delivery date\n→ Weekly milestone confirmation during production\n→ An agreed escalation protocol when a milestone is at risk\n\nVendors who will commit to this process are vendors whose lead times are reliable.\n\nFabcon provides production milestone visibility and proactive escalation as standard program practice.\n\nIf you'd like to understand what transparent production tracking looks like in practice, we're available for a 15-minute conversation.`,
  ],
  'cost-overruns': [
    `If you've been tracking bid-to-final-cost variance across your fabrication programs and the number isn't where it should be, here's the practical step:\n\nFor your next program, require a pre-production engineering review as a process step — not an option.\n\nThe review covers: drawing completeness, specification alignment, tolerance confirmation, surface treatment clarity.\n\nVendors who run this meeting catch scope gaps before production. The ones who don't charge for them as change orders.\n\nFabcon runs a pre-production review on every program as standard practice.\n\nIf you'd like to understand what that review looks like and how it's structured, we can walk through it for your specific program type.`,
  ],
  'quality-inconsistency': [
    `If rejection rates at first inspection are a consistent challenge across your fabrication programs, here's the practical question:\n\nAre you issuing project-specific QC documentation to every vendor before production — not just drawings?\n\nExplicit tolerance requirements, weld acceptance standards, inspection checkpoints, first-article inspection requirements.\n\nThe shops that produce consistent quality against those documents are identifiable by their process — before you've seen a single part.\n\nFabcon uses documented QC standards with first-article inspection on every program. Rejection rates at first inspection run under 3%.\n\nIf you'd like to understand how we structure the pre-production quality alignment process, we're available to walk through it.`,
  ],
  'missed-deadlines': [
    `If fabrication deadline misses have been a consistent challenge in your project programs, here's the practical question:\n\nWhat does your vendor capacity confirmation process look like before order placement?\n\nIf the answer is "we accept the quoted lead time," the risk is already present.\n\nCapacity confirmation, milestone scheduling, and early escalation are the practices that distinguish vendors who hit their dates from those who explain why they didn't.\n\nFabcon provides production milestone schedules at order placement and proactive milestone communication throughout production.\n\nIf you'd like to understand what that process looks like in practice, we're available for a 15-minute conversation.`,
  ],
}

const PRACTICAL_TAKEAWAYS: Record<string, string> = {
  'fabrication-bottlenecks': 'Map the vendor handoffs in your current fabrication program. For each transition, identify who is accountable for confirming readiness. If the answer is unclear, the coordination failure is already designed in. Assign it before production starts.',
  'production-delays': 'Before your next fabrication order, confirm vendor capacity against current backlog — not just the quoted lead time. Ask for the production milestone schedule, not just the delivery date. The milestone schedule tells you where the risk is.',
  'rework-scrap-cost': 'Ask your fabrication vendor for their scrap rate on comparable programs and whether they run first-article inspection. These two questions filter out the quotes that look cheap and deliver expensively.',
  'labor-inefficiency': 'Ask your fabrication vendor for actual versus estimated labor variance on their last five comparable programs. A shop that tracks this data manages labor efficiency. A shop that doesn\'t tracks equipment — and lets labor cost drift.',
  'poor-project-coordination': 'Before your next multi-vendor program, run a pre-production specification alignment meeting with all vendors present. Document sign-off on tolerances, weld standards, and surface treatment requirements. One meeting prevents most specification errors.',
  'missed-deadlines': 'Before placing a fabrication order with a penalty timeline commitment, confirm production capacity — not the quoted lead time. Ask for backlog, material readiness, and equipment availability. These questions are free to ask and expensive to skip.',
  'cost-overruns': 'Require a pre-production engineering review on your next fabrication program. Cover drawings, specifications, tolerances, and weld standards with vendor sign-off before production authorization. Every change order this prevents was visible as an unanswered question in that review.',
  'quality-inconsistency': 'Issue project-specific QC documentation to every fabrication vendor before production — not just drawings. Define tolerance requirements, weld acceptance criteria, and first-article inspection requirements explicitly. The vendors who produce consistent quality against those documents are identifiable by their process.',
  'equipment-downtime': 'Ask your fabrication vendor for the preventive maintenance schedule on the specific equipment running your job. The vendor who can produce it has a maintenance program. The vendor who can\'t is managing equipment reactively — and your delivery date is exposed to that posture.',
  'material-waste': 'Add plate yield rate to your vendor qualification criteria before your next fabrication program. Ask every vendor for their waste rate on comparable programs. The number separates vendors pricing from an efficient cost basis from vendors building waste into their quote.',
}

const CTAS: Record<string, string> = {
  'fabrication-bottlenecks': 'What does your current vendor structure look like on your most active fabrication program? Share in the comments — or message us directly if you\'d like a coordination risk review of your program.',
  'production-delays': 'What\'s your current process for managing production visibility between order placement and delivery? Comment below — and if you\'d like to discuss production tracking for your next program, we\'re available for a 15-minute conversation.',
  'rework-scrap-cost': 'What does your current vendor QC process look like, and what\'s your typical rejection rate at first inspection? Share below — or contact us if you\'d like to discuss QC process standards for your program type.',
  'labor-inefficiency': 'Have you tracked labor variance on your fabrication programs? Comment with your experience — and if you\'d like to understand how we manage labor efficiency on complex programs, we\'re available to discuss.',
  'poor-project-coordination': 'Who owns inter-vendor coordination in your current fabrication programs? Comment below — or contact us to discuss program coordination structure for your next project.',
  'missed-deadlines': 'What\'s your current process for confirming vendor capacity before committing to a project timeline? Share below — or contact us to discuss production milestone tracking for your next program.',
  'cost-overruns': 'What\'s your bid-to-final-cost variance across your last several fabrication programs? Comment below — or contact us to discuss how a pre-production review would apply to your specific program type.',
  'quality-inconsistency': 'What\'s your rejection rate at first inspection across your fabrication vendors? Comment below — or contact us to discuss QC standards and single-source fabrication options for your program.',
  'equipment-downtime': 'Have you asked your fabrication vendors about their maintenance programs? Comment below — and if you\'d like to discuss equipment reliability as part of vendor selection, we\'re available.',
  'material-waste': 'Have you asked your fabrication vendors for their plate yield rate? Comment below — and if you\'d like to understand how material efficiency factors into our quoting process, we\'d be glad to walk through it.',
}

export function generateFacebook(inputs: FacebookInputs, seed: number = 0): FacebookOutput {
  const v = seed % 3
  const p = inputs.problem
  const fmt = inputs.contentFormat

  let primaryPost: string

  if (fmt === 'short') {
    const postsArr = SHORT_POSTS[p] ?? SHORT_POSTS['fabrication-bottlenecks']
    primaryPost = postsArr[v] ?? postsArr[0]
  } else if (fmt === 'educational') {
    const eduArr = EDUCATIONAL_POSTS[p] ?? EDUCATIONAL_POSTS['fabrication-bottlenecks']
    primaryPost = eduArr[v % eduArr.length] ?? eduArr[0]
  } else if (fmt === 'discussion') {
    const postsArr = SHORT_POSTS[p] ?? SHORT_POSTS['fabrication-bottlenecks']
    primaryPost = postsArr[v] ?? postsArr[0]
  } else if (fmt === 'business-owner') {
    const boArr = BUSINESS_OWNER_POSTS[p] ?? BUSINESS_OWNER_POSTS['production-delays']
    primaryPost = boArr[v % boArr.length] ?? boArr[0]
  } else {
    const retArr = RETARGETING_POSTS[p] ?? RETARGETING_POSTS['fabrication-bottlenecks']
    primaryPost = retArr[v % retArr.length] ?? retArr[0]
  }

  const practicalTakeaway = PRACTICAL_TAKEAWAYS[p] ?? PRACTICAL_TAKEAWAYS['fabrication-bottlenecks']
  const cta = CTAS[p] ?? CTAS['fabrication-bottlenecks']
  const discussionQuestion = DISCUSSION_PROMPTS[p] ?? DISCUSSION_PROMPTS['fabrication-bottlenecks']

  const repurposing = [
    'Turn the educational post into a LinkedIn article with added data points and industry-specific examples.',
    'Convert the practical takeaway into an Instagram carousel with one slide per action item.',
    'Use the discussion question as a Twitter/X engagement post — fabrication operators respond to specific operational questions.',
  ]

  const qualityScore = scoreContent(inputs, true, true, true, primaryPost.split(' ').length)

  const improvementSuggestions = [
    'Add a specific project type (commercial construction, OEM manufacturing, industrial installation) to make the scenario immediately relatable to your target reader.',
    'Include a question in the post body — Facebook posts with questions receive significantly higher comment engagement than declarative posts.',
    'Tag a specific pain point metric in the first paragraph — a dollar figure or percentage anchors the reader\'s attention before the explanation.',
  ]

  return {
    platform: 'facebook',
    primaryPost,
    practicalTakeaway,
    cta,
    discussionQuestion,
    repurposingSuggestions: repurposing,
    qualityScore,
    improvementSuggestions,
  }
}
