import type { FacebookInputs, FacebookOutput } from '../types'
import { PROBLEM_DATA } from '../lib/companyProfile'
import { scoreContent } from '../lib/scoring'

const PRIMARY_POSTS: Record<string, string[]> = {
  'manufacturing-bottlenecks': [
    `If your electronics program keeps running behind schedule, the issue usually isn't on the assembly floor.\n\nIt's upstream — in design handoffs, component kitting, or inter-vendor coordination.\n\n${PROBLEM_DATA['manufacturing-bottlenecks'].stat1}.\n\n${PROBLEM_DATA['manufacturing-bottlenecks'].stat2}.\n\nThe structural fix is simpler than most teams expect: consolidate to a single EMS partner who manages all stages. One timeline. One point of accountability. No inter-vendor gaps where delays form.\n\n${PROBLEM_DATA['manufacturing-bottlenecks'].consequence}`,
    `Here's something worth checking before your next production run:\n\nHow many separate vendors are involved in moving a board from design to delivery?\n\nEvery handoff between them is a potential delay surface.\n\n${PROBLEM_DATA['manufacturing-bottlenecks'].stat3}.\n\nMost program teams manage bottlenecks reactively — after the delay has started. The programs that avoid them map their handoff surfaces before production and assign clear ownership to each one.\n\nThat's the difference between a bottleneck and a managed risk.`,
    `Electronics manufacturing bottleneck math:\n\nA 3-day SMT stoppage × 2 idle engineering teams × $3,000/day = $18,000 in downstream cost.\n\nFrom a hold that started in an incomplete component kit — not on the assembly line.\n\n${PROBLEM_DATA['manufacturing-bottlenecks'].stat2}.\n\nIf your EMS program has more than one assembly partner, you have more handoff surfaces than you have owners for them. That's where delays live.\n\nThe fix: map the handoffs, assign ownership, and consolidate where you can't do both.`,
  ],
  'supplier-inconsistency': [
    `Component supplier inconsistency is the most common unplanned production event in electronics manufacturing.\n\nAnd it almost always shows up at the worst time — at kitting, when production is already scheduled.\n\n${PROBLEM_DATA['supplier-inconsistency'].stat1}.\n\nThe prevention isn't complicated: pre-qualify approved alternates for every long-lead or single-source component before production is scheduled. When the primary goes on allocation, the alternate is ready and production continues.\n\nMost programs skip this step. The ones that don't rarely have production holds.`,
    `Something worth thinking about if you manage electronics production:\n\nHow many distributors are in your supply chain for your most critical components?\n\n${PROBLEM_DATA['supplier-inconsistency'].stat2}.\n\nMore distributors doesn't mean more options — it means more incoming verification burden and more substitution risk. Each distributor is a potential source of a non-approved substitute.\n\nApproved manufacturer list compliance at receiving, combined with a consolidated distributor strategy, is the most reliable way to keep supplier inconsistency out of production.`,
    `A first-article rejection caused by a supplier substitution is the most frustrating failure mode in electronics manufacturing.\n\nThe design was correct.\nThe assembly process was correct.\nThe wrong component was in the kit.\n\n${PROBLEM_DATA['supplier-inconsistency'].stat3}.\n\n28–42% of first-article failures trace here. The fix is upstream — in the supply chain qualification process, not in the assembly process.\n\nIf you're seeing first-article failures that don't trace to design or assembly issues, the supply chain is where to look.`,
  ],
  'qa-failures': [
    `Here's the QA cost calculation most electronics programs haven't done:\n\n• Defect caught during in-process inspection: rework cycle, 20 minutes\n• Same defect caught in the field: RMA processing, root cause investigation, yield hold on all prior shipments\n\n${PROBLEM_DATA['qa-failures'].stat1}.\n\nThe inspection architecture — specifically where inspection happens relative to the manufacturing process — is the variable that determines which cost you pay.\n\nPrograms that invest in SPI, AOI, and X-ray inspection pay the 20-minute cost. Programs that don't pay the field return cost.`,
    `If your electronics program ships BGA or QFN components without X-ray inspection, this is worth knowing:\n\nBGA and QFN solder joints are invisible to visual inspection. They can't be evaluated optically.\n\n${PROBLEM_DATA['qa-failures'].stat2}.\n\n15–25% higher field return rates without formal AOI and X-ray. The field return rate is determined by the inspection architecture — before the first board ships.\n\nX-ray inspection after reflow is not optional for BGA and QFN packages. It's the only way to know what solder joint quality actually looks like.`,
    `1 in 3 first-article rejections in electronics assembly traces to incomplete IPC acceptance criteria.\n\nNot to assembly errors.\nNot to component issues.\nTo a documentation gap.\n\n${PROBLEM_DATA['qa-failures'].stat3}.\n\nThe IPC acceptance criteria defines what the assembly team is building to. When it's incomplete, the team builds to their best interpretation — which may not match the contract requirement.\n\nBefore the first board goes down the line, the acceptance criteria should be documented, signed, and communicated to every inspection station. It's a documentation task. It prevents a very expensive rejection.`,
  ],
  'production-delays': [
    `71% of hardware launch overruns trace to PCB manufacturing delays.\n\nMost engineering teams know this intuitively — and still don't price the risk into their program schedules.\n\n${PROBLEM_DATA['production-delays'].stat2}.\n\nThe cost compounds quickly. Two teams idle for two weeks isn't a PCB problem. It's a $60,000–$112,000 program problem that started with an incomplete manufacturing release package.\n\nA manufacturing readiness review before every PCB release takes 2 hours. It catches the documentation gaps that cause the delays that generate those downstream costs.`,
    `Something most hardware programs get wrong about PCB lead times:\n\nThe quoted lead time assumes a complete, release-ready manufacturing package.\n\nIncomplete Gerbers. Unresolved BOM questions. Missing fabrication notes. Each one adds clarification cycles to the fabrication process — which extend the actual lead time beyond what was quoted.\n\n${PROBLEM_DATA['production-delays'].stat3}.\n\n71% of hardware launch overruns trace to PCB delays. Most of those delays were documentation delays — preventable with a manufacturing readiness review before release.`,
    `The firmware team went idle for three weeks waiting on boards.\n\nThe delay traced to a controlled impedance question on a high-speed signal layer — not called out in the fabrication notes. The fabricator flagged it at production rather than assuming.\n\n${PROBLEM_DATA['production-delays'].stat1}.\n\nAn 18–30% average timeline extension from PCB delays. In a regulated market, those weeks can determine whether a product makes the current submission cycle.\n\nThe manufacturing readiness review is the process that catches these gaps before they become production holds.`,
  ],
  'component-shortages': [
    `38% of electronics programs require a design respin due to component shortages.\n\nSix to fourteen weeks added to the program schedule. A new validation cycle. A regulatory test cycle if it's a medical or defense product. A market window that may not wait.\n\n${PROBLEM_DATA['component-shortages'].stat2}.\n\nMost of those respins were preventable. The components that caused them were on allocation watch lists before the program was scheduled. Approved alternates, pre-qualified at the design stage, would have eliminated the respin.\n\nComponent risk strategy is a design decision. By production, the exposure is already set.`,
    `Here's the math on component shortages that most programs haven't run:\n\n${PROBLEM_DATA['component-shortages'].stat3}.\n\n180–400% spot market cost premium during allocation events.\n\nOn a 10,000-unit program with a $3 affected component:\n• Spot market sourcing: $54,000–$120,000 in unplanned cost\n• Approved alternate (pre-qualified): $0 in additional cost\n\nThe approved alternate qualification is a one-time investment. The spot market premium is per production run.\n\nThe math makes the qualification decision straightforward — when it's made at the right stage.`,
    `The component shortage event is not a supply chain failure.\n\nIt's the predictable outcome of a supply chain strategy that didn't account for allocation risk.\n\n${PROBLEM_DATA['component-shortages'].stat1}.\n\n38% of programs requiring design respins. In most of those cases, the affected component's EOL or allocation status was visible months before production was scheduled.\n\nThe difference between programs that respin and programs that don't: approved alternates pre-qualified before production is scheduled. That's it.`,
  ],
  'rework-scrap-cost': [
    `Rework in electronics manufacturing has three costs — and most program budgets only account for one.\n\nFirst: the material. The component replaced or the board scrapped.\n\nSecond: the technician time — and the risk. ${PROBLEM_DATA['rework-scrap-cost'].stat2}. Three to six hours, with risk of pad lift and adjacent component stress.\n\nThird — and most expensive: the test repeat. Every rework event requires a full test cycle. On a complex board with a 4-hour test, that's 4 hours added per rework event.\n\n${PROBLEM_DATA['rework-scrap-cost'].stat1}.\n\nIn-process inspection prevents all three. That's the ROI calculation.`,
    `The scrap rate in your electronics program tells you more about your EMS partner's process discipline than almost any other single metric.\n\n${PROBLEM_DATA['rework-scrap-cost'].stat3}.\n\nScrap rates of 1–3% in disciplined operations versus 6–14% in undisciplined ones. Same equipment. Same components. Different inspection architecture.\n\nSPI before reflow. AOI after placement. X-ray after reflow for BGAs. Each stage catches the defect while it's cheapest to correct.\n\nIf your EMS partner doesn't report scrap rate by program, ask for it. The number will tell you exactly where process investment is needed.`,
    `Something worth calculating on your current production program:\n\nWhat is your rework rate as a percentage of total production cost?\n\n${PROBLEM_DATA['rework-scrap-cost'].stat1}.\n\n4–11% as the documented range without robust in-process inspection. On a $400,000 production program at 7% rework, that's $28,000 not in the original estimate.\n\nMost programs track rework as a quality metric — how many boards required rework. Tracking it as a financial metric — what percentage of total production cost went to rework — changes how the inspection investment looks.`,
  ],
  'compliance-risk': [
    `If your electronics program serves defense, medical, or other regulated markets, this is worth verifying before the next production run:\n\nIs your EMS partner ITAR-registered? ISO-certified for your specific market? Do their documented inspection criteria match the IPC class you specified in the contract?\n\n${PROBLEM_DATA['compliance-risk'].stat1}.\n\nA 4–8 week compliance hold is not a quality event. It's a revenue event, a customer commitment event, and in some cases a contract performance event.\n\nVerification before production takes 30 minutes. The hold it prevents takes months.`,
    `Here's something most electronics program managers don't know about ITAR compliance:\n\nThe OEM who directed manufacturing carries equal or greater liability than the EMS partner who executed it.\n\n${PROBLEM_DATA['compliance-risk'].stat3}.\n\n$250,000 minimum penalty per ITAR incident. No warning. No corrective action period.\n\nEMS partner ITAR registration verification is a 10-minute task. For programs with defense or dual-use applications, it's a mandatory step — not an assumption.\n\nIf you haven't verified your EMS partner's ITAR registration status in writing, that's the first step.`,
    `Traceability documentation in electronics manufacturing is not paperwork.\n\nIt's the evidence that a controlled process produced a controlled product.\n\n${PROBLEM_DATA['compliance-risk'].stat2}.\n\n3x higher audit failure rate without traceability documentation. When a regulatory auditor or customer audit requests documentation for a specific production lot, the traceability system is what makes that response possible.\n\nSpecify traceability requirements in the EMS partner contract before production. What records, what format, what retention period. If it's not in the contract, it may not be in the documentation.`,
  ],
  'scaling-complexity': [
    `If you're preparing for your first high-volume electronics production run, here's what the data says about the prototype-to-production transition:\n\n${PROBLEM_DATA['scaling-complexity'].stat1}.\n\n45–65% more defect events per board in the first three production runs. Not because the design changed — because the design was validated for bench performance, not for SMT line manufacturing variation at volume.\n\nA DFM review with your EMS partner before layout completion is the highest-ROI step in the NPI process. It surfaces the design elements that will cause production failures before the first board is built.`,
    `Something most hardware teams discover too late in the production scaling process:\n\nECOs during production are 12–28% more expensive per unit than ECOs made before production entry.\n\n${PROBLEM_DATA['scaling-complexity'].stat3}.\n\nEach ECO at production stage requires a revised Gerber, an updated stencil, a process requalification, and in some cases a regulatory re-submission.\n\nThe same change at layout stage: a 10-minute correction.\n\nThe DFM review before layout completion is what makes that 10-minute correction happen at layout stage instead of production stage.`,
    `Scaling from prototype to production without a formal NPI process:\n\n${PROBLEM_DATA['scaling-complexity'].stat2}.\n\n8–16 additional weeks to stabilize yield. During those weeks, engineering is burning cycles on production defects that a structured DFM and first-article process would have caught before the first board was built.\n\nThe programs that hit their yield targets in the first production run all have one thing in common: a formal NPI process that includes DFM review, first-article inspection with documented pass criteria, and a yield gate before full production release.`,
  ],
  'cost-leakage': [
    `Here's a question worth running on your last closed electronics program:\n\nWhat was the final production cost versus the original budget?\n\n${PROBLEM_DATA['cost-leakage'].stat1}.\n\n8–18% above budget as the documented average. Not from a single unexpected event — from a series of individually approved decisions that accumulated into an overrun.\n\nSubstitution qualification costs. Additional rework cycles. Extended program management. Expedite fees. Each approved. None aggregated against the original budget.\n\nCost leakage is controllable — but only if it's tracked at the decision point, not discovered at close-out.`,
    `The BOM substitution process in most electronics programs tracks one thing: the component price delta.\n\n${PROBLEM_DATA['cost-leakage'].stat2}.\n\nWhat it doesn't track: the qualification testing cost, the updated acceptance criteria documentation cost, the process re-verification time, and the schedule impact of the verification delay.\n\nOn a substitution that saves $0.15 per unit, those untracked costs routinely exceed $10,000 — making the substitution net-negative on a per-program basis.\n\nTracking the total cost burden of every substitution changes the approval calculus significantly.`,
    `20–35% of field failures in electronics programs are shipping escapes — defects that passed internal inspection.\n\n${PROBLEM_DATA['cost-leakage'].stat3}.\n\nThe test coverage decision made during program setup determines that rate. It's a cost decision — but it's made as a scope decision, without calculating the field failure cost of an untested escape.\n\nThe cost of a shipping escape: RMA processing, root cause investigation, replacement unit, and in regulated markets, potential regulatory notification. At $500–$2,000 per unit, that's a test coverage ROI calculation worth running before program setup.`,
  ],
  'poor-manufacturing-decisions': [
    `The most expensive manufacturing decision in an electronics program is made before manufacturing starts.\n\nIt's made at the PCB design stage — in via type selection, layer stack-up, component footprint choices, and whether a DFM review happens before layout completion.\n\n${PROBLEM_DATA['poor-manufacturing-decisions'].stat1}.\n\nA 22–40% higher production cost from bypassing DFM review. On a 5,000-unit program at $45 per board, 30% premium is $67,500 — determined before the first Gerber was submitted.\n\nDFM review is cost control at the design stage. It's not overhead. It's the highest-ROI intervention in the program.`,
    `Here's something worth knowing before selecting an EMS partner:\n\n${PROBLEM_DATA['poor-manufacturing-decisions'].stat2}.\n\n2.5x more mid-program quality events when EMS selection is based on price alone.\n\nThe savings are real at the quote stage. The first quality event is where they disappear.\n\nEMS evaluation criteria that filters for the right outcome: documented inspection infrastructure (SPI, AOI, X-ray), IPC certification level, first-pass yield data on comparable programs, and a DFM review process included in onboarding.\n\nThese criteria predict production outcomes. Bid price doesn't.`,
    `A practical electronics manufacturing tip for PCB designers:\n\n${PROBLEM_DATA['poor-manufacturing-decisions'].stat3}.\n\n$4–$18 per board in avoidable fabrication cost from the wrong via type, trace width, or stack-up selection.\n\nOn 5,000 units, that's $20,000–$90,000 in avoidable cost determined in a CAD tool — before any board was ordered.\n\nA 30-minute DFM call with your EMS partner before layout is complete will catch these decisions while they're still inexpensive to change. Most EMS partners offer this. Most designers don't schedule it until after the Gerbers are generated.`,
  ],
}

const PRACTICAL_TAKEAWAYS: Record<string, string> = {
  'manufacturing-bottlenecks': 'Map every vendor handoff in your EMS program — from design to fabrication to assembly to test. Each handoff without a single accountable owner is a bottleneck surface. Assign ownership before production starts.',
  'supplier-inconsistency': 'For every long-lead or single-source component in your BOM, identify and pre-qualify an approved alternate before production is scheduled. When the primary goes on allocation, the alternate is ready — no production hold required.',
  'qa-failures': 'Define IPC acceptance criteria for every component package type before the first board goes down the line. Ensure SPI, AOI, and X-ray coverage matches your package types. Document the criteria at each inspection station.',
  'production-delays': 'Run a manufacturing readiness review before every PCB release: BOM completeness, Gerber verification, fabrication notes completeness, and long-lead component availability confirmation. Two hours before release prevents two weeks of delay.',
  'component-shortages': 'During schematic capture, identify every component with a lead time over 10 weeks or a single-source supply relationship. Pre-qualify an approved alternate for each one. Add the alternate to the BOM before production is scheduled.',
  'rework-scrap-cost': 'Track rework cost as a percentage of total production cost — not just as a count of boards reworked. If the percentage exceeds 3%, evaluate which inspection stages are missing. Each stage prevents the defect modes that compound into expensive rework events.',
  'compliance-risk': 'Before selecting an EMS partner for a regulated program, verify: ITAR registration (for defense/dual-use), ISO certification scope (9001, 13485, or AS9100 as applicable), and IPC class compliance documentation. Require written confirmation — not verbal assurance.',
  'scaling-complexity': 'Before your next production scaling run: complete a DFM review with your EMS partner before layout is finalized, define first-article inspection pass criteria before the first board is built, and set a yield target gate before full production release.',
  'cost-leakage': 'Build a rolling program cost model that captures the total cost burden of every substitution, rework event, and test coverage decision — not just the direct component or labor cost. Update it at every significant decision point during the program.',
  'poor-manufacturing-decisions': 'Before your next PCB layout is finalized, schedule a 30-minute DFM review with your EMS partner. Bring the schematic and stack-up. Ask specifically about via requirements, minimum clearances, component footprint support, and controlled impedance callouts.',
}

const DISCUSSION_QUESTIONS: Record<string, string> = {
  'manufacturing-bottlenecks': "Where has your last PCB production bottleneck actually started — design handoff, component kitting, inter-vendor coordination, or somewhere else? Drop your experience in the comments.",
  'supplier-inconsistency': "Has your electronics program ever experienced a production hold from a supplier inconsistency or non-approved substitution event? What was the root cause — and was it preventable?",
  'qa-failures': "What in-process inspection steps does your EMS program currently include — SPI, AOI, X-ray, or a subset? Have you seen a field return event that would have been caught by a missing inspection stage?",
  'production-delays': "What percentage of your PCB deliveries match the originally quoted lead time? Have you ever traced a hardware launch delay back to a manufacturing readiness gap in the release package?",
  'component-shortages': "How do you currently manage component shortage risk in your electronics programs? Approved alternates, buffer stock, long-term supplier agreements — or mostly reactive sourcing when a shortage hits?",
  'rework-scrap-cost': "What is your current first-pass yield rate on your most complex PCB? And do you track rework cost as a financial metric or only as a quality metric? The two framings lead to very different investment decisions.",
  'compliance-risk': "When did you last verify your EMS partner's compliance certification scope — not just confirm they hold a certificate? Have you ever had a compliance hold that could have been prevented by a pre-production verification?",
  'scaling-complexity': "What was the first-pass yield difference between your most recent prototype build and first production run? And did you complete a formal DFM review before production entry?",
  'cost-leakage': "Have you completed a post-program cost reconciliation on a closed electronics program? What was the variance between original budget and final cost — and what were the primary drivers?",
  'poor-manufacturing-decisions': "Has a PCB design decision — via type, stack-up, footprint choice — ever added significant unexpected cost to a production program? And was the decision made without input from the EMS partner before layout was complete?",
}

const CTAS: Record<string, string> = {
  'manufacturing-bottlenecks': "If you'd like to map the handoff surfaces in your current EMS program structure, we can walk through it together — comment below or send us a message.",
  'supplier-inconsistency': "If you want to run a component risk audit on your current BOM — identifying single-source parts and substitution risk — reach out and we'll share the framework.",
  'qa-failures': "If you'd like to evaluate your current inspection architecture against your package types and defect history, we can outline the gaps in 15 minutes.",
  'production-delays': "If you want the manufacturing readiness review checklist we use before every PCB release, comment 'READINESS' and we'll share it.",
  'component-shortages': "If you want to run an approved alternate audit on your current BOM, comment 'ALTERNATES' and we'll share the process we use.",
  'rework-scrap-cost': "If you want to model the ROI of in-process inspection upgrades against your current rework rate, message us and we'll build the calculation for your program.",
  'compliance-risk': "If you're preparing for a regulated program and want a compliance verification checklist for EMS partner evaluation, comment 'COMPLIANCE' and we'll share it.",
  'scaling-complexity': "If you're approaching your first high-volume production run and want a DFM review checklist tailored to your stack-up and assembly complexity, reach out.",
  'cost-leakage': "If you want to build a rolling program cost model that tracks leakage in real time, we can walk through the structure together — message us.",
  'poor-manufacturing-decisions': "If you'd like a DFM pre-check on your current PCB design before layout is complete, we're glad to walk through it — comment below with your stack-up details.",
}

const REPURPOSING: Record<string, string[]> = {
  'manufacturing-bottlenecks': ['Convert to a LinkedIn post with a tighter hook and the cost stat as the lead', 'Use the discussion question as a Twitter/X engagement post', 'Turn the practical takeaway into an Instagram caption with a process diagram visual'],
  'supplier-inconsistency': ['Expand into a LinkedIn post focused on supply chain consolidation as a QA strategy', 'Use the discussion question as a Twitter/X engagement post for procurement professionals', 'Convert the practical takeaway into an Instagram carousel on approved alternate strategy'],
  'qa-failures': ['Turn into a LinkedIn post focused on in-process inspection as cost control', 'Use the IPC criteria stat as a standalone Twitter/X post', 'Convert the practical takeaway into an Instagram story sequence'],
  'production-delays': ['Expand into a LinkedIn post on manufacturing readiness review ROI', 'Use the 71% stat as a standalone Twitter/X post for hardware program managers', 'Convert the practical takeaway into an Instagram carousel on PCB release checklist'],
  'component-shortages': ['Turn into a LinkedIn post on approved alternates as a design-stage decision', 'Use the spot market cost premium as a standalone Twitter/X post', 'Convert the practical takeaway into an Instagram carousel on BOM risk management'],
  'rework-scrap-cost': ['Expand into a LinkedIn post focused on first-pass yield as a financial metric', 'Use the scrap rate differential as a standalone Twitter/X post', 'Convert the practical takeaway into an Instagram carousel on in-process inspection stages'],
  'compliance-risk': ['Turn into a LinkedIn post on EMS partner compliance verification before regulated programs', 'Use the ITAR penalty stat as a standalone Twitter/X post for defense program managers', 'Convert the practical takeaway into an Instagram carousel on compliance checklist'],
  'scaling-complexity': ['Expand into a LinkedIn post on DFM review ROI for hardware scaling programs', 'Use the yield stabilization stat as a standalone Twitter/X post', 'Convert the NPI process into an Instagram carousel'],
  'cost-leakage': ['Turn into a LinkedIn post on tracking substitution cost burden versus component delta', 'Use the shipping escape stat as a standalone Twitter/X post', 'Convert the rolling cost model into an Instagram carousel'],
  'poor-manufacturing-decisions': ['Expand into a LinkedIn post on DFM bypass cost premium', 'Use the via type cost stat as a standalone Twitter/X post for PCB designers', 'Convert the EMS selection criteria into an Instagram carousel'],
}

export function generateFacebook(inputs: FacebookInputs, seed: number = 0): FacebookOutput {
  const v = seed % 3
  const p = inputs.problem

  const postsArr = PRIMARY_POSTS[p] ?? PRIMARY_POSTS['manufacturing-bottlenecks']
  const primaryPost = postsArr[v] ?? postsArr[0]

  const practicalTakeaway = PRACTICAL_TAKEAWAYS[p] ?? PRACTICAL_TAKEAWAYS['manufacturing-bottlenecks']
  const cta = CTAS[p] ?? CTAS['manufacturing-bottlenecks']
  const discussionQuestion = DISCUSSION_QUESTIONS[p] ?? DISCUSSION_QUESTIONS['manufacturing-bottlenecks']
  const repArr = REPURPOSING[p] ?? REPURPOSING['manufacturing-bottlenecks']

  const qualityScore = scoreContent(inputs, true, true, true, primaryPost.split(' ').length)

  const improvementSuggestions = [
    'Add a specific market segment (medical devices, defense electronics, industrial IoT) to make the scenario more recognizable to your target audience.',
    'Include a specific dollar figure or percentage from your own program data to make the financial impact tangible and credible.',
    'End with an open question that invites operations managers and engineering directors to share their own experience with this pain point.',
  ]

  return {
    platform: 'facebook',
    primaryPost,
    practicalTakeaway,
    cta,
    discussionQuestion,
    repurposingSuggestions: repArr.slice(0, 3),
    qualityScore,
    improvementSuggestions,
  }
}
